deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
This commit updates the WMC CRD as it has lagged behind the codebase. This
commit was done by running `operator-sdk generate crds`.
=> Update WMC CRD

build/Dockerfile, build/Dockerfile.ci
=> [wmco] Updated payload tree diagram for dockerfiles

README.md
=> [docs] Update README for running e2e locally

hack/run-ci-e2e-test.sh, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/tracker/tracker.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/main_test.go, test/e2e/validation_test.go
- Add more informative debugging and info messages that give feedback to user as to what the operator is doing
- Improve the error messages to reflect the error scenario
- Update the operator-sdk command in the hack script to increase the debugging level
- s/configmap/ConfigMap
=> [wmco] Improve comments, logs and error messages

pkg/controller/windowsmachineconfig/tracker.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/internal/wget-ignore-cert.ps1
- [wmco] Update wget-ignore-cert.ps1 to run over ssh
- [wmco] Replace Run calls with RunOverSSH
=> [wmco] Run all Windows commands over ssh

README.md, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/create_test.go, test/e2e/validation_test.go
This PR introduces generation of user data for connecting to the
windows vm through ssh configuration. This data includes a script for sending
the public key created using private key and required config for sshd.
=> [wmco] Generate userData secret

go.mod, go.sum, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/windows/connectivity.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
- Use WNI to only create the Windows VM
- Implement all required connectivity methods in a separate object
=> [wmco] Use key based auth for Windows interactions 

README.md
- Fix up explanation of how to replace infrastructureID
- Rename windows_image_with_container_runtime_installed to  windows_container_ami
- Replaces instances of zone with <zone> and region with <region> and explain how to use them
- Replace <role> with worker
=> [docs] Fix MachineSet example in README

pkg/controller/windowsmachine/windows/windows.go
This PR fixes the copy destination for Windows binaries
and config files, this will ensure only the files required
for one time operation are stored in Temp directory and the
ones that need to be preserved longer are stored in C:\k
directory on the Windows node.
=> Bug 1840251: Fix file copy destination for Windows

pkg/controller/windowsmachine/windows/windows.go, pkg/internal/wget-ignore-cert.ps1
Depends on https://github.com/openshift/windows-machine-config-bootstrapper/pull/223
/hold
=> [controller] Switch to Ignition config spec v3.1 

build/Dockerfile, build/Dockerfile.ci, pkg/controller/windowsmachine/nodeconfig/init.go, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, pkg/controller/windowsmachine/windows/windows.go, pkg/controller/windowsmachine/windowsmachine_controller.go, pkg/internal/wget-ignore-cert.ps1, test/e2e/create_test.go, test/e2e/validation_test.go
This PR includes multiple commits to fix https://bugzilla.redhat.com/show_bug.cgi?id=1875528 and the symptoms related to it.
=> Bug 1875528: Allow reconfiguration of Windows machines after partial configuration failure

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml
This reverts commit 3f0c1620477daff4fa5066b03117a6ae1976e4e8.
=> Revert "[ci] Run operator deployment on control plane"

pkg/controller/windowsmachine/windowsmachine_controller.go
As of now, WMCO is reconciling successfully on the following conditions:
- When machine doesn't have internal IP
- Whem machine doesn't have nodeRef missing
- When the machine object doesn't have an internal IP
WMCO also ignores the machines that were created before WMCO starts as we're
ignoring the Creat Events
This commit should address the above issues
=> Bug 1882526: [wmco] Improve requeuing

.gitmodules, build/Dockerfile, build/Dockerfile.ci, docs/HACKING.md, hack/lint-gofmt.sh
This PR adds git submodules for WMCB, Kubernetes, ovn-kubernetes, CNI plugins
to reference them as subdirectories within wmco repository. This is a requirement to add
Cachito support with git submodules.
=> WINC-516: Add git submodules for Cachito support

build/Dockerfile, build/Dockerfile.ci
Remove `COPY . .` so that we can take advantage of image caching.
=> [build] Remove "COPY . ."  from Dockerfiles

pkg/controller/windowsmachine/windows/windows.go
This change was made to reduce code duplication in the creation and start of Windows services, as well as when checking if a particular file exists on the VM. This makes it easier when adding new services into Windows VM configuration.
=> [wmco] Refactor Windows service start/creation

pkg/controller/secret/secret_controller.go, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, pkg/controller/windowsmachine/windows/windows.go, pkg/controller/windowsmachine/windowsmachine_controller.go
- [wmco] Improve logging
- [wmco] Improve event messages
=> WINC-416: Improve logging and events

.gitmodules, build/Dockerfile, build/Dockerfile.ci, cmd/manager/main.go, docs/HACKING.md, pkg/controller/wellknownlocations/wellknownlocations.go, pkg/controller/windowsmachine/windows/windows.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/network_test.go, test/e2e/windows_exporter_test.go
This change was made to transfer the windows_exporter executable to the Windows VM and run as a Windows service, exposing node-specific collected metrics at an endpoint reachable from within the cluster.
=> WINC-473: [wmco] run windows_exporter as a Windows service

README.md, docs/TROUBLESHOOTING.md
- Add a troubleshooting guide that describes access a Windows node and collect various log files
- Update the README.md with a strong recommendation to use the same  private key used to create the cluster in the cloud-private-key secret
=> [docs] Add troubleshooting guide

pkg/controller/windowsmachine/windows/windows.go
Use the command "sc.exe qe" and the error code "1060" as hints to not log the error. We are doing this as it was spamming the log with no informational benefit.
=> WINC-547: [wmco] Don't log when a service is not found

pkg/controller/windowsmachine/windows/windows.go
Use the command "sc.exe qe" and the error code "1060" as hints to not log the error. We are doing this as it was spamming the log with no informational benefit.
(cherry picked from commit e5b96f3991d81364748f884a820c2e70ab44f84f)
=> WINC-547: [community-4.6][wmco] Don't log when a service is not found

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.ci, go.mod, hack/lint-gofmt.sh
=> WINC-460: Update to Go 1.15

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR adds icon and  description in WMCO CSV for WMCO operator release-4.6.
=> [release-4.6] Add icon and description in WMCO CSV

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.ci, go.mod, hack/lint-gofmt.sh
This PR:
* Updates to building with go1.15
* Updates submodules to tips of release-4.6 branches
=> [community-4.6] Use go1.15 and update submodules

docs/TROUBLESHOOTING.md
=> [community-4.6] docs: Extend section on how to collect WinEvent logs

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This commit directs customers to use the Red Hat Customer Portal instead
of bugzilla to open issues with the operator.
=> [docs] Update support details in CSV 

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This commit directs customers to use the Red Hat Customer Portal instead
of bugzilla to open issues with the operator.
(cherry picked from commit 8990951a0f48d43804750303da325f47de17a086)
=> [release-4.6][docs] Update support details in CSV

docs/TROUBLESHOOTING.md
Backport of https://github.com/openshift/windows-machine-config-operator/pull/207
=> [release-4.6] docs: Extend section on how to collect WinEvent logs

README.md, docs/machineset-aws.md
This commit ensures that we recommend in our docs the expected
kernel version to mitigate any issues while running Windows
workloads. The expected kernel version is 10.0.17763.1457
or earlier.
=> [docs] Update README with expected Kernel Version

docs/TROUBLESHOOTING.md, hack/packet_trace.sh
Captures .etl traces which can be converted into a .pcapng file, to be
consumed by either Wireshark or other programs.
=> [hack] Add script to collect Windows network trace

README.md, cmd/manager/main.go, cmd/manager/main_test.go, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, docs/machineset-azure.md, docs/powershell.ps1, docs/unattend.xml, docs/vsphere-prerequisites.md, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/controller/controller.go, pkg/controller/secret/secret_controller.go, pkg/controller/windowsmachine/nodeconfig/network.go, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, pkg/controller/windowsmachine/windows/windows.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/network_test.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/vsphere/vsphere.go
Initial set of changes supporting WMCO on vSphere
=> WINC-499: vSphere support

CONTRIBUTION.md
Add a section describing the format of the PR and how it affects Jira and Bugzilla
=> [docs] Add PR format to CONTRIBUTION.md

OWNERS
(cherry picked from commit 3e16a5ec5dfdbf1cf045daecdca0e5260ec4bebd)
=> [release-4.6] Add sebsoto as an approver

go.mod, pkg/cluster/config.go, pkg/cluster/config_test.go, vendor/modules.txt
=> WINC-565: [community-4.7][wmco] Relax k8s version strict dependency

cmd/manager/main.go, cmd/manager/main_test.go, go.mod, vendor/golang.org/x/mod/LICENSE, vendor/golang.org/x/mod/PATENTS, vendor/golang.org/x/mod/semver/semver.go, vendor/modules.txt
=> WINC-565: [community-4.6][wmco] Relax k8s version strict dependency 

hack/run-ci-e2e-test.sh
case there is an transient issue when deploying the WMCO.
=> WINC-574: [ci] Introduce retries for WMCO deployment

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the operator capability in the WMCO CSV to Seamless upgrades indicating it supports upgrades now.
=> [deploy] Update operator capability to 'Seamless upgrades'

hack/run-ci-e2e-test.sh
case there is an transient issue when deploying the WMCO. Recently we
have been seeing an issue with Azure clusters going through an etcd
leader election soon after install. This change is being made as a
reaction to that, so that we retry WMCO deployment instead of having to
retry the entire test, including cluster provision.
(cherry picked from commit 1f840a658ff62e5252245d825ae8c5b14ec9e00d)
=> WINC-574: [community-4.6]][ci] Introduce retries for WMCO deployment

hack/run-ci-e2e-test.sh
case there is an transient issue when deploying the WMCO. Recently we
have been seeing an issue with Azure clusters going through an etcd
leader election soon after install. This change is being made as a
reaction to that, so that we retry WMCO deployment instead of having to
retry the entire test, including cluster provision.
(cherry picked from commit 1f840a658ff62e5252245d825ae8c5b14ec9e00d)
=> WINC-574: [release-4.6][ci] Introduce retries for WMCO deployment

pkg/controller/windowsmachine/metrics/metrics.go
This commit removes the constant used as name for  metrics resources.
The name for metrics resources is set by 'metrics' package of operator-sdk
and is equivalent to the name of the metrics service. The changes include
retrieving the name set by the 'metrics' package and using it for accessing
the resources.
=> [wmco] Remove constant for metrics resources name 

hack/run-ci-e2e-test.sh
case there is an transient issue when deploying the WMCO. Recently we
have been seeing an issue with Azure clusters going through an etcd
leader election soon after install. This change is being made as a
reaction to that, so that we retry WMCO deployment instead of having to
retry the entire test, including cluster provision.
(cherry picked from commit 1f840a658ff62e5252245d825ae8c5b14ec9e00d)
=> WINC-574: [release-4.7][ci] Introduce retries for WMCO deployment

hack/run-ci-e2e-test.sh
case there is an transient issue when deploying the WMCO. Recently we
have been seeing an issue with Azure clusters going through an etcd
leader election soon after install. This change is being made as a
reaction to that, so that we retry WMCO deployment instead of having to
retry the entire test, including cluster provision.
(cherry picked from commit 1f840a658ff62e5252245d825ae8c5b14ec9e00d)
=> WINC-574: [community-4.7][ci] Introduce retries for WMCO deployment

pkg/controller/windowsmachine/metrics/metrics.go
This commit removes the constant used as name for  metrics resources.
The name for metrics resources is set by 'metrics' package of operator-sdk
and is equivalent to the name of the metrics service. The changes include
retrieving the name set by the 'metrics' package and using it for accessing
the resources.
(cherry picked from commit 831e42db1a24264fd28bb6f38e780e576ea3d6ce)
=> [community-4.6][wmco] Remove constant for metrics resources name

docs/vsphere-prerequisites.md
=> small updates to vsphere readme

test/e2e/providers/vsphere/vsphere.go
Instead get it from the env var $LEASED_RESOURCE for CI and assume "dev-segment" otherwise.
=> [test] Don't assume vSphere network name

.gitmodules
Updates the windows-machine-config-bootstrapper submodule to commit openshift/windows-machine-config-bootstrapper@86d9c3e
Commands run:
```shell
git config -f .gitmodules submodule.windows-machine-config-bootstrapper.branch release-4.8
cd windows-machine-config-bootstrapper
git checkout release-4.8
git pull
```
=> WINC-555: [submodule][wmcb] Update to 86d9c3e

.gitmodules
Updates the windows-machine-config-bootstrapper submodule to commit openshift/windows-machine-config-bootstrapper@cf60cd7
Commands run:
```shell
git config -f .gitmodules submodule.windows-machine-config-bootstrapper.branch community-4.7
cd windows-machine-config-bootstrapper
git checkout community-4.7
git pull
```
=> WINC-555: [community-4.7][submodule][wmcb] Update to cf60cd7

hack/run-ci-e2e-test.sh
This reduces the noise in the main CI test output.
=> [test] Redirect WMCO log output to a file

controllers/windowsmachine_controller.go
This commit makes it so that the isAllowedDeletion() function properly
returns an error in the case that the function is unable to tell if the
Machine can be deleted or not.
=> [wmco] Handle errors in Machine deletion check

.gitmodules, build/Dockerfile, build/Dockerfile.ci, hack/lint-gofmt.sh
- [submodule][kubernetes] Rename to kubelet
- [submodule][kube-proxy] Build from SDN branch
=> WINC-593: Build kube-proxy from the SDN branch

docs/setup-hybrid-OVNKubernetes-cluster.md
I've updated this to match the configuration that's in the latest installation procedure for OCP
=> Simplify installation manifest

controllers/windowsmachine_controller.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
Changes that need to be made in order for Bring Your Own Host (BYOH) to be possible.
=> Generalize nodeconfig to work with VMs not sourced from Machines

docs/vsphere-prerequisites.md
Update reference link for [hybrid OVN Kubernetes networking]
=> [docs] fix reference link

test/e2e/metrics_test.go
This commit adds a test to make sure CPU and memory usage statistics are
available for Windows nodes.
=> [test] Ensure node resource usage is retrievable

.gitmodules
- [submodule][ovn-kubernetes] Update to openshift/ovn-kubernetes@157c0a7
- [submodule][windows-machine-config-bootstrapper] Update to openshift/windows-machine-config-bootstrapper@0d5d2f4
-  [submodule][containernetworking-plugins] Update to openshift/containernetworking-plugins@c35c6e7
- [submodule][kubelet] Update to openshift/kubernetes@a678cfd
=> [submodules] Update branch to release-4.9

controllers/configmap_controller.go
Rename it to ensureInstanceIsConfigured as that terminology is more
correct here.
=> [wmco] Rename ensureNodeIsConfigured()

pkg/nodeconfig/network.go, pkg/nodeconfig/nodeconfig.go, pkg/nodeconfig/payload/payload.go, pkg/windows/windows.go
This commit fixes minor formatting issues and typos.
=> [wmco] Fix typos and formatting

controllers/configmap_controller.go, controllers/configmap_controller_test.go
Reverts openshift/windows-machine-config-operator#523
=> Revert "[community-4.8] WINC-612: [wmco] Introduce isValidConfigMap()"

controllers/configmap_controller.go
This commit refactors the reconcileNodes() function present in the
ConfigMap controller, by breaking out instance configuration logic into
a separate ensureInstancesAreUpToDate() function.
=> [wmco] Further modularize BYOH instance configuration

CONTRIBUTION.md
Add a missing `<BLANK LINE>` in the commit message example for
the `<footer>` section in the CONTRIBUTION.md documentation
=> [docs] Update contribution documentation

.gitmodules
Update to https://github.com/openshift/kubernetes/commit/a85801d05770a8903f6f2cdd117fb783a51a68f3
=> [submodule][kube-proxy] Update to a85801d0577

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, pkg/csr/csr.go, pkg/csr/csr_test.go, pkg/instance/instance.go, pkg/instance/instance_test.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, pkg/wiparser/wiparser.go, pkg/wiparser/wiparser_test.go
- Rename instances pkg to instance
- Rename InstanceInfo to Info
- Rename NewInstanceInfo to NewInfo
This results in more natural names for the types and functions in their call sites.
=> [wmco] Remove stuttering from instances pkg

pkg/windows/connectivity.go
Remove an unnecessary if statement.
=> [windows] Improve connectivity.run()

pkg/windows/windows.go
This PR introduces ensuring HNS Networks are removed by waiting and verifying the output of Get-HNSNetwork does not contain the removed network. If the network is not removed, it will retry the removal of network until it is removed.
=> [wmco] Ensure HNS networks are removed

hack/run-ci-e2e-test.sh
Update run-ci-e2e-test.sh usage message including the
supported options.
=> [hack] Update run-ci-e2e-test.sh usage message

config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Update the k8s version to v1.22 in the CSV
Follow-up to https://github.com/openshift/windows-machine-config-operator/pull/581/commits/6698f0296c05ca2e534c1f72265945c0ffbe98a0
=> [config] Update the k8s version in the CSV

pkg/windows/windows.go
Renames the function and related variables in order to be accurate to
what the function is actually doing. The function is asking for a new
HNS endpoint to be created and attached to the HNS network created by
hybrid overlay.
=> [windows] Rename getSourceVIP()

docs/wmco-prerequisites.md
- Add support for platform:none (BYOH)
- Add support for Windows SAC 20H2
- Correct the LTSC version to 2019 as 1809 also refers to a SAC version
=> [docs][pre-reqs] Update providers and OS versions

.gitmodules
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/781
=> [community-4.7] Replace git with https URL in .gitmodules

.gitmodules
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/781
=> [release-4.7] Replace git with https URL in .gitmodules

.gitmodules
[submodule][windows-machine-config-bootstrapper] Update to openshift/windows-machine-config-bootstrapper@827c30a
[submodule][ovn-kubernetes] Update to openshift/ovn-kubernetes@818dac4
[submodule][containernetworking-plugins] Update to openshift/containernetworking-plugins@44a4913
[submodule][kubelet] Update to openshift/kubernetes@1b2affc
[submodule][kube-proxy] Update to openshift/kubernetes@ff80f21
=> [submodules] Update branch to release-4.10

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
Ran `make bundle` after updating operator version in Makefile.
=> [release-4.9] Prep for 4.0.1 release

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This PR all the necessary files to update the WMCO version to 3.1.1
Ran command 'make update'
=> [release-4.8] Prep for 3.1.1 release

test/e2e/network_test.go
Now that powershell:lts-nanoserver-20h2 image has been published, use that instead of the servercore:2009 image. This also simplifies the code as we no longer have to choose between `powershell.exe` and `pwsh.exe`.
=> [e2e] Use powershell:lts-nanoserver-20h2 image

pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/crypto/crypto_test.go
Fix formatting issue in comments without leading space and
re-arrange import order in file.
=> [wmco] Re-arrange import and add missing spaces

docs/HACKING.md
- Fix spacing
- Fix capitalization and short form usage
- Fix incorrect link to Git submodule section
=> [docs] Minor fixes to HACKING.md

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, main.go, pkg/nodeconfig/payload/payload.go, pkg/windows/windows.go
- [submodule][containernetworking-plugins] Update to 693f1c1 
- [wmco] React to upstream CNI changes
=> [submodule][containernetworking-plugins] Update to 693f1c1

go.mod, go.sum, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/network_test.go, vendor/github.com/apparentlymart/go-cidr/LICENSE, vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go, vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go, vendor/modules.txt
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/777
=> [community-4.9] OCPBUGSM-36947: Get and pass Cluster DNS to wmcb.exe

.gitmodules
[submodule][containerd] Update to openshift/containerd@ 3ccd43c8f
[submodule][ovn-kubernetes] Update to openshift/ovn-kubernetes@ 822ae6d6 
[submodule][kubelet] Update to openshift/kubernetes@ 6859754c3ff
[submodule][hcsshim] Update to openshift/hcsshim@ 77c02704
[submodule][cloud-provider-azure] Update to openshift/cloud-provider-azure@ 07f13351
[submodule][windows-machine-config-bootstrapper] Update to openshift/windows-machine-config-bootstrapper@ 0d5c2b4
=> [master][submodule] update 01 07 submodule update 01 10

.gitmodules, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/lint-gofmt.sh
This is a manual cherry-pick of #850 and revert of 3e2f466
=> [community-4.9] Revert containerd addition

go.mod, go.sum, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/network_test.go, vendor/github.com/apparentlymart/go-cidr/LICENSE, vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go, vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go, vendor/modules.txt
This is a manual cherry-pick of #777 due to vendor conflicts.
=> [community 4.8] OCPBUGSM-36947: Get and pass Cluster DNS to wmcb.exe

go.mod, go.sum, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/network_test.go, vendor/github.com/apparentlymart/go-cidr/LICENSE, vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go, vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go, vendor/modules.txt
This is a manual cherry-pick of #777
=> [release-4.9] Bug 2020350: Get and pass Cluster DNS to wmcb.exe

OWNERS
- Remove @aravindhp from OWNERS
- Add @selansen to reviewers and approvers
- Add @aravindhp and @ravisantoshgudimetla to emeritus_approvers
=> [OWNERS] Remove @aravindhp and add @selansen

.gitmodules
Ran command:
./hack/update_submodules.sh master
[submodule][windows-machine-config-bootstrapper] Update to 693f1c1
[submodule][containernetworking-plugins] Update to 693f1c1 
[submodule][kubelet] Update to f14faf24
=> [master][submodule] update 02/15

go.mod, go.sum, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/network_test.go, vendor/github.com/apparentlymart/go-cidr/LICENSE, vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go, vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go, vendor/modules.txt
This is a manual cherry-pick of #777 due to vendor conflicts.
=> [release-4.8] Bug 2030943: Get and pass Cluster DNS to wmcb.exe

controllers/certificatesigningrequests_controller.go, pkg/csr/csr.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
Manual cherry-pick of #894 for fixing vendoring.
=> [community-4.9] [csr_controller] RetryOnConflict in CSR approvals

controllers/certificatesigningrequests_controller.go, pkg/csr/csr.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
Manual backport of #894 to fix vendoring.
=> [release-4.9] [csr_controller] RetryOnConflict in CSR approvals

docs/wmco-prerequisites.md
This PR documents the dual NIC limitation. In addition, fixes incorrectly formatted tables.
=> WINC-749: Document dual NIC limitation

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This commit adds a subscription annotation to our CSV to prepare for the new
gating validation being added by CVP.
(cherry picked from commit 18390d0c700e3e2da7b647aeb29a7d2d4c01ee3f)
=> [release-4.7] WINC-797: Add subscription annotation to CSV

.gitmodules
Update to https://github.com/openshift/containernetworking-plugins/commit/9061d30f600f4fa36f179ffe26d17b4485e076e3
=> [community-4.10] [submodule][containernetworking-plugins] Update to 9061d30f

README.md, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, docs/byoh-instance-pre-requisites.md, docs/vsphere-golden-image.md, main.go, pkg/csr/csr.go, pkg/internal/cni-conf-template.json, pkg/internal/containerd_conf.toml, pkg/nodeconfig/network.go, pkg/nodeconfig/network_test.go, pkg/nodeconfig/nodeconfig.go, pkg/nodeconfig/payload/payload.go, pkg/windows/windows.go, test/e2e/delete_test.go, test/e2e/logs_test.go
This is a manual backport of #891 and includes the WMCB submodule update pointing to community-4.10.
=> [community-4.10] WINC-695: Configure containerd service and start it

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml
This commit aims to address [WINC-803](https://issues.redhat.com//browse/WINC-803) issue. We need to update
OpenShift Container Platform for Windows Containers subscription
as subscription info to be in sync with release and support docs.
(cherry picked from commit b44a63f8931897f386cb6b6528cd477ed61a8b2e)
=> [release-4.9]  [bundle]  Update correct WMCO subscription info

docs/byoh-instance-pre-requisites.md
Documents limitations for Windows Server versions other than 2022
=> Document BYOH static IP limitation

pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/daemon/winsvc/winsvc.go, pkg/daemon/winsvc/winsvc_test.go
Includes changes to both the unit test code and functionality, improving the way WICD handle service dependencies
=> Better WICD dependency handling

OWNERS
- Remove @selansen from OWNERS
- Add @aravindhp to reviewers and approvers
- Remove @aravindhp from emeritus_approvers
=> [OWNERS] Remove @selansen and add @aravindhp

README.md, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, hack/community/csv/description.md
Documents that DeploymentConfigs are not supported on Windows
=> Document DeploymentConfig limitation

controllers/configmap_controller.go, pkg/windows/windows.go, test/e2e/validation_test.go
This PR adds Windows Exporter to the Windows service ConfigMap, as well as changes required to stop the service when needed.
=> WINC-848: Manage Windows exporter with WICD

README.md, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)
=> [release-4.10][docs] DeploymentConfig limitation

controllers/configmap_controller.go
* Fixes panic
* Refactors EnsureServicesConfigMapExists()
=> Minor ConfigMap controller improvements

hack/machineset.sh
Adds ability to spin up a Windows Server 2022 MachineSet on GCP.
=> WINC-814: Add GCP to machineset.sh

README.md
- Add a section calling out all the products WMCO and Windows nodes don't work with
- Fix formatting in the same section
=> [docs] Add Windows node limitations

README.md, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)
=> [release-4.7][docs] DeploymentConfig limitation

README.md, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)
=> [release-4.9][docs] DeploymentConfig limitation

Makefile, hack/community/csv/description.md, hack/community/generate.sh, hack/community/readme.md
Manual cherry-pick from #1151 
(cherry picked from commit 919a311949cfabfb6b555cd204dda93b91e5dd06)
=> [community-4.10] WINC-823: Test generated community manifests in WMCO e2e

README.md, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)
=> [release-4.8][docs] DeploymentConfig limitation

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/rfe.yml
Unquoted '@' was causing a yaml parsing error.
Additionally the assignees field was explicitly made an array.
=> Fix issue template yaml syntax

build/Dockerfile.ci, hack/run-ci-e2e-test.sh
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1216
=> [release-4.9] WINC-520: Stop downloading oc client and leverage test image binaries

build/Dockerfile.ci, hack/run-ci-e2e-test.sh
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1216
=> [release-4.8] WINC-520: Stop downloading oc client and leverage test image binaries

build/Dockerfile.ci, hack/run-ci-e2e-test.sh
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1216
=> [release-4.10] WINC-520: Stop downloading oc client and leverage test image binaries

pkg/windows/windows.go
This is manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1198
=> [release-4.9] [windows] Increase kubelet verbosity in debug

.gitmodules
Update git submodules to 4.13 branches
=> [master] [submodule] Update git submodules to 4.13 branches

.github/ISSUE_TEMPLATE/merge-blocker.yml
Use `value` instead of `placeholder` so that the text is actually populated in the issue.
=> Fix merge blocker template

README.md
This PR adds WMCO limitation of not supporting a network configuration with trunk port.
Fixes BZ#2072418
=> Bug 2072418: [docs] Add trunk port  to the limitations

Makefile, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This change bumps the operator and OCP version
according to the WMCO 8.0.0 release.
Ran 'make bundle' after changing the Makefile and 'config/' files.
=> WINC-942: [bundle] Prep for 8.0.0 release

.gitmodules
Update to containerd [v1.6.15](https://github.com/openshift/containerd/releases/tag/v1.6.15) and hcsshim [v0.9.6](https://github.com/openshift/hcsshim/releases/tag/v0.9.6)
=> WINC-957: [submodule] Update to containerd v1.6.15 and hcsshim v0.9.6

pkg/daemon/manager/manager.go
This commit waits for the process associated with a service to exit
after stopping a service to ensure that WICD is correctly returning that
cleanup was successful, only after all the services have fully stopped.
If the process does not exit before the timeout period, the process will
be terminated by WICD.
=> OCPBUGS-6611: Wait until processes exit when stopping services

Makefile
Update windows_exporter and containerd submodules to their latest updated downstream commits.
=> WINC-925: [master] submodule update 02 10

Makefile
testing ci job for https://issues.redhat.com/browse/SDN-3603
=> WIP: Please ignore

Makefile
[submodule][ovn-kubernetes] Update to 4d17668ef
[submodule][containernetworking-plugins
[submodule][kubelet] Update to 919a59b67b7
[build] Update kubelet version to v1.26.0+919a59b
=> [submodule] update 2/16

Makefile
[submodule][ovn-kubernetes] Update to 3e65a77ce
[submodule][kubelet] Update to f854081c069
[build] Update kubelet version to v1.26.0+f854081
[submodule][containerd] Update to d594a39e7
[build] Update containerd version to v1.6.19-4-gd594a39e7
[submodule][hcsshim] Update to 27bb92f3
[submodule][cloud-provider-azure] Update to c9c5dcc66
=> [master] submodule update 03/01

Makefile
[submodule][hcsshim] Update to 27bb92f3
[submodule][containerd] Update to 37febd202
[build] Update kube-proxy version to v1.24.0+041f707 
[build] Update kubelet version to v1.24.6+deccab3
[submodule][ovn-kubernetes] Update to e21e8eeb1
=> [release-4.11][submodule] submodule update 03/01

Makefile
[submodule][hcsshim] Update to 27bb92f3 
[build] Update containerd version to v1.6.19-4-geab1c5444
[submodule][containerd] Update to eab1c5444 
[submodule][ovn-kubernetes] Update to 5f8cd83cb
=> [release-4.12][submodule] submodule update 03/01

pkg/daemon/controller/controller.go, pkg/windows/service.go, pkg/windows/windows.go, test/e2e/validation_test.go
Ensures that services return to the correct state if tampered with
=> WINC-736: Periodically correct service state

Makefile
- [build] Update kubelet version to v1.23.12+8a6bfe4
- [build] Update kube-proxy version to v1.23.4+c51fc87
=> [release 4.10][submodule] update 03/06

Makefile
- [build] Update kubelet version to v1.22.15+c763d11
- [build] Update kube-proxy version to v1.22.0+0032072
=> [release 4.9][submodule] update 03/09

test/e2e/logs_test.go
Fixes only stdout being captured.
=> [test] Capture stderr on oc adm node-logs failures

CONTRIBUTION.md
reorganizes and gets CONTRIBUTION.md up to date with current practices
=> WINC-959: [docs] updates CONTRIBUTION.md

pkg/windows/windows.go
This PR rearranges the order of WMCO instance deconfiguration operations. It also updates the directory removal operation to delete the ksDir files excluding the WICD service related files. This allows us to retry
reconciliation in case of a deletion failure, resulting in WICD cleanup cmd being called. k8sDir which only contains the WICD files is deleted as the last step in the directory cleanup process with best effort, logging any errors. At this point we don't want to retry reconciliation as the WICD files would have been deleted.
=> OCPBUGS-10572: Fix cleanup failure on WMCO upgrade

Makefile
- [[submodule][ovn-kubernetes] Update to aeac6b26e](https://github.com/openshift/windows-machine-config-operator/commit/eac1fb385a31752ba682b817acc9e43486f686a8)
- [[submodule][containernetworking-plugins] Update to 239bdb6](https://github.com/openshift/windows-machine-config-operator/commit/f63a1ac601cb17504d2d8708bd24beb336162f8f)
- [[submodule][kubelet] Update to 7d98b1aa513](https://github.com/openshift/windows-machine-config-operator/commit/d4643ca18ee3b8d3fa165f7414500888a3f40c27)
- [[build] Update kubelet version to v1.26.2+7d98b1a](https://github.com/openshift/windows-machine-config-operator/commit/993ba323ecb10d94c7213832c9b6f8393aa505eb)
- [[submodule][cloud-provider-azure] Update to ed929dcb5](https://github.com/openshift/windows-machine-config-operator/commit/f1a1943ce5da781f34 …
=> [submodule] update 03/20

Makefile
- [[submodule][ovn-kubernetes] Update to 117c69fcf](https://github.com/openshift/windows-machine-config-operator/commit/8ee50d626e3aa8c48479e28a65d5ad6c37485f86)
- [[submodule][kubelet] Update to 06e8c46c9f0](https://github.com/openshift/windows-machine-config-operator/commit/4bd238b48cf69e79ac758d55ecf29a2b4ea1a669)
- [[build] Update kubelet version to v1.26.2+06e8c46](https://github.com/openshift/windows-machine-config-operator/commit/c7dc431908c85bea18c47bb6c7b2898be604cde9)
- [[submodule][cloud-provider-azure] Update to ce2ddad66](https://github.com/openshift/windows-machine-config-operator/commit/7778221aeafc4fffc533126a8cbc944a27038fe0)
=> [release-4.13] submodule update 03/20

pkg/daemon/controller/controller.go
This commit removes all unecessary klog calls and passes a klog logger into the controller-runtime manager, causing reconcile errors to be logged automatically, instead of having to make extra klog.Error() calls.
=> [wicd] Pass klog to controller-runtime

Makefile
- [[submodule][ovn-kubernetes] Update to 1ec7d41fa](https://github.com/openshift/windows-machine-config-operator/commit/58f5e9217812fa2111f223a1a95d9dc8865cb7db)
- [[submodule][kubelet] Update to eab9cc98fe4](https://github.com/openshift/windows-machine-config-operator/commit/5521d38a97399d2f14d53c0606fa5c9f98e244dd)
- [[build] Update kubelet version to v1.25.7+eab9cc9](https://github.com/openshift/windows-machine-config-operator/commit/83ecf0f6cd0af21060aaca4fe05eb3648cf643bf)
=> [release-4.12] submodule update 03/16

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco
[build] Update Dockerfiles to use rhel-9-release-golang-1.19-openshift-4.13 base image
=> [build] Update Dockerfiles to use rhel-9, openshift-4.13 base image

Makefile
[[submodule][ovn-kubernetes] Update to 04fcf6c04](https://github.com/openshift/windows-machine-config-operator/pull/1560/commits/a83dac73f199cedfc46d19ae8bef74143a9faaf1) 
[[submodule][kubelet] Update to 0f238333eaa](https://github.com/openshift/windows-machine-config-operator/pull/1560/commits/40cb001c767f4b8d495738c10481db934a0c0196) 
[[build] Update kubelet version to v1.26.2+0f23833](https://github.com/openshift/windows-machine-config-operator/pull/1560/commits/397ca02da1c4f903aabb1a05e8483029e5ceea55) 
[[submodule][kube-proxy] Update to ec42cea68da](https://github.com/openshift/windows-machine-config-operator/pull/1560/commits/ed5d427cdd572a1902fb356ba276a57cce55da3c) 
[[build] Update kube-proxy version to v1.26.0+ec42cea](https://github.com/openshift/windows-machine-config-operator/p …
=> [submodule] update 04/14

Makefile
[[submodule][ovn-kubernetes] Update to d69a62a5a](https://github.com/openshift/windows-machine-config-operator/pull/1561/commits/ce0ec1c9c1bd6e0a311dcb044f257ccf536b77b7) 
[[submodule][kubelet] Update to 27e744f55d2](https://github.com/openshift/windows-machine-config-operator/pull/1561/commits/7f6ba546f8d3ce691a7f8b6d60dd9586659a33c7) 
[[build] Update kubelet version to v1.25.8+27e744f](https://github.com/openshift/windows-machine-config-operator/pull/1561/commits/73bab8b86ea9f63eb27cace3bef372929d1e121f)
=> [release-4.12] submodule update 04/14

Makefile
[[submodule][ovn-kubernetes] Update to 7d28d1649](https://github.com/openshift/windows-machine-config-operator/pull/1563/commits/54acc98ea190128e8a619200dea057d7af4ad187) 
[[submodule][kubelet] Update to ceaf3380064](https://github.com/openshift/windows-machine-config-operator/pull/1563/commits/3d57325f7da5a07a47d6fcf1ce71089c251f46b9) 
[[build] Update kubelet version to v1.24.12+ceaf338](https://github.com/openshift/windows-machine-config-operator/pull/1563/commits/133f3ab100bdc87c47cc050827e5de3fd8be11ff)
=> [release-4.11] submodule update 04/14

.gitmodules, Makefile, pkg/internal/containerd_conf.toml
- Update to openshift/hcsshim@5871d0c
- Update to openshift/containerd@1fbd703
- [build] Update containerd version to v1.7.0
- [internal] Update containerd 1.7 config defaults 
Adding the default configuration generated for review purposes
<details><summary>containerd.exe config default</summary>
<p>
disabled_plugins = []
imports = []
oom_score = 0
plugin_dir = ""
required_plugins = []
root = "C:\\ProgramData\\containerd\\root"
state = "C:\\ProgramData\\containerd\\state"
temp = ""
version = 2
[cgroup]
path = ""
[debug]
address = ""
format = ""
gid = 0
level = ""
uid = 0
[grpc]
address = "\\\\.\\pipe\\containerd-containerd"
gid = 0
max_recv_message_size = 16777216
max_send_message_size = 16777216
tcp_address = ""
tcp_tls_ca = ""
tcp_tls_cert = ""
tcp_tls_key = ""
uid = 0
[metrics]
address …
=> WINC-1010: Upgrade to containerd 1.7

docs/vsphere_ci/README.md, docs/vsphere_ci/scripts/disable-ipv6.ps1, docs/vsphere_ci/windows-server-2022.pkr.hcl, hack/machineset.sh, test/e2e/providers/vsphere/vsphere.go
- [vpshere_ci] Disable IPv6 on Windows 2022
- [test] Use IPv6 disabled template for Windows 2022
=> [release-4.10] OCPBUGS-11898: Disable IPv6 on Windows 2022

docs/wmco-prerequisites.md
Explain why we are dropping Azure support in WMCO 5.x and lower.
(manually cherry picked from commit 5e754f1)
=> [release-4.10] WINC-1036: Drop Azure support in WMCO 5.x and lower

docs/wmco-prerequisites.md
Explain why we are dropping Azure support in WMCO 5.x and lower.
(manually cherry picked from commit 2697e9a)
=> [release-4.11] WINC-1036: Drop Azure support in WMCO 5.x and lower

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.13] WINC-1020: Update version to 8.0.1

pkg/windows/windows.go, test/e2e/providers/azure/azure.go
- [windows] Install container feature silently 
- [test] Use 2019-datacenter-smalldisk for Azure
Fixes OCPBUGS-13244
=> OCPBUGS-13244: Install container feature silently

go.mod, go.sum, vendor/github.com/go-imports-organizer/goio/README.md, vendor/github.com/go-imports-organizer/goio/main.go, vendor/modules.txt
Updated goio entry in go.mod and ran "go mod tidy && go mod vendor"
=> [vendor] Update goio to v1.3.3

pkg/daemon/controller/controller.go
WICD should not be labeling a Node as fully configured if it does not go into the 'Ready' state. Applying the version annotation communicates that this is a working, configured node.
=> Ensure node becomes ready when configuring

Makefile
[[submodule][ovn-kubernetes] Update to fb1c5655e](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/b02eb553f6af875ed2263164c2af844e6bf5bdd5)
[[submodule][containernetworking-plugins] Update to 6e00b54](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/b7c2436dae4b9aea9b803dd0dcf5ba40a9053be6)
[[submodule][kubelet] Update to cb4b47e5ddf](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/77e3794ca263fdfa039a817ea540655710714dd3)
[[build] Update kubelet version to v1.27.3+cb4b47e](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/2e37abba20b545d82398d49ace7df0e5fd3ccc8c)
[[submodule][kube-proxy] Update to 70821f71879](https://github.com/openshift/windows-machine-config-operator …
=> [submodule] update 06/23

pkg/windows/windows.go
=> [release-4.11] OCPBUGS-15435: Install container feature silently

Makefile
* https://github.com/openshift/ovn-kubernetes/commit/e236fea83d62de8b60b9456770a3e0b525830051
* https://github.com/openshift/kubernetes/commit/af29f64acbf9e6d33cde7f3194cf858f54058d3b
* https://github.com/openshift/cloud-provider-azure/commit/ce1b81a02fd012f3edbd54642284555b89c7e852
=> Submodule update 07/10

README.md, docs/machineset-nutanix.md, docs/nutanix-prerequisites.md, docs/wmco-prerequisites.md
[docs] Document Nutanix machineset sample
* Documents how a user can create a Windows MachineSet in a Nutanix cluster
* Adds pre-requisites to run Windows worker machines in a Nutanix cluster
=> [docs] Document Nutanix machineset sample

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.13] Update version to 8.0.2

Makefile
https://github.com/openshift/ovn-kubernetes/commit/567aee061b529bef8671e0423fda2242fdc6f568
https://github.com/openshift/containernetworking-plugins/commit/1d2b1f63fca16699eedc71fb400afd65eefbfed2 
https://github.com/openshift/kubernetes/commit/4aaeaec06c95e0a1a868695792c256d8f0158075
https://github.com/openshift/cloud-provider-azure/commit/8c622c018714685c1ac2a41e4dc44564fbb1d6ba
=> Submodule update 07/18

Makefile
[[submodule][ovn-kubernetes] Update to 70d15f04e](https://github.com/openshift/windows-machine-config-operator/pull/1703/commits/e983b8fd339cfb31aa01cd845db1401fc87838d1)
[[submodule][promu] Update to 6c8c415](https://github.com/openshift/windows-machine-config-operator/pull/1703/commits/acbd5b04cddc70c489324ab6695ead934e593046)
[[submodule][windows_exporter] Update to 3f5cfea](https://github.com/openshift/windows-machine-config-operator/pull/1703/commits/e5346c34d040397741ee08c39d8aa1dbe7c872d4)
[[submodule][kubelet] Update to 1485cc94772](https://github.com/openshift/windows-machine-config-operator/pull/1703/commits/b745d679300a985d9fa0379a01ce5a4f47e77ae9)
[[build] Update kubelet version to v1.25.11+1485cc9](https://github.com/openshift/windows-machine-config-operator/pull/1703/commits/ …
=> [release-4.12] submodule update 07/25

hack/manifests/csi/vsphere/example-windows-daemonset-pvc-sc.yaml
Introduces sample vsphere CSI manifests to be used by the dev and QE team.
=> [hack] Introduce vsphere CSI manifests

hack/pre-release.sh
Enables gitlab version updates to be performed from the pre-release script.
=> WINC-945: [hack] Automate gitlab version updates

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
=> [release-4.11] WINC-1056: Update version to 6.0.2

Makefile
- [[submodule][ovn-kubernetes] Update to f05d79a60](https://github.com/openshift/windows-machine-config-operator/commit/72d5b84ce8b95aa9b9534181d51c5a6f166275ee) 
- [[submodule][kubelet] Update to e12378702b5](https://github.com/openshift/windows-machine-config-operator/commit/c352264693bfcadf4054742bf07be27e4ca8568b) 
- [[build] Update kubelet version to v1.27.4+e123787](https://github.com/openshift/windows-machine-config-operator/commit/932ace3bb15eeb9143bb580127e5a3d3f8bfd30d) 
- [[submodule][hcsshim] Update to 28cce9cea](https://github.com/openshift/windows-machine-config-operator/commit/3b216e9c4211620b57ff309e43edffeef539b700)
=> Master submodule update 08 07

.gitmodules, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, docs/HACKING.md, goio.yaml, hack/update_submodules.sh, pkg/nodeconfig/payload/payload.go, pkg/services/services.go, pkg/windows/windows.go
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1530
=> [release-4.13] WINC-1025: Enable CSI plugins on Windows nodes

go.mod, go.sum, vendor/github.com/go-imports-organizer/goio/README.md, vendor/github.com/go-imports-organizer/goio/main.go, vendor/modules.txt
Updated goio entry in go.mod and ran "go mod tidy && go mod vendor"
=> [release-4.13] [vendor] Update goio to v1.3.3

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
=> [release-4.11] WINC-1109: Update version to 6.0.3

Makefile
- [[submodule][ovn-kubernetes] Update to 51baafc3f](https://github.com/openshift/windows-machine-config-operator/commit/3aa88cf09c57a20334079e11bf72be47c98994ca) 
- [[submodule][promu] Update to d5383c5](https://github.com/openshift/windows-machine-config-operator/commit/327c32650a9c6fffaa04306b1feafe3705e0d21a) 
- [[submodule][kubelet] Update to 26fdcdf8fc0](https://github.com/openshift/windows-machine-config-operator/commit/ca79f9b9daa471f38580719e8244f3387b02d481) 
- [[build] Update kubelet version to v1.23.17+26fdcdf](https://github.com/openshift/windows-machine-config-operator/commit/5b6a614bb92c38f1d07a8bb5b22e196cc6a08b7d)
=> [release-4.10] submodule update 08-29

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
=> [release-4.12] WINC-1108: Update version to 7.2.0

Makefile
- [[submodule][ovn-kubernetes] Update to 75d07f23e](https://github.com/openshift/windows-machine-config-operator/commit/ba141f3fa61caff0b66182a29496b0f6330a9fd7) 
- [[submodule][containernetworking-plugins] Update to dbf24dea](https://github.com/openshift/windows-machine-config-operator/commit/bf7eedb70dbec1ea6e3f8cd36e52157fbd1a660c) 
- [[submodule][promu] Update to d5383c5](https://github.com/openshift/windows-machine-config-operator/commit/78f2b352183f061304f3ebf3f0c5c082ef910a29) 
- [[submodule][windows_exporter] Update to 3f5cfea](https://github.com/openshift/windows-machine-config-operator/commit/a4f1b502c148bb5e02398937997b49fefa6350e0) 
- [[submodule][kubelet] Update to 0ef5eae6ff8](https://github.com/openshift/windows-machine-config-operator/commit/b41d5c09af56f6b5c04fffb24fa903cb …
=> [release-4.13] submodule update 08/29

Makefile
- [[submodule][ovn-kubernetes] Update to d54b88982](https://github.com/openshift/windows-machine-config-operator/commit/a49c1e3dd2db3f592d14a6b7497780b821fb81c6) 
- [[submodule][containernetworking-plugins] Update to 46338658](https://github.com/openshift/windows-machine-config-operator/commit/23c808fca661ef62f552f9649b973ef5c127a031) 
- [[submodule][promu] Update to d5383c5](https://github.com/openshift/windows-machine-config-operator/commit/6e9950598ae51aba30ba4c1df4bee67622a2befa) 
- [[submodule][kubelet] Update to d424288c25b](https://github.com/openshift/windows-machine-config-operator/commit/457c3d989c9dd46f6687ccb43eea252a9ff4b807) 
- [[build] Update kubelet version to v1.27.4+d424288](https://github.com/openshift/windows-machine-config-operator/commit/0ce4e387e7dd6c7a0ee1198f37570b …
=> submodule update 08-29

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> WINC-1107: [release-4.13] Update version to 8.1.0

hack/run-ci-e2e-test.sh, test/e2e/upgrade_test.go
Includes various fixes/improvements for the new upgrade test
=> WINC-1043: Upgrade test improvements

.gitmodules, Makefile
- [[submodule][kube-proxy] Update to 08ff87bfdab](https://github.com/openshift/windows-machine-config-operator/commit/716beb8bf7d56d997256709a2ae8205d96146e77) 
- [[build] Update kube-proxy version to v1.25.4+08ff87bf](https://github.com/openshift/windows-machine-config-operator/commit/d4504f1a62e88da4ece80c5b8294eb1bec0f005d) 
- [[submodule][ovn-kubernetes] Update to ac22a205a](https://github.com/openshift/windows-machine-config-operator/commit/0987823d2639d11b889b8c6bf28bffff3fb21cd7) 
- [[submodule][promu] Update to d5383c5](https://github.com/openshift/windows-machine-config-operator/commit/6befdea71fd9602f39d0ec2cef639c21f48036e5) 
- [[submodule][kubelet] Update to 26bab08d8df](https://github.com/openshift/windows-machine-config-operator/commit/3a937e66a7549b38cb79a55821766b24ddd88e73 …
=> [release-4.12] submodule update 08/31

.gitmodules, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, goio.yaml, pkg/nodeconfig/payload/payload.go, pkg/services/services.go, pkg/windows/windows.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/smb/smb.go, test/e2e/storage_test.go
Includes backports for csi-proxy, as well as SMB CSI testing, in order to validate the functionality of csi-proxy.
=> [release-4.12] Run csi-proxy on Windows nodes

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/delete_test.go
This is a manual cherry-pick of #1796
=> [release-4.13] OCPBUGS-19084: Restore routes on AWS Windows 2022 nodes

test/e2e/providers/azure/azure.go
Adds azure-file CSI storage to the e2e tests
=> Test Azure CSI storage

test/e2e/providers/azure/azure.go
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1806
=> [release-4.13] Test Azure CSI storage

hack/run-ci-e2e-test.sh, test/e2e/delete_test.go, test/e2e/logs_test.go, test/e2e/main_test.go, test/e2e/providers/azure/azure.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1705
=> [release-4.13] WINC-1043: Test upgrading to CSI storage, from in-tree drivers

Makefile
[submodule][ovn-kubernetes] Update to 0dbe16bbc 
[submodule][containerd] Update to 38d6e91c9 
[build] Update containerd version to v1.6.24-7-g38d6e91c9
=> [release-4.11] submodule update 09 27

Makefile
[submodule][ovn-kubernetes] Update to f2f537e24
[submodule][kubelet] Update to 52589e6ce26 
[build] Update kubelet version to v1.26.9+52589e6 
[submodule][containerd] Update to 6bbc7a691
[build] Update containerd version to v1.6.24-8-g6bbc7a691
=> [release-4.13] submodule update 09 27

Makefile
[submodule][ovn-kubernetes] Update to 87440f4f2 
[submodule][containerd] Update to b93c35c9c 
[build] Update containerd version to v1.6.24-7-gb93c35c9c
[submodule][csi-proxy] Update to 0211feaf25c
=> [release-4.12] submodule update 09 27

Makefile
- [[submodule][ovn-kubernetes] Update to d0925e2b8](https://github.com/openshift/windows-machine-config-operator/commit/fd06601659fc254b45ed355d1268d5e001efb2e2) 
- [[submodule][kubelet] Update to 07c0911cf67](https://github.com/openshift/windows-machine-config-operator/commit/01d9051fa7d4592ffe423ae6822c965e907fbd30) 
- [[build] Update kubelet version to v1.26.9+07c0911](https://github.com/openshift/windows-machine-config-operator/commit/fc5c37af21dc991d7d24cbb07a64e2e75507d38b)
=> [release-4.13] submodule update 10/04

test/e2e/create_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1832
=> [release-4.12] [e2e] Wait for deleted machines in Azure 

pkg/daemon/cleanup/cleanup.go, pkg/daemon/cleanup/cleanup_test.go, test/e2e/delete_test.go
Manual cherry-pick of #1654. Auto-cherry pick is missing time package which was removed in #1811
=> [release-4.12] OCPBUGS-20139,OCPBUGS-20140: Use latest and version CM for cleanup

Makefile
Ran:
```
./hack/update_submodules.sh release-4.14
```
=> [release-4.14] submodule update 10 09

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> WINC-1153: [release-4.13] Update version to 8.1.1

pkg/csr/csr.go
This commit ensures valid and err are being handled appropriately. The logic was mistakenly changed in https://github.com/openshift/windows-machine-config-operator/commit/8b7275ab24d74a55463aa0f090cfec39dc358f42
=> OCPBUGS-22824: Fix error handling for Approve()

Makefile
[[submodule][ovn-kubernetes] Update to dd3c7ed8c](https://github.com/openshift/windows-machine-config-operator/commit/fe6e5371d6598c04d77badf767e49bc5b4307159)
[[submodule][kubelet] Update to bcb9a60b6dd](https://github.com/openshift/windows-machine-config-operator/commit/c0166569bb40de9dbc9a242640fe7da5e61892a4)
[[build] Update kubelet version to v1.25.14+bcb9a60](https://github.com/openshift/windows-machine-config-operator/commit/742153e6e530369b1067dc35ce032898a92e4990)
=> [release-4.12] submodule update 11 06

Makefile
[[submodule][ovn-kubernetes] Update to 2e60df220](https://github.com/openshift/windows-machine-config-operator/commit/8f8e88b7d599e0d88867713e48a9086d626b30d6)
[[submodule][kubelet] Update to 9a3367c89a7](https://github.com/openshift/windows-machine-config-operator/commit/5126100a67e0f6b12ca6e47e8ab5c318d3ce8cd3)
[[build] Update kubelet version to v1.24.16+9a3367c](https://github.com/openshift/windows-machine-config-operator/commit/ea1f523070613c98c83649722b4d5f26a7bcf7b5)
=> [release-4.11] submodule update 11 07

Makefile
[[submodule][ovn-kubernetes] Update to 814535a6d](https://github.com/openshift/windows-machine-config-operator/commit/af35dd1959b71945a47eea6b8c5f30af4d0d1676)
[[submodule][containernetworking-plugins] Update to 8f26066e](https://github.com/openshift/windows-machine-config-operator/commit/521658e7433603ba2c37ad40241b9c14dd909704)
[[submodule][kubelet] Update to 4cbdd29250f](https://github.com/openshift/windows-machine-config-operator/commit/31644f61f30d8bd2616ded3e8c40818f9567f128)
[[build] Update kubelet version to v1.28.3+4cbdd29](https://github.com/openshift/windows-machine-config-operator/commit/fbf9c2b994fb050ebe81b1ac8631fe39adba4ab0)
=> Master submodule update 11 07

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.14] Update version to 9.0.1

test/e2e/metrics_test.go
This change replaces the API call to fetch the service account token from the automatically generated secret with a TokenRequest.
As per official docs automatically generated secrets for should be avoided as they might be removed in a future OpenShift Container Platform release.
See https://docs.openshift.com/container-platform/4.14/authentication/using-service-accounts-in-applications.html#auto-generated-sa-token-secrets_using-service-accounts
=> Stop using automatically generated service account token in e2e test suite

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
Commands run: 
hack/pre-release.sh release-4.12 z
=> [release-4.12] WINC-1177: Update version to 7.2.1

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
=> [release-4.11] WINC-1176: Update version to 6.0.4

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This commit was generated by hack/pre-release.sh release-4.13 z
=> [release-4.13] WINC-1178: Update version to 8.1.2

hack/machineset.sh
Enables the machineSet generation for the Nutanix platform.
=>  Add support for Nutanix in machineset.sh

Makefile
[[submodule][windows-machine-config-bootstrapper] Update to e97b995](https://github.com/openshift/windows-machine-config-operator/commit/e45c9f621802350f53c97646cc73a20107bf25e5) 
[[submodule][containernetworking-plugins] Update to 1addd7c7](https://github.com/openshift/windows-machine-config-operator/commit/5c9005a0388ffe4ec7ae8a2a1200a6e4079041ac) 
[[submodule][windows_exporter] Update to 832186c](https://github.com/openshift/windows-machine-config-operator/commit/47192540d66a62273f122dae39b9e59fb43a340e) 
[[submodule][kubelet] Update to 2e1e13716c7](https://github.com/openshift/windows-machine-config-operator/commit/04ec07e27e622bd97a50a8c552c7edd533b131b3) 
[[build] Update kubelet version to v1.24.16+2e1e137](https://github.com/openshift/windows-machine-config-operator/commit/283dacec6 …
=> [release-4.11] submodule update 01/02

cmd/operator/main.go, docs/byoh-instance-pre-requisites.md, docs/vsphere-golden-image.md, docs/vsphere_ci/scripts/install-firewall-rules.ps1, pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go, pkg/secrets/secrets.go, pkg/services/services.go, pkg/windows/windows.go, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
Changes how kube-proxy is ran in order to use more stable load balancing methods
=> OCPBUGS-26761:  Use DSR load balancing in kube-proxy

hack/errata-check.sh
Adds a column to the errata build report indicating the status of the associated JIRA issue.
=> [hack] Add JIRA status to errata script

hack/errata-check.sh
Adds a new column (Merged) which represents the relative time since the PR was merged.  Also, the Commit Hash is reduced to an abbreviated commit to save space with the additional column.
```
Merge commits in release-4.15 after build windows-machine-config-operator-container-10.15.0-41
Commit   Merged         PR#  PR Title                                                          Jira ID       Fix Version   JIRA Status   Errata Status
======== ============== ==== ================================================================= ============= ============= ============= =============
9581032b 4 hours ago    2024 [release-4.15] OCPBUGS-27503: Use DSR load balancing in kube-prox OCPBUGS-27503 4.15.0        MODIFIED      Not Attached
971f3ede 6 hours ago    2030 [release-4.15] [test] Open SMB …
```
=> [hack] Add relative PR merge times to errata script

cmd/operator/main.go, pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go, pkg/windows/windows.go
This reverts commit 4edb6c5020b41145f0ad98b71a5d44c054dcd41d.
=> Revert "Change sourceVIP used for kube-proxy"

Makefile, go.mod, go.sum, vendor/github.com/go-openapi/swag/BENCHMARK.md, vendor/github.com/go-openapi/swag/initialism_index.go, vendor/github.com/go-openapi/swag/name_lexem.go, vendor/github.com/go-openapi/swag/split.go, vendor/github.com/go-openapi/swag/string_bytes.go, vendor/github.com/go-openapi/swag/util.go, vendor/modules.txt
Ran:
./hack/update_submodules.sh release-4.12
=> [release-4.12] submodule update 01 29

docs/byoh-instance-pre-requisites.md, docs/vsphere-golden-image.md, docs/vsphere_ci/scripts/install-firewall-rules.ps1, pkg/secrets/secrets.go, pkg/services/services.go, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2024
=> [release-4.14] OCPBUGS-28226: Use DSR load balancing in kube-proxy

go.mod, go.sum, vendor/modules.txt
Ran:
./hack/update_submodules.sh release-4.12
=> [release-4.12] submodule update 02 19

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.15] WINC-1113: Introduce feature annotations to CSV

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.14] WINC-1113: Introduce feature annotations to CSV

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
=> WINC-1113: Introduce feature annotations to CSV

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.13] WINC-1113: Introduce feature annotations to CSV

go.mod, go.sum, vendor/github.com/emicklei/go-restful/v3/CHANGES.md, vendor/modules.txt
=> [release-4.12] submodule update 02 26

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.15] WINC-1214: Update version to 10.15.2

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> WINC-1218: [release-4.14] Update version to 9.0.2

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.13] Update version to 8.1.3

hack/errata-check.sh
When using the errata script, use a locally saved personal access token to authenticate with JIRA, if it is available. This will allow the user to get details on non-public issues, as long as the user has access to them.
=> [hack] Allow authenticating with JIRA

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.12] Update version to 7.2.2

Makefile
Ran:
./hack/update_submodules.sh release-4.12
=> [release-4.12] submodule update 04 08

pkg/daemon/controller/controller.go, pkg/metrics/metrics.go
Reduces noise in WMCO and WICD logs
=> WINC-1150: Reduce unecessary log messages

Makefile
Ran:
./hack/update_submodules.sh release-4.13
=> [release-4.13] submodule update 05 13

Makefile
Ran:
./hack/update_submodules.sh release-4.14
=> [release-4.14] submodule update 05 13

Makefile
Ran:
```
./hack/update_submodules.sh release-4.15
```
=> [release-4.15] submodule update 05 13

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, build/bundle-konflux.Dockerfile
Changes default image to the WMCO controller image, as required by konflux. Adds seperate bundle Dockerfile for konflux builds.
=> WINC-1292: Set up konflux bundle builds

.tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml, .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-16-push.yaml, build/Dockerfile.konflux, build/bundle-konflux.Dockerfile
Adding configuration files to each release branch as instructed by https://konflux-ci.dev/docs/advanced-how-tos/managing-multiple-versions/
=> [release-4.16] WINC-1309: Add konflux configuration files

Makefile, hack/run-ci-e2e-test.sh, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2218
=> [release-4.15] WINC-1310: Remove certain tests in old upgrade suite

Makefile, hack/run-ci-e2e-test.sh, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2251
=> [release-4.12] WINC-1310: Remove certain tests in old upgrade suite

Makefile, hack/run-ci-e2e-test.sh, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2249
=> [release-4.14] WINC-1310: Remove certain tests in old upgrade suite

pkg/nodeconfig/nodeconfig.go
This is a behavior change which comes as a result of inconsistencies across OCP platforms and versions. Previously WMCO would check if the cluster created a SA token secret for the WICD SA, and if it exists would use the cluster created secret, else it would create its own secret.
We are finding that on upgrades from 4.15 to 4.16 the secret was missing on 4.15, but then created by an entity in the cluster on 4.16. This is throwing off WMCO's logic to get the secret as there will be multiple SA token secrets, one created by WMCO in 4.15, and an additional one when the 4.16 upgrade occurs.
This commit remedies this issue by having WMCO only use the secret it creates, ignoring any other service account token secrets in the WMCO namespace.
=> OCPBUGS-29253, WINC-1172: Always use created WICD SA token

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.16] Update version to 10.16.1

Makefile
[[submodule][ovn-kubernetes] Update to 4748eb619](https://github.com/openshift/windows-machine-config-operator/commit/0a85d6b08b493f955937d54dad76c52c079b8677)
[[submodule][kubelet] Update to e0953cc62b5](https://github.com/openshift/windows-machine-config-operator/commit/f22c30187352201388cf3b085f95657913b2cee5)
[[build] Update kubelet version to v1.26.15+e0953cc](https://github.com/openshift/windows-machine-config-operator/commit/297dd5c60a9d697708690700d4f5a8907974181d)
=> [release-4.13]  OCPBUGS-37280: submodule update 08 12

Makefile
[[submodule][ovn-kubernetes] Update to aa1ed5138](https://github.com/openshift/windows-machine-config-operator/commit/19ec742f78f8ccfcdbc414655a13fd43637ad0f5)
[[submodule][kubelet] Update to e82605653d2](https://github.com/openshift/windows-machine-config-operator/commit/1d8f3617dc4af817d7b527ba8bff8d15d8ae295f)
[[build] Update kubelet version to v1.27.16+e826056](https://github.com/openshift/windows-machine-config-operator/commit/593ed094b0f05ae8e0633d61ad71ed23f8d44bc6)
[[submodule][cloud-provider-azure] Update to d9800e1ed](https://github.com/openshift/windows-machine-config-operator/commit/48dc20a0a8a86448027f9812472c394c8998d656)
=> [release-4.14] submodule update 08 12

Makefile
Ran:
```
hack/update_submodules.sh release-4.12
```
=> [release-4.12] submodule update 08 13

Makefile
Ran:
./hack/update_submodules.sh release-4.14
=> [release-4.14] submodule update 08 20

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.16] WINC-1325: Update version to 10.16.2

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.15] WINC-1297: Update version to 10.15.4

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.14] WINC-1300: Update version to 9.0.4

README.md
This PR proposes the steps to support  EUS-to-EUS upgrade with Windows nodes.
=> WINC-1315: Document steps for EUS-to-EUS upgrade

pkg/daemon/cleanup/cleanup.go, pkg/daemon/cleanup/cleanup_test.go
The best effort cleanup of WICD is expanded to look at service descriptions
to cleanup all services that WICD started, even if they are not in the curren
iteration of the Windows services ConfigMap. This also prevents a user from
being able to sneak in services into the CM that WICD would never cleanup
since all services started through WICD/windows-services CM will have the
"OpenShift managed" description.
=> OCPBUGS-16711, WINC-853: WICD best effort cleans up removes all managed services

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.17] Update version to 10.17.1

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.12] Update version to 7.2.3

.tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml, .tekton/windows-machine-config-operator-release-4-17-push.yaml, build/bundle-konflux.Dockerfile
In order to pass EnterpriseContractPolicy
=> [release-4.17] Adjust konflux builds

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, .tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml, build/Dockerfile.konflux, build/bundle-konflux.Dockerfile
Makes changes to allow pipeline to pass the required EnterpriseContract policy
=> Update konflux build pipeline

.tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml, .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-18-push.yaml, build/Dockerfile.konflux, build/bundle-konflux.Dockerfile
Makes changes to allow pipeline to pass the required EnterpriseContract policy
cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2597
=> [release-4.18] Update konflux build pipeline

build/bundle-konflux.Dockerfile
Image was using tag + digest, which is invalid.
Additionally, updated digest to latest build
=> [build] Fix bundle image reference

.tekton/windows-machine-config-operator-master-pull-request.yaml
Change filename that was missed in e41ed3da5df6be532fcca365adb6a7b73bba459a
=> [build] Fix missed filename change

go.mod, go.sum, vendor/github.com/evanphx/json-patch/v5/merge.go, vendor/github.com/evanphx/json-patch/v5/patch.go, vendor/github.com/spf13/pflag/.editorconfig, vendor/github.com/spf13/pflag/.golangci.yaml, vendor/modules.txt
=> [release-4.17] submodule update 02 03

.tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml, Containerfile
Manual cherry-picks from master branch
=> [release-4.18] Update konflux build definitions

test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go
fixes warnings in the e2e tests
=> WINC-1365: Fix e2e warnings

.gitmodules, .snyk, Containerfile, Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, docs/HACKING.md, hack/lint-gofmt.sh, hack/update_submodules.sh
Cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2729
=> [release-4.18] WINC-1375: Remove kube-proxy submodule

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, .tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml
=> Add shell and unicode sast pipeline tasks

.tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml, .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-18-push.yaml
=> [release 4.18] Add shell and unicode sast pipeline tasks

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml, docs/TROUBLESHOOTING.md, hack/run-ci-e2e-test.sh, test/e2e/validation_test.go
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/2699 and https://github.com/openshift/windows-machine-config-operator/pull/2730
=> OCPBUGS-54313: [release-4.17] Make debugLogging non-default

.tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml, .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-17-push.yaml
=> WINC-1380: [release-4.17] Add shell and unicode sast pipeline tasks

.tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml, .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-16-push.yaml
=> WINC-1380: [release-4.16] Add shell and unicode sast pipeline tasks

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, .tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml
Memory needs to be bumped for all tasks that use SOURCE_ARTIFACT
=> WINC-1383: Increase memory for konflux tasks that OOM

.tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml
=> WINC-1383: Increase build-container task memory

test/e2e/network_test.go
adds ten retries to oc cp to hopefully lessen the frequency of this flake 
```
Error: Received unexpected error:  
oc cp failed with exit code exit status 1 and output: tar: Removing leading '/' from member names  
Dropping out copy after 0 retries  
: error: unexpected EOF  
Test: TestWMCO/network  
```
=> OCPBUGS-52423: adds retries to oc cp

Containerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Backport missing commits from https://github.com/openshift/windows-machine-config-operator/pull/2662
=> [release-4.17] WINC-1351: Enable FIPS compliance

controllers/registry_controller.go
It has been observed that the registry controller can copy containerd configurations to a Windows BYOH instance, even after the Node has started the deletion process.
This commit hardens the reconcile logic to avoid this timing issue.
While this won't 100% fix the issue, this solution avoids introducing a mutex for manipulating a given node. Given the low severity of the issue I believe this does not warrant the complications that a mutex would add.
=> OCPBUGS-55614: Avoid copying containerd registry files to deleted nodes

.tekton/images-mirror-set.yaml, .tekton/windows-machine-config-operator-bundle-release-4.19-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4.19-push.yaml, .tekton/windows-machine-config-operator-release-4.19-pull-request.yaml, .tekton/windows-machine-config-operator-release-4.19-push.yaml
branching day tasks for 4.20 release
=> [release-4.19] branching day tasks for 4.20 release 

Containerfile, Containerfile.bundle, Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.18] Update version to 10.18.2

build/Dockerfile.ci, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, cmd/operator/main.go, config/manager/manager.yaml, docs/TROUBLESHOOTING.md, hack/run-ci-e2e-test.sh, test/e2e/validation_test.go
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/2784
Install jq in Dockerfile.ci
=> [release-4.16] OCPBUGS-55939: Make debugLogging non-default 

Containerfile, Containerfile.bundle, Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml
=> [release-4.16] Update version to 10.16.3
