openshift/windows-machine-config-operator

.gitignore
Add GoLand config directory to .gitignore
=> Update .gitignore for GoLand 

README.md, build/Dockerfile
Update the Dockerfile to collect all the required binaries and create the following directory structure:
```
/payload/
├── cni-plugins
│   ├── flannel.exe
│   ├── host-local.exe
│   ├── win-bridge.exe
│   └── win-overlay.exe
├── hybrid-overlay.exe
├── kube-node
│   ├── kube-proxy.exe
│   └── kubelet.exe
└── wmcb.exe
```
The above binaries are the ones required for the operator to onboard a VM as a node to an OpenShift cluster.
Jira: [WINC-166](https://issues.redhat.com/browse/WINC-166)
=> Update operator Dockerfile with payload

Makefile, build/build.sh, hack/lint-gofmt.sh, hack/run-ci-e2e-test.sh
Add a Makefile with the following targets:
- build
This will be used in CI to ensure there are not compilation failures. We cannot use `operator-sdk build` as that will result in building the operator image which is not supported in the test pods.
- lint
Runs gofmt against the code base. It will be connected to a CI job.
- run-ci-e2e-test
This is a placeholder for running the e2e tests. It will be connected to a CI job.
- clean
Deletes the built operator binary.
=> [build] Add Makefile

build/Dockerfile.ci
CI requires a special Dockerfile for use with OpenShift Builds which is what is used to build the image. This requires building the operator from the PR source without using the operator-sdk.
=> [build] Add Dockerfile for ci

build/Dockerfile, build/Dockerfile.ci
The operator requires golang 1.13 for building. Remove the hack that required us to $HOME/build/ as we are changing build images. Though to be accurate, the issue had nothing to do with the image but with containers/buildah#2189.
=> [build] Use golang 1.13 for builder

build/build.sh
The golang image used for building in CI enforces vendoring by setting "-mod=vendor" in GOFLAGS. Add a workaround that detects that and unsets it.
=> [build] Add workaround for CI enforcing vendoring

build/build.sh
`set -o nounset` results in errors on trying to access a variable which is not set. This is an issue with `GOFLAGS` as it is set in the CI build container and not in other places. Workaround this by using an intermediate variable that is set to an empty string if `GOFLAGS` is not set and use that variable to check for `-mod=vendor`.
=> [build] Account for GOFLAGS not being set

build/Dockerfile.ci
- Place the WMCO code within the build directory
- Copy the binary from the build stage and not the download stage
=> [build] Fix building of WMCO in Dockerfile.ci

Makefile, build/build.sh
"make clean" was broken when $OUTPUT_DIR moved into build/build.sh. This PR fixes the issue by making OUTPUT_DIR a parameter you pass to build.sh.
=> [build] Fix make clean

README.md
Update documentation on e2e testing. This ensures we can run e2e tests locally from our machine
/cc @aravindhp
=> [docs] Add testing guidelines

deploy/crds/wmc.openshift.io_v1alpha1_windowsmachineconfig_cr.yaml, deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml, pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go, pkg/controller/wellknownlocations/wellknownlocations.go
As of now, the e2es are failing as some CRD fields
are made mandatory. This commit relaxes
the restriction and removes certain fields that are
not mandatory anymore
cc @aravindhp @openshift/openshift-team-windows-containers
=> [wmco] Relax CRD field validation

build/Dockerfile
`operator-sdk build` was broken in f46ddec9. This commit fixes the breakage.
Bug: [WINC-311](https://issues.redhat.com/browse/WINC-311)
=> [build] Fix operator-sdk image build

README.md
cc @aravindhp @akhil-rane @openshift/openshift-team-windows-containers
=> Update README with ssh key information

go.mod, pkg/controller/windowsmachineconfig/tracker/tracker.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
The operator needs an internal tracking mechanism for Windows
nodes that it is managing that has some associated meta data.
This meta data will allow the Operator to sync the nodes on
cluster to what is expected as per the WMC CR. This commits
add the tracker configmap which can be used to identify the
nodes that are being added to the cluster.
/cc @openshift/openshift-team-windows-containers @aravindhp
=> [wmco] Create tracker configmap for Windows VMs

build/Dockerfile, build/Dockerfile.ci
Docker has a longstanding bug using globs
in COPY directives (i.e. COPY foo/dir/* /tmp/dir/ ).
If the source files matched by the glob include
subdirectories, these subdirectories are
not present in the destination. While this is not
a problem for WMCO Dockerfiles, we are doing it
just to be on safe side.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1813508
=> Bug 1813508: Update dockerfile to address buildah COPY bug

deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml, pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR updates the WMC CRD to set the minimum value of 'replicas' 
field to 0 by executing 'operator-sdk generate crds' command
It also adds validations for 'replicas' field in the CRD. Following are the
validations that are performed.
- 'replicas' field is a required field and should be present
- 'replicas' field cannot have value less than 0
=> [wmco] Add validation for fields in the CRD

README.md, deploy/olm-catalog/catalogsource.yaml, deploy/olm-catalog/operatorgroup.yaml, deploy/olm-catalog/subscription.yaml, deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml, deploy/olm-catalog/windows-machine-config-operator/0.0.0/wmc.openshift.io_windowsmachineconfigs_crd.yaml, deploy/operator.yaml, deploy/role.yaml, deploy/role_binding.yaml, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
This PR consists of 3 commits which work towards making the WMCO deployable via OLM:
* Change the WNI resource tracking directory used so that the operator can be deployed outside of CI
* Change RBAC permissions so the SA used by the operator has the correct permissions
* Add the operator bundle and olm deployment yamls
=> Make operator deployable via OLM

README.md
Updated Readme to point the correct link for updating shheyPair,
now mentioned in create_test.go file.
=> [docs] Fix link for SshKeyPair in README

test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/main_test.go, test/e2e/validation_test.go
As of now, we're not able to share context across test suites and within test suites. The commit adds
- local context
- global context
The local context should be used within a single test suite where global context should be across test suites.
=> [ci] Refactor tests to have global and local contexts 

cmd/manager/main.go, pkg/controller/windowsmachineconfig/tracker/tracker.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
This PR introduces a fix for the log panic caused due to a log entry with odd number of arguments for the logger. 
BZ: [https://bugzilla.redhat.com/show_bug.cgi?id=1817186](https://bugzilla.redhat.com/show_bug.cgi?id=1817186)
It also introduces changes for formatting the log info and error messages in a structured log format that follows the msg, key, value pair format as recommended by logr. 
This follows guidelines mentioned in :[https://godoc.org/github.com/go-logr/logr](https://godoc.org/github.com/go-logr/logr) and [https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md](https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md)
=> Bug 1817186: [wmco]  Fix log panic and correct formatting of log messages

cmd/manager/main.go, cmd/manager/main_test.go, hack/unit.sh, pkg/controller/wellknownlocations/wellknownlocations.go
This PR introduces a guard that ensures that required files for WMCO exist
before the operator starts. The operator fails when the required files are
absent. Also, the golang 1.13 image used in CI enforces vendoring, unseting it
before running the unit tests.
=> [wmco] Ensure files required by WMCO are present

hack/run-ci-e2e-test.sh, pkg/controller/retry/retry.go, pkg/controller/wellknownlocations/wellknownlocations.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/windows/windows.go, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
- [ci] Normalize retry constants across the code
- Move common retry constants to the main codebase so that they can be shared across the e2e tests
- Normalize and use sane timeouts and waits for resources to be created
- [wmco] hybrid-overlay configuration
- Update hack/run-ci-e2e-test.sh to enable hybrid OVN networking on the cluster
- Add steps to run hybrid-overlay.exe in the Windows VM
- Add a slice of Windows VM handles to the global context to allow for inside VM tests
- Move nodes from test context to the global context as they are needed in multiple tests
- Add e2e tests to check if the result of running the hybrid-overlay.exe is successful
=> [wmco] Hybrid overlay configuration

README.md, build/Dockerfile, build/Dockerfile.ci, cmd/manager/main.go, pkg/controller/wellknownlocations/wellknownlocations.go, pkg/controller/windowsmachineconfig/windows/windows.go, test/e2e/network_test.go
Because of this [commit](openshift/ovn-kubernetes@2563e6b#diff-86eeef0b956d450bd2a787067b7443fdR26) in ovn-kubernetes repo, the hybrid-overlay binary is no longer called hybrid-overlay.exe but it is called hybrid-overlay-node.exe. We've a hardcoding to hybrid-overlay.exe in the following locations:
-   Dockerfile
-   Dockefile.ci
-   wellknownlocations.go
And there are other places where it is mentioned in code comments.The name of this binary needs to be changed for the operator to start working. Otherwise the CI will keep failing.
In addition, [commit](openshift/ovn-kubernetes@fc16768#diff-7374600df6a5d7b56af840179f7ad27fR86) brought in changes related to renaming OVN overlay networks. This commit address that as well.
=> Bug 1823579: [ci] React to hybrid overlay changes upstream

README.md, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
As of now, after the test suite has been run, the
Windows nodes would be deleted as well. This commit
ensures that
- We have a flag which retains the Windows node
created as part of test suite. Please note that
we're skipping the part where the delete
suite is being called in case this flag has been
set.
- We have flag to specify the number of number of
Windows nodes to be created as part of test run
- We won't download operator-sdk if it's already
available in the PATH
Example command to spin up 2 Windows nodes and retain them after test run:
```
hack/run-ci-e2e-test.sh -s -k "openshift-dev" -n 2"
```
=> [ci] Add local dev flags to e2e script

build/Dockerfile, build/Dockerfile.ci
**Problem:** hack/run-ci-e2e-test.sh fails in the following manner as observed when working on https://github.com/openshift/release/pull/8323:
```
failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
Error: failed to build test binary: ...
```
**Solution:** Preemptively create the go cache directory in the image being built by CI.
=> [ci] Fix failure of e2e hack script

pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/create_test.go, test/e2e/validation_test.go
Refactor:
This PR refactors nodeConfig and adds node object to nodeConfig
struct. It also includes validation for windowsVM and node object.
Also, moved WindowsOSLabel to nodeconfig.go
WMCO:
This PR adds a worker label for windows node
and adds e2e test to check worker label on windows node
Also, adds e2e test to check presence of windows taint on windows node
=> Added worker label and windows taint for windows node

cmd/manager/main.go, cmd/manager/main_test.go, deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml, deploy/role.yaml, hack/unit.sh, pkg/clusternetwork/config.go, pkg/clusternetwork/config_test.go
This PR ensures that the cluster has required configurations before starting
the controller. The cluster configuration checks include : 
- checking the K8s version
- checking that cluster uses OVN kubernetes
- checking hybrid overlay is enabled.
[WINC-326](https://issues.redhat.com/browse/WINC-326)
=> [wmco]Add cluster configuration checks

build/Dockerfile, build/Dockerfile.ci
78409f0 incorrectly fixed the permission issue [being seen](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8323/rehearse-8323-pull-ci-openshift-windows-machine-config-operator-master-e2e-operator/7) during the run of hack script in CI when moving to the step-registry. The fix was in the build stage in the Dockerfile instead of the main stage. Now rather than creating the directory we give the user write permission to the "/go" folder in the container image.
=> [ci] Add write permission to the image's go folder

test/e2e/create_test.go, test/e2e/validation_test.go
**Problem**
In cases where the VM creation failed and then the scale down tests are executed, there is potential for waitForTrackerConfigMap() and waitForWindowsNode() to wait until the go test time out is reached instead of the expected 10 minutes.
**Solution**
The reason for the issues is the way we created the duration based on the number of nodes. Correct this to account for the scale down to 0 nodes scenarios.
=> [ci] Fix waits in VM creation failure scenarios

build/Dockerfile.ci
Without explicitly setting the GOCACHE environment variable, it is defaulting to `/.cache` in the CI runs which is causing the following error:
```
"failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
```
as seen in https://github.com/openshift/release/pull/8323 [pj-rehearse job](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8323/rehearse-8323-pull-ci-openshift-windows-machine-config-operator-master-e2e-operator/9)
=> [ci] Explicitly set GOCACHE environment variable

go.mod, go.sum, pkg/controller/windowsmachineconfig/windows/windows.go
**Problem** 
Any vm.Run() call after the hybrid overlay configuration has completed was taking more than 5 minutes to complete. This is causing the tracker validation test to be flaky as its timeout was 10 munutes.
**Solution** 
To mitigate this openshift/windows-machine-config-bootstrapper#182 introduces reinitializing the WinRM client as part of the Reinitialize() call. Reorder the waitForHNSNetworks() call after the Reinitialize() call to take advantage of this. We are adding a 2 minute sleep after the hybrid overlay starts running to allow it complete its work.
This fix has the very useful side effect of making the node preparation time lower.
=> [ci] Fix tracker validation test

pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
This PR includes various commits to clean up the how the operator handles errors both in the creation of the controller, and the creation of nodes.
=> [wmco] Improve error handling

hack/run-ci-e2e-test.sh
Now that we are using the [step registry workflow](openshift/release#8323) for bringing up a hybrid OVN cluster in CI, we can stop patching the network.operator CR to enable hybrid networking.
=> [ci] Remove patching of network.operator CR

Makefile, hack/common.sh, hack/lint-generate-crds.sh, hack/run-ci-e2e-test.sh
This PR makes sure the generated CRDs are in line with the go code.
=> [ci] Ensure WMC CRD is up to date in lint job 

README.md, deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml, deploy/operator.yaml, hack/run-ci-e2e-test.sh, pkg/controller/windowsmachineconfig/nodeconfig/init.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig_test.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
As of now, we're relying on an environment variable for
cluster address. If the operator runs in a container,
we are mounting the cluster address as the secret
to be used within operator. This commit removes
the dependency on the environment variable. We can
now generate the cluster address from apiserver
config.
https://issues.redhat.com/browse/WINC-274
=> [wmco] Generate cluster address from config

deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
This PR ensures that operator runs without having to watch pod resources
The operator is watching pod during reconcile. Updated the controller to
remove watch on pod resources. Updated the rbac rules to remove pod permissions.
[WINC-340](https://issues.redhat.com/browse/WINC-340)
=> Bug 1819227: [wmco] Remove unnecessary watching of Pods

deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml, pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/status_test.go, test/e2e/validation_test.go
[wmco] remove validation for replicas
fixes validation for replicas field as it was being interpreted as
float while validating.
this was because replicas was defined as `int` in place of `int32`
which is causing the `operator-sdk generate crds` to not create a
`format` field in crd. This is a known issue in
operator-sdk 0.17.
Created [ticket](https://issues.redhat.com/browse/WINC-407) to revert this change 
once we bump operator sdk to 0.18 or above 
operator-sdk [issue](https://github.com/operator-framework/operator-sdk/issues/2952) 
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1835166)
=> Bug 1835166: [wmco] fix validation for replicas

hack/run-ci-e2e-test.sh, pkg/controller/windowsmachineconfig/tracker.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/main_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
If the WMCO is restarted, the knowledge of the nodes
created via WMCO is lost. We can construct this information from
the tracker configmap. This PR addresses the following items:
- https://issues.redhat.com/browse/WINC-269
- https://issues.redhat.com/browse/WINC-280
We're addressing WINC-280 as part of this PR as the node can be in unready state
and we're still counting it towards the windowsVM that was created. Only the
nodes that are in ready state should be accounted for when the operator
restarts
=> [wmco] Fix restart

pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/tracker.go, pkg/controller/windowsmachineconfig/windows/windows.go
This commit corrects the format of error.wrap messages from
errors.Wrap(err, fmt.Sprintf(msg)) -> errors.wrapf(err, msg)
This will ensure consistency across the repo and start using
errors.wrap moving forward.
=> [wmco] fix formatting of errors.wrap messages

README.md, build/Dockerfile, build/Dockerfile.ci, cmd/manager/main.go, hack/run-ci-e2e-test.sh, pkg/clusternetwork/config.go, pkg/clusternetwork/config_test.go, pkg/controller/controller.go, pkg/controller/wellknownlocations/wellknownlocations.go, pkg/controller/windowsmachineconfig/nodeconfig/network.go, pkg/controller/windowsmachineconfig/nodeconfig/network_test.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/tracker.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, pkg/internal/cni-conf-template.json, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/validation_test.go
This commit run the wmcb's configure-cni command on the windows
nodes. It also transfers the files required for the configuration to the
windows VM. cni.conf file has been added in internal directory to be
transferred to the payload directory.  In addition, added the east-west networking tests to test
connection between linux, windows pods.
=> [wmco] Configure CNI on nodes

go.mod, go.sum
Operator imports wni module. This commit ensures that latest changes of wni
are reflected in the operator
=> [wmco] Bump wni version to reflect latest changes

build/Dockerfile
The path for cni-conf-template.json needs to be corrected in the
Dockerfile used for building operator image since we do not
clone windows-machine-config-operator project in the build directory
for this Dockerfile.
=> Bug 1840504: Copy cni-conf-template.json failed

build/Dockerfile, build/Dockerfile.ci
Update the download location of the kube-node binaries to v1.18.3.
=> [wmco] Bump kube-node binaries to v1.18.3

build/Dockerfile, build/Dockerfile.ci
Update the download and sha512 location of the CNI plugins to v0.8.6.
=> [wmco] Bump cni-plugins to v0.8.6

README.md, build/Dockerfile.ci, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml, hack/run-ci-e2e-test.sh, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR makes it so that our CI tests use an OLM deployed operator instead of a locally deployed one.
=> [ci] Test with OLM deployed operator

pkg/apis/wmc/v1alpha1/conditions.go, pkg/controller/windowsmachineconfig/status.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
This PR fixes the wmco reboot error that occurs due to
a stale resource read of the object from client cache for a
subsequent update. This PR replaces the default client
with a non-default-client that does not read from cache and
only updates the status to reconciling when we scale up or down.
Ref: [opertaor-sdk-non-default-client]( https://github.com/operator-framework/operator-sdk/blob/3efa98cb74a8388877724c574473c291677f2a18/website/content/en/docs/golang/references/client.md#non-default-client)
=> Bug 1840837: Get reconcile error on wmco reboot

README.md, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml, deploy/role.yaml, pkg/controller/windowsmachineconfig/nodeconfig/init.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig_test.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
This commit ensures that we no longer use KUBECONFIG to create or delete
instances. The changes include
-  removing all instances of kubeconfig
- adding pod, certificate approval permissions 
-  using infrastructure resource to get api server url.
[WINC-397](https://issues.redhat.com/browse/WINC-397)
=> [wmco] Remove Kubeconfig requirement

deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml, deploy/olm-catalog/windows-machine-config-operator/manifests/wmc.openshift.io_windowsmachineconfigs_crd.yaml, pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/status_test.go, test/e2e/validation_test.go
revert the changes brought in https://github.com/openshift/windows-machine-config-operator/pull/53/ as the change didn't really fix Bug 1835166
the bug was fixed as a part of upgrading to operator-sdk v0.18
=> revert replicas type int32 change

build/Dockerfile, build/Dockerfile.ci, cmd/manager/main.go, hack/run-ci-e2e-test.sh, pkg/controller/wellknownlocations/wellknownlocations.go, pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go, pkg/controller/windowsmachineconfig/windows/service.go, pkg/controller/windowsmachineconfig/windows/windows.go, pkg/internal/hns.psm1, test/e2e/network_test.go
This commit adds running kube-proxy as a Windows service as part of the
procedure of configuring new Windows nodes. This enables communication
with workloads on the Windows node from outside the cluster.
=> Run kube-proxy on new Windows nodes

hack/run-ci-e2e-test.sh
This commit ensures that KUBECONFIG secret is not created
in the hack script used for running e2e tests in CI. We removed
relying on the kubeconfig secret in
#66
=> [ci] Remove kubeconfig secret

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml, deploy/role.yaml, go.mod, go.sum, pkg/controller/windowsmachineconfig/tracker.go, pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
As of now, WMCO runs on pod network. This PR ensures that WMCO runs on
hostNetwork. This is a step towards making WMCO use machine api.
The advantage of running WMCO on hostNetwork includes not having a public IP
for the Windows VM created. This relies on
openshift/windows-machine-config-bootstrapper#214
The master branch of WNI is having issues while setting up SSH client. So pinning WNI in go.mod to
https://github.com/openshift/windows-machine-config-bootstrapper/commit/727c39ac62ac0b7622029f3ffc0eccbbb44e5693
=> Make WMCO run on hostNetwork

README.md, hack/run-ci-e2e-test.sh, test/e2e/main_test.go
The libra keypair should no longer be used as the CI secret from BitWarden has
changed recently
=> [ci] Change keypair

pkg/controller/windowsmachineconfig/windows/windows.go, pkg/internal/wget-ignore-cert.ps1
The MCO team have started moving to ignition v3 spec in MCS. For 4.6 timeframe,
they are supporting both v2 and v3. As a result, MCS now requires user-agent
in the header to tell which version of ignition spec to be served by MCS.
This PR modifies the powershell script to include a new parameter for the
user-agent header
https://issues.redhat.com/browse/WINC-457
=> [wmco] Add user-agent for ignition url

test/e2e/network_test.go, test/e2e/providers/aws/aws.go
This PR makes following changes to e2e tests:
- `retryInterval` is increased while pulling the Windows image for the first time in e2e tests
- To reduce the total duration of the tests, Windows NanoServer is introduced instead of using 
Windows ServerCore.
=> [ci] Fix flakiness of Windows webserver deployment

README.md, hack/common.sh, hack/olm.sh, hack/run-ci-e2e-test.sh
the hack script creates a container image for the operator
and pushes this operator image to remote repository and uses
it to deploy the operator on the cluster.
p.s. this is intended only for testing purpose.
=> [hack] add development script

build/Dockerfile, build/Dockerfile.ci, cmd/manager/main.go, cmd/manager/main_test.go
Update the kube-node tarball URL and SHA to v1.19 RC as per the [release changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#v1190-rc2).
=> [wmco] Upgrade to kube-node v1.19 RC

hack/common.sh, hack/run-ci-e2e-test.sh, test/e2e/create_test.go
- Don't proceed if the creation test fails
- Add additional guard that checks that the operator is running
- Update get_WMCO_logs with --tail=-1 to ensure we get all logs
=> [e2e] Fail on creation test failure

build/build.sh, cmd/manager/main.go, hack/common.sh, hack/olm.sh, version/version.go
this PR shifts all version related code to `version.go`
also, adds version sub-command as a CLI option to indicate what
version of the operator is being used.
=> [wmco] add version sub-command

README.md
Replacing old links to 'running operator locally' with those to 'development workflow' section
=> [docs] Replace dead links in README

hack/run-ci-e2e-test.sh, pkg/controller/windowsmachine/windows/windows.go, test/e2e/create_test.go, test/e2e/logs_test.go
This commit changes the log locations of kube-proxy and hybrid-overlay
to C:\\var\\log. This allows the use of `oc adm node-logs`, as log
paths given to the command must be relative to `/var/log`.
This commit also results in the gathering of the Windows node
artifacts in CI.
=> [wmco] Save Windows component logs to C:\\var\\log

README.md, hack/run-ci-e2e-test.sh, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This commit adds the version of the WMCO instance that configured each
node to that node's annotations. This will be used in the WMCO upgrade
process, as this allows WMCO to see which nodes were not configured by
the current version.
=> [wmco] Add WMCO version to Windows node

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This commit adds sets the WMCO CSV minKubeVersion to 1.19.0. This change
prevents WMCO from being deployed on clusters with Kubernetes versions
earlier than 1.19.0.
=> [olm] Add minKubeVersion to CSV

README.md
Call out that WMCO requires an OpenShift 4.6 cluster with hybrid OVN Kubernetes networking as a pre-requisite.
=> [docs] Add cluster type to README pre-requisites

build/Dockerfile, build/Dockerfile.ci, go.mod, hack/lint-gofmt.sh, test/e2e/main_test.go, test/e2e/network_test.go, vendor/modules.txt
This PR allows for Windows pods to be deployed in non-default namespaces.
=> Use downstream kubernetes node binaries

README.md, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, test/e2e/create_test.go, test/e2e/providers/aws/aws.go
As of now, WMCO is applying worker label to the node object created. The label
should be specified by the end-user in the MachineSet spec instead of WMCO being
prescriptive and applying the label.
This also solves:
https://bugzilla.redhat.com/show_bug.cgi?id=1860372
=> Bug 1860372: [wmco] Remove applying worker label

build/Dockerfile, build/Dockerfile.ci
Instead of using the CNI plugins from an upstream release, build it from the downstream OpenShift repo.
=> [build] Build CNI plugins from downstream

cmd/manager/main.go, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml, hack/common.sh, hack/olm.sh, hack/run-ci-e2e-test.sh, pkg/controller/controller.go, pkg/controller/secret/secret_controller.go, pkg/controller/secrets/secrets.go, pkg/controller/signer/signer.go, pkg/controller/wellknownlocations/wellknownlocations.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This commit is stopping the mounting of the cloud-private-key secret,
and instead fetching it within the Windows Machine and secret
controllers.
This has two main benefits. Firstly, this allows the
operator to be deployed without the cloud-private-key existing. This
will allow the operator to be properly deployed via the OpenShift
console, allowing for a much better UX. Machines will not be configured
until the private key secret is created, as they will not enter the
provisoned state until the userData secret is created by WMCO.
Secondly, this commit allows for our operator to update the userData
secret immediately after a change is made to the private key.
This commit made the private key secret the primary resource of the
secret controller. This is more fitting than the userData being …
=> [wmco] Watch cloud-private-key secret

README.md
- Fix the operator-sdk links to point to v0.18
- Remove the mention regarding operator-framework/operator-sdk#2938 as that has been fixed
- The MachineSet is mapping to a Linux worker. Fix that by adding`windows` to the MachineSet name.
=> [docs] Fix README operator-sdk and MachineSet refs

build/Dockerfile.ci
This is being done to resolve an issue with operator-sdk not having
the proper permissions to create a directory within the `deploy` folder.
=> [ci] Add write permissions to WMCO repo directory

hack/run-ci-e2e-test.sh, test/e2e/main_test.go, test/e2e/wmco_test.go
Since we are explicitly running every test suite, we dont need --skip-deletion
flag as an option for the different test suites. This commit removes the
explicit use of --skip-deletion option while running the tests.
However, the `--skip-deletion` flag is useful when we want to avoid running
of deletion test suite while running `run-ci-e2e-test.sh`
=> [wmco] Remove explicit use of --skip-deletion

hack/run-ci-e2e-test.sh, test/e2e/main_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/cloudprovider.go, test/e2e/wmco_test.go
It's not necessary to pass an SSH key pair name into the
MachineProviderConfig specs as an additional means of access.
The MachineProviderConfig already contains a UserDataSecret
specifying instructions for the Windows VM to set up and enable SSH
access.
=> [test] Remove passing of SSH Key Pair env var

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml
This PR updates operator.yaml to add node selector and tolerations
to allow operator deployment to run on control plane node. The PR
will be reverted once the networking issue is fixed, where
hostnetwork pod cannot access the kubernetes service.
Bug Reference : [BZ-1880974](https://bugzilla.redhat.com/show_bug.cgi?id=1880974)
=> [ci] Run operator deployment on control plane

pkg/controller/windowsmachine/windows/service.go, pkg/controller/windowsmachine/windows/windows.go
With the newly introduced feature, we can now run hybrid-overlay-node.exe as a Windows Service. This PR will leverage this functionality to start running hybrid-overlay-node as a Windows Service on the Windows nodes using WMCO.
=> [wmco] Run hybrid overlay as a Windows service

hack/common.sh, hack/olm.sh
Adds a build command to the olm.sh script for convenience.
The build command builds the operator image and pushes it to the
registry specified in the
OPERATOR_IMAGE env var, without deploying the operator on the cluster.
=> [hack/olm.sh] Add build cmd

README.md, cmd/manager/main.go, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, hack/run-ci-e2e-test.sh, pkg/apis/addtoscheme_mapi_v1beta1.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
This PR makes sure that machine controller handles changes in version
annotation on Windows nodes. The version annotation can be changed in the following scenarios -
- During upgrade process, where `operatorVersion` would not match with the version used in the annotation
- When node annotation is tampered by an user
The controller makes sure to delete the machines and subsequently the nodes, when annotation is mismatched and the number of nodes after deletion are greater than the predetermined `minHealthyCount`
This PR also increases the value of `nodeCreation` in the e2e tests, to take into consideration time required to delete the node and recreate it.
=> [wmco] Delete Machines with mismatched version annotations

go.sum, test/e2e/network_test.go
This commit increases the coverage of the east to west networking tests
to include reaching the Windows webserver through a clusterIP service.
This commit also accomplishes a refactoring of the existing tests into a
table driven test format.
Co-authored-by: Sebastian Soto <ssoto@redhat.com>
=> [WINC-496] [ci] Add east/west e2e tests through a clusterIP

README.md, deploy/namespace.yaml, deploy/olm-catalog/operatorgroup.yaml, deploy/olm-catalog/subscription.yaml, deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, hack/common.sh, hack/run-ci-e2e-test.sh, test/e2e/delete_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
This commit changes the namespace the operator is deployed to by default
to `openshift-windows-machine-config-operator`, instead of the
`windows-machine-config-operator` namespace used before.
This is a requirement for Prometheus monitoring.
=> [deploy] Use openshift-windows-machine-config-operator namespace

pkg/controller/windowsmachine/windows/connectivity.go, pkg/controller/windowsmachine/windows/windows.go
The run() methods were not returning the output in the case of errors. This commit fixes and the call sites where the output was not being propagated.
=> [wmco] Fix error output not being shown in logs

test/e2e/network_test.go
I noticed warnings on the linux curler pods:
```
2020-09-30 16:42:01,690 [ERROR] yum:8:MainThread @logutil.py:194 - [Errno 13] Permission denied: '/var/log/rhsm/rhsm.log' - Further logging output will be written to stderr
Not root, Subscription Management repositories not updated
Error: This command has to be run under the root user.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<html><body><H1>Windows Container Web Server</H1></body></html>100    63  100    63    0     0   2100   
```
This fixes the warning thrown on linux curler pods by not calling yum (curl is already present).
=> [test] Use ubi-minimal image for Linux curlers

README.md, docs/HACKING.md, docs/setup-hybrid-OVNKubernetes-cluster.md
Splits out the development instructions into `docs/HACKING.md` and
updates `README.md` to align with the contents of the community
operator description on OperatorHub.
=> [docs] Update README.md, split out HACKING.md

README.md, hack/machineset.sh
this script makes the creation of MachineSet on AWS and Azure platform
less of a task.
Requires an existing logged in cluster to create MachineSet
Currently works only for AWS and AZURE platform
USAGE
`machineset.sh apply/delete`
OPTIONS
`$1           Action (optional)             apply/delete the MachineSet`
=> [hack] add MachineSet creation/deletion script

.gitmodules
Convention is that .git is used for bare repositories and it is left off for repositories with a working tree. Note that not having a trailing / will help folks using the following
```
git config:
[url "git@github.com:"]
insteadOf = https://github.com/
```
=> [git] Normalize gitmodules URLs

.ci-operator.yaml
This commit allows us to change the build_root_image with commits to
this repo. Previously we would hit an issue with breaking builds due to
bumping the required go version within this repository and then having
to update the used go version within the openshift/release repo.
https://docs.ci.openshift.org/docs/architecture/ci-operator/#build-root-image
=> WINC-460: [ci] Define build_root_image within repo

pkg/controller/windowsmachine/windows/connectivity.go
This commit makes it so that the log.Error() function is used properly
when transferring files over ssh
=> [wmco] Fix error logging when transfering files

bundle.Dockerfile
This commit updates the bundle.Dockerfile with the required labels to create a WMCO bundle Dockerfile using render_templates in the Windows-machine-config-operator-bundle [dist-git](http://pkgs.devel.redhat.com/cgit/containers/windows-machine-config-operator-bundle/?h=rhaos-4.6-rhel-8) repository. This Dockerfile is used for our bundle build process in CPaaS pipeline.
=> update bundle.Dockerfile for dist-git

pkg/controller/secrets/secrets.go
OpenSSHUtils is getting deprecated
MicrosoftDocs/windowsserverdocs#3806
We need to move away from using OpenSSHUtils to configure ssh
access to Windows VMs
Remove installing OpenSSHUtils and its usage for setting the
authorized keys and uses the built-in ssh mechanism supported
by Windows Server 1709 and above
=> WINC-525: [WMCO] Handle OpenSSHUtils deprecation

build/Dockerfile.ci
PR #154 tried to be smart by copying just enough git metadata for version reporting. This however was resulting in a non-fatal failure, `fatal: bad object HEAD`. Fix this by being less smart and more thorough.
=> [ci] Fix WMCO version injection in Dockerfile

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/operator.yaml
WMCO has escalated permissions and we need to run it on 
control-plane hosts. 
This reverts commit 0c33029.
=> WINC-527: [wmco] run WMCO on control plane

build/Dockerfile.ci
Do not update the packages for base image, since it might lead to failures with conflicting packages. If there are updates to the image, they should be picked up with the image itself.
=> [ci] Remove microdnf update

docs/HACKING.md, hack/common.sh, hack/olm.sh
Using the `-k private-key-path` input with the `run` option will result in the cloud-private-key secret being created. This improves the development workflow.
=> [hack] Add private key input to olm.sh

pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/network_test.go, test/e2e/upgrade_test.go
Previously, during an upgrade, wmco defined minHealthy count. This count was
taken into consideration while deleting the nodes with mismatched version.
This commit updates the deletion process to take into account maxUnhealthy
count. This count ensures that we have only limited number of nodes that
are in Not Ready state during an upgrade
It also adds tests for workload availability during Upgrade process.
[WINC-523](https://issues.redhat.com/browse/WINC-523)
=> WINC-523: [wmco] Update Node deletion during upgrade

bundle.Dockerfile
Sync bundle.Dockerfile with WMCO current directory structure, we had updated this file to match the WMCO bundle dist-git directory structure, the dist-git layout will be updated to match with WMCO and reuse this Dockerfile.
=> Sync bundle.Dockerfile with WMCO directory structure

cmd/manager/main.go, hack/run-ci-e2e-test.sh, pkg/controller/payload/payload.go, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, pkg/controller/windowsmachine/windows/windows.go, test/e2e/reconfigure_test.go, test/e2e/wmco_test.go
This commit makes it so that we check the sha256 checksum of files that
were previously transfered to Windows nodes. If the checksum does not
match what we expect it to, the correct file will be transfered over.
=> WINC-513: Ensure all transfered files have the correct hash

hack/lint-gofmt.sh
Excludes the recently added windows_exporter and promu submodules
from go fmt linting.
=> [hack] lint-gofmt.sh: Exclude windows_exporter and promu submodules

build/Dockerfile, build/Dockerfile.ci
This avoids problems when files that cannot be archived with tar, like sockets, are present in the yum cache (container images are tar archives).
=> [build] Add `microdnf clean all` to Dockerfiles

build/Dockerfile, build/Dockerfile.ci, test/e2e/create_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
This PR fixes the bug where kubelet and kube-proxy were not
reporting correct version.
This was because of absence of git metadata which is required for
setting this version.
The bug fix includes copying the git metadata.
Also, added test to check the kubelet version in-case it breaks again.
We are just checking if the prefix has the major and minor version like `v1.19`
Consolidated the node metadata test and included kubelet version there
Also, simplified the way we build the promu binary, by using `go install .`
=> Bug 1894631: Fix k8s version being misreported

hack/run-ci-e2e-test.sh
This PR checks if the OO_INDEX ENV var is set and the operator deployment is already rolled out to skip deployment in WMCO e2e tests.
$OO_INDEX points to the WMCO bundle index image created through https://docs.ci.openshift.org/docs/how-tos/testing-operator-sdk-operators/ workflow in CI. 
This is a step towards moving to the _Testing Operators Built With The Operator SDK and Deployed Through OLM_ workflow.
=> WINC-519: skip operator deployment in e2e tests

pkg/controller/windowsmachine/windows/windows.go
Use the command "sc.exe qe" and the error code "1060" as hints to not log the error. We are doing this as it was spamming the log with no informational benefit.
(cherry picked from commit e5b96f3991d81364748f884a820c2e70ab44f84f)
=> WINC-547: [release-4.6][wmco] Don't log when a service is not found

hack/common.sh
The tests have been failing a lot because
`operator-sdk run packagemanifests` has a default timeout of 2min which
was often missed. This commit extends the timeout to 5min to ensure the
command can return properly even when running on slower infrastructure.
With version 0.19.4 of the operator-sdk, the `run` command should now
return correct values, hence the condition and comment to explicitly
check for that have been removed.
Reverts ea557cb8ebb7a276e220af52fd9768ba10c6d16f
=> WINC-453: [hack] Extend OSDK run timeout to 5min

hack/common.sh
The tests have been failing a lot because
`operator-sdk run packagemanifests` has a default timeout of 2min which
was often missed. This commit extends the timeout to 5min to ensure the
command can return properly even when running on slower infrastructure.
With version 0.19.4 of the operator-sdk, the `run` command should now
return correct values, hence the condition and comment to explicitly
check for that have been removed.
Backport of #195
=> WINC-453: [release-4.6] [hack] Extend OSDK run timeout to 5min

hack/common.sh
The tests have been failing a lot because
`operator-sdk run packagemanifests` has a default timeout of 2min which
was often missed. This commit extends the timeout to 5min to ensure the
command can return properly even when running on slower infrastructure.
With version 0.19.4 of the operator-sdk, the `run` command should now
return correct values, hence the condition and comment to explicitly
check for that have been removed.
Backport of #195
=> WINC-453: [community-4.6] [hack] Extend OSDK run timeout to 5min

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.ci, go.mod, hack/lint-gofmt.sh
Backports https://github.com/openshift/windows-machine-config-operator/pull/179 to release-4.6 branch.
=> [release-4.6] Update to Go 1.15

.gitmodules
Updates the kubernetes submodule to commit ad738ba548b6d6b5cd2e83351951ccd7019afa4c.
Also changes the referenced branch in .gitmodules to release-4.7
Commands run:
```
cd kubernetes
git fetch origin && git checkout ad738ba548b6d6b5cd2e83351951ccd7019afa4c
cd ..
```
That commit includes the kubelet changes that allow for querying the WinEvent logs with `oc adm node-logs`.
~~Blocked by https://github.com/openshift/windows-machine-config-operator/pull/179~~
=> [k8s] Update submodule to current openshift:release-4.7

bundle.Dockerfile
windows-machine-config-operator-bundle comet container repository in openshift4 namespace has been deprecated and moved to openshift4-wincw namespace. This commit updates the label name to point the repository in openshift4-wincw namespace.
=> Update namespace for label component name in bundle.Dockerfile

bundle.Dockerfile
windows-machine-config-operator-bundle comet container repository in openshift4 namespace has been deprecated and moved to openshift4-wincw namespace. This commit updates the label name to point the repository in openshift4-wincw namespace.
=> [release-4.6] Update namespace for label component name in bundle.Dockerfile

bundle.Dockerfile
This PR updates the channel in bundle.Dockerfile from "alpha" to "preview" for the availability of the first release-candidate of WMCO.
=> Update release channel to "preview" in bundle.Dockerfile

bundle.Dockerfile
This PR updates the channel in bundle.Dockerfile from "alpha" to "preview" for the availability of the first release-candidate of WMCO.
=> [release-4.6] Update release channel to "preview" in bundle.Dockerfile

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/olm-catalog/windows-machine-config-operator/metadata/annotations.yaml
- Remove upgrade verbiage from the description in the CSV which only applies to the community operator
- The channel name needs to match the name in the Dockerfile label in the release Dockerfile.
=> [release-4.6][deploy] Fix channel name and description

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, hack/common.sh
Update WMCO binary version in hack/common.sh from 0.0.1 to 1.0.0 for the release.
Add the various metadata fields like description, createdAt, maintainers, containerImage, categories etc in CSV that are used to populate the operatorhub UI of WMCO.
=> Bug 1905429: Fix WMCO version and info missed in web console

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, hack/common.sh
Update WMCO binary version in hack/common.sh from 0.0.1 to 1.0.0 for the release.
Add the various metadata fields like description, createdAt, maintainers, containerImage, categories etc in CSV that are used to populate the operatorhub UI of WMCO.
=> Bug 1905716: [release-4.6] Fix WMCO version and info missed in web console

bundle.Dockerfile, deploy/olm-catalog/windows-machine-config-operator/metadata/annotations.yaml, hack/common.sh
This PR updates the WMCO default channel in annotations.yaml and the bundle.Dockerfile to "stable".
In addition we add both "preview" and "stable" channels to the list of available channels for release 1.0.1.
This also updates the WMCO version to 1.0.1 in hack script.
=> [deploy] Update WMCO channel and version

bundle.Dockerfile, deploy/olm-catalog/windows-machine-config-operator/metadata/annotations.yaml, hack/common.sh
This PR updates the WMCO default channel in annotations.yaml and the bundle.Dockerfile to "stable" 
on the release-4.6 branch. 
In addition we add both "preview" and "stable" channels to the list of available channels for release 1.0.1.
This also updates the WMCO version to 1.0.1 in hack script.
(cherry picked from commit 4d0f08383f52daa62b643900c03149b646e82974)
=> [release-4.6] [deploy] Update WMCO channel and version

test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/network_test.go
the `defer deleteService` in network test is not able to delete the
service in time. Sometimes it succeeds in deleting the service and
sometimes it takes a lot of time.
we are creating service of same name in upgrade test. In case the
service is not deleted, it throws an error.
This is causing our tests to fail.
The fix includes changing the service name. We are doing
this by using `generateName` field while creating the service
we are frequently coming across timeout while deleting the nodes
the nodes are usually deleted within a minute but sometimes they
time out.
this PR increases the timeout from 5 minutes to 10 minutes
=> [test] fix failing upgrade and delete tests

hack/common.sh
This PR updates the WMCO version to 1.0.2 in hack/common.sh script.
=> [release-4.6] [hack] Update WMCO version to 1.0.2

test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/network_test.go
the defer deleteService in network test is not able to delete the
service in time. Sometimes it succeeds in deleting the service and
sometimes it takes a lot of time.
we are creating service of same name in upgrade test. In case the
service is not deleted, it throws an error.
This is causing our tests to fail.
The fix includes changing the service name. We are doing
this by using generateName field while creating the service
we are frequently coming across timeout while deleting the nodes
the nodes are usually deleted within a minute but sometimes they
time out.
this PR increases the timeout from 5 minutes to 10 minutes
Backport of #216
=> [release-4.6][test] fix failing upgrade and delete tests

build/Dockerfile, build/Dockerfile.ci, docs/HACKING.md, hack/common.sh, hack/olm.sh, hack/run-ci-e2e-test.sh
This is a backport of https://github.com/openshift/windows-machine-config-operator/pull/203
this PR removes the usage of `operator-sdk build`
command to build the operator image.
We are now building the operator binary in dockerfile
similar to what we are doing in dockerfile.ci and
using `make build` which uses `build/build.sh` to set
the version for operator binary. Removed other
references of setting version in `hack/olm.sh`
Also included building the WMCO binary using
`make build` while launching the tests through local
machine.
We use this binary for validating the version
annotation on the operator.
This change is needed as `operator-sdk build`
used to generate the operator binary before building
the container image. Now that we are using
`podman build`, we need to explicitly use …
=> [release-4.6][build] Fix version and remove operator-sdk build

test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/network_test.go
the defer deleteService in network test is not able to delete the
service in time. Sometimes it succeeds in deleting the service and
sometimes it takes a lot of time.
we are creating service of same name in upgrade test. In case the
service is not deleted, it throws an error.
This is causing our tests to fail.
The fix includes changing the service name. We are doing
this by using generateName field while creating the service
we are frequently coming across timeout while deleting the nodes
the nodes are usually deleted within a minute but sometimes they
time out.
this PR increases the timeout from 5 minutes to 10 minutes
Backport of #216
=> [community-4.6][test] fix failing upgrade and delete tests

build/Dockerfile, build/Dockerfile.ci, docs/HACKING.md, hack/common.sh, hack/olm.sh, hack/run-ci-e2e-test.sh
This is a backport of https://github.com/openshift/windows-machine-config-operator/pull/203
this PR removes the usage of `operator-sdk build`
command to build the operator image.
We are now building the operator binary in dockerfile
similar to what we are doing in dockerfile.ci and
using `make build` which uses `build/build.sh` to set
the version for operator binary. Removed other
references of setting version in `hack/olm.sh`
Also included building the WMCO binary using
`make build` while launching the tests through local
machine.
We use this binary for validating the version
annotation on the operator.
This change is needed as `operator-sdk build`
used to generate the operator binary before building
the container image. Now that we are using
`podman build`, we need to explicitly use …
=> [community-4.6][build] Fix version and remove operator-sdk build

hack/run-ci-e2e-test.sh, pkg/controller/windowsmachine/windows/connectivity.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/create_test.go
This commit prevents an issue where a user changes the private key used
to configure Windows Machines, after unconfigured Machines have been
created with the original userdata secret. When those unconfigured
Machines are reconciled they will never be able to be SSH'd into and
will infinitely be requeued.
This issue is being fixed by deleting Machines that have had an
authentication error so that they can be re-provisioned with userdata
corresponding with the new private key.
=> WINC-485: [wmco] Delete Machines when SSH auth fails

build/Dockerfile, build/Dockerfile.ci, docs/HACKING.md, hack/common.sh, hack/olm.sh, hack/run-ci-e2e-test.sh
this commit removes the usage of `operator-sdk build`
command to build the operator image.
We are now building the operator binary in dockerfile
similar to what we are doing in dockerfile.ci and
using `make build` which uses `build/build.sh` to set
the version for operator binary. Removed other
references of setting version in `hack/olm.sh`
Also included building the WMCO binary using
`make build` while launching the tests through local
machine.
We use this binary for validating the version
annotation on the operator.
This change is needed as `operator-sdk build`
used to generate the operator binary before building
the container image. Now that we are using
`podman build`, we need to explicitly use
`make build` to generate operator binary for e2e test.
Only e2e tests launched through …
=> [build] Fix version and remove operator-sdk build 

test/e2e/network_test.go, test/e2e/upgrade_test.go
This commit carries over the changes from #216,
i.e using generateName for deployment and job objects.
This change also requires changing the way we use win-webserver in the
upgrade test.
In the upgrade test, we are getting the win-webserver deployment object
created in the network test using a get method. We are getting this
deployment using the deployment name.
As we will be using generateName across the board, we need to change the
way we get the windows web server deployment.
As this is a web server deployment, we can create a new one for
upgrade tests just before we start the test and the linux curler which
ensures that the webserver is functioning across an upgrade, and not use
the win-webserver created in network test. Everything
should be destroyed once we tear down the cluster.
=> WINC-557: [test] Use generateName instead of Name

test/e2e/create_test.go
This commit ensures that we test Node Status as a part of our e2e tests.
When the operator reconciles successfully, the Node can be in NotReady
state. This is an unexpected outcome and should be tested as a part of
waitForWindowsNodes function. The changes include checking if the Node
has condition type Ready and if it has a value 'true' for a successful
test.
=> [wmco][e2e] Add test to check Node Status

test/e2e/network_test.go, test/e2e/upgrade_test.go
This is a backport of #236 
This commit ensures that we use generateName instead of Name                                        
for deployment and job objects.  
This change also requires changing the way we use win-webserver in the
upgrade test.
In the upgrade test, we are getting the win-webserver deployment object
created in the network test using a get method. We are getting this
deployment using the deployment name.
As we will be using generateName across the board, we need to change the
way we get the windows web server deployment.
As this is a web server deployment, we can create a new one for
upgrade tests just before we start the test and the linux curler which
ensures that the webserver is functioning across an upgrade, and not use
the win-webserver created in network test.
=> [community-4.6][test] Use generateName instead of Name

test/e2e/network_test.go, test/e2e/upgrade_test.go
This is a backport of #236 
This commit ensures that we use generateName instead of Name                                        
for deployment and job objects.  
This change also requires changing the way we use win-webserver in the
upgrade test.
In the upgrade test, we are getting the win-webserver deployment object
created in the network test using a get method. We are getting this
deployment using the deployment name.
As we will be using generateName across the board, we need to change the
way we get the windows web server deployment.
As this is a web server deployment, we can create a new one for
upgrade tests just before we start the test and the linux curler which
ensures that the webserver is functioning across an upgrade, and not use
the win-webserver created in network test.
=> [release-4.6][test] Use generateName instead of Name

hack/run-ci-e2e-test.sh, pkg/controller/windowsmachine/windows/connectivity.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/create_test.go
Backport of https://github.com/openshift/windows-machine-config-operator/pull/202
This commit prevents an issue where a user changes the private key used
to configure Windows Machines, after unconfigured Machines have been
created with the original userdata secret. When those unconfigured
Machines are reconciled they will never be able to be SSH'd into and
will infinitely be requeued.
This issue is being fixed by deleting Machines that have had an
authentication error so that they can be re-provisioned with userdata
corresponding with the new private key.
=> [community-4.6] Delete Machines when SSH auth fails

bundle.Dockerfile, hack/common.sh
This PR updates the operator version to 2.0.0 for the 4.7 release in hack/common.sh
It also updates the operator supported OpenShift version label to be set to "=v4.7" in bundle.Dockerfile.
=> Update operator version and supported OpenShift version label

bundle.Dockerfile, hack/common.sh
Backport of https://github.com/openshift/windows-machine-config-operator/pull/244
This PR updates the operator version to 2.0.0 for the 4.7 release in hack/common.sh
It also updates the operator supported OpenShift version label to be set to "=v4.7" in bundle.Dockerfile.
=> [community-4.7] Update operator version and supported OpenShift version label

build/Dockerfile
This commit switches from a dockerhub hosted image to a Red Hat hosted
image. This will fix an issue with dockerhub rate limiting when building
the community operator.
=> Switch build base image to Red Hat hosted image

build/Dockerfile, build/Dockerfile.ci
This PR creates windows_exporter directory before-hand and explicitly sets the GOBIN path to specify where the promu binary should be installed, promu installed in the windows_exporter directory is then utilized for its installation.
This change was necessary because Cachito integration on CpaaS side changes the GOPATH during image build and if the path is not specified promu is installed to some location from which it is not accessible to build windows_exporter executable.
=> Explicitly set GOBIN path for promu installation

hack/packet_trace.sh
This commit fixes an issue that would prevent the packet trace script
from running against any node without the user capi.
=> [hack] Fix user issue in packet trace script

pkg/controller/secret/secret_controller.go, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/create_test.go, test/e2e/secrets_test.go, test/e2e/validation_test.go
If the private key used to configure nodes changes, Machines configured
with the old key will be deleted, so that they can be replaced with new
Machines.
=> Add pubkey annotation to Windows nodes

hack/olm.sh
Fix the `noCache` command in olm.sh hack script to build the
operator image without cache.
This change is required as we are no longer using
`operator-sdk build` to create the operator image
\cc: @alinaryan
=> [hack] fix noCache command in olm.sh

build/Dockerfile, build/Dockerfile.ci
This commit explicitly sets the GOBIN path
to specify where the promu binary should be
installed, promu installed in the windows_exporter
directory is then utilized for its installation.
This change was necessary because cachito changes
the GOPATH during image build and if the path is
not specified promu is installed to some location
from which it is not accessible to build
windows_exporter executable.
(cherry picked from commit 6f65fced396dcfb17c73a97aebd0119740c85cb6)
=> [community-4.7] Explicitly set GOBIN path for promu installation

cmd/manager/main.go, cmd/manager/main_test.go, go.mod, vendor/golang.org/x/mod/LICENSE, vendor/golang.org/x/mod/PATENTS, vendor/golang.org/x/mod/semver/semver.go, vendor/modules.txt
This commit ensures that we no longer are tied to exact version
OpenShift. The changes allow WMCO to run on N and N+1 versions of
OpenShift. This is required to perform seamless upgrade between
4.6 to 4.7 OpenShift version.
=> WINC-565: [release-4.6] [wmco] Relax k8s version strict dependency

bundle.Dockerfile, hack/common.sh
This PR introduces following changes:
- Operator version update to prep for release 1.0.3
- Update cluster version label for wmco bundles to ensure that they are present only
within OCP 4.6 version.
=> [release-4.6][wmco] Prep for 1.0.3 release

go.mod, pkg/cluster/config.go, pkg/cluster/config_test.go, vendor/modules.txt
This commit ensures that we no longer are tied to exact version
OpenShift. The changes allow WMCO to run on N and N+1 versions of
OpenShift. This is required to perform seamless upgrade between
N to N+1 versions.
=> WINC-565: [wmco] Relax k8s version strict dependency

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR adds the skipRange option and value `">=1.0.0 <2.0.0" ` to CSV for the 2.0.0 release. Since the 2.0.0 operator
is not in the same index as 1.x operator, we need to use 'skipRange' instead of the 'replaces' field for the upgrade process.
=> [deploy] Add skipRange to csv for 2.0.0 release

hack/machineset.sh
This PR modifies the  ami_date for AWS machineset creation script from 2020.09.09 to 2020-10-14, since
the earlier is no longer available in AWS regions.
=> [hack] Modify ami_date for machineset.sh script

build/Dockerfile
Reverts openshift/windows-machine-config-operator#258 as registry.svc.ci.openshift.org/origin/builder:golang-1.15 image requires access credentials. Moreover openshift/windows-machine-config-operator#258 never actually fixed the rate limiting as it was not backported to the `community-*` branches.
=> Revert "Switch build base image to Red Hat hosted image"

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the operator capability in  the WMCO CSV to Seamless upgrades indicating it supports upgrades now.
(cherry picked from commit ae352e84bdd06cddf9d50589209d6f5af842eebb)
=> [release-4.6] [deploy] Update Operator capability to 'Seamless Upgrades'

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the operator capability in the WMCO CSV to Seamless upgrades indicating it supports upgrades now.
(cherry picked from commit ae352e84bdd06cddf9d50589209d6f5af842eebb)
=> [Community-4.7] [deploy] Update Operator capability to 'Seamless Upgrades'

test/e2e/create_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/vsphere/vsphere.go
And use it to only run the `Changing the private key ensures all Windows nodes use the new private key` test on AWS. This cannot be run against a vSphere cluster because this random key is not part of the vSphere template image. Moreover this test is platform agnostic so is not needed to be run for every supported platform.
(cherry picked from commit 34cb58f1828825e54af9381730a3b00a28fe1453)
=> [release-4.7][test] Introduce CloudProvider.GetType()

test/e2e/create_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/vsphere/vsphere.go
Introduce CloudProvider.GetType() and use it to only run the `Changing the private key ensures all Windows nodes use the new private key` test on AWS. We don't want to run this on vSphere because this random key is not part of the vSphere template image. Moreover this test is platform agnostic so is not needed to be run for every supported platform.
=> [test] Fix e2e tests for vSphere

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the operator capability in the WMCO CSV to Seamless upgrades indicating it supports upgrades now.
(cherry picked from commit ae352e84bdd06cddf9d50589209d6f5af842eebb)
=> [release-4.7] [deploy] Update operator capability to 'Seamless upgrades'

test/e2e/create_test.go, test/e2e/reconfigure_test.go, test/e2e/upgrade_test.go
- Run upgrade test only on AWS
- Run reconfiguration test only on Azure
- Run "Windows Machines without the Windows label are not configured"
only on Azure
=> [test] Don't run all tests on all platforms

pkg/controller/secret/secret_controller.go, pkg/controller/windowsmachine/nodeconfig/nodeconfig.go, pkg/controller/windowsmachine/windowsmachine_controller.go, test/e2e/create_test.go, test/e2e/secrets_test.go, test/e2e/validation_test.go
If the private key used to configure nodes changes, Machines configured
with the old key will be deleted, so that they can be replaced with new
Machines.
Backport of https://github.com/openshift/windows-machine-config-operator/pull/239
=> [community-4.7] Add pubkey annotation to Windows nodes

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/windowsmachine/metrics/metrics.go
This commit checks for an existing service monitor object on a WMCO restart.
If a service monitor object does exist, it is deleted and a new one is created.
We are deleting to ensure that the SM always exists with the correct spec. Otherwise,
metrics may exhibit unexpected behavior if created by a previous version of WMCO.
(cherry picked from commit 2209daf0d0c6d5ebe7a0a986c509854539355780)
=> [community-4.7][wmco] Delete existing service monitor object on WMCO restart

test/e2e/create_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/vsphere/vsphere.go
And use it to only run the "Changing the private key ensures all Windows nodes use the new private key" test on AWS. This cannot be run against a vSphere cluster because this random key is not part of the vSphere template image. Moreover this test is platform agnostic so is not needed to be run for every supported platform.
(cherry picked from commit 34cb58f1828825e54af9381730a3b00a28fe1453)
(backport of #285)
=> [community-4.7][test] Introduce CloudProvider.GetType()

hack/common.sh, hack/machineset.sh
error-exit is being called in run-ci-e2e-test.sh but it is defined in machineset.sh. Fix this by moving it to common.sh.
=> [hack] Move error-exit to common.sh

docs/machineset-aws.md, hack/machineset.sh
This commit removes the AWS describe-image command 
from the docs as we will be changing the script in a follow-up 
PR to grab the latest tag for getting the ami since the date is 
constantly being changed by AWS. It also updates the
ami_date in the hackscript from 2020.10.14 to 2021.01.13 
to be used in the meantime, since the earlier date is no longer 
available in AWS regions.
=> [docs] Remove AWS describe-image command 

pkg/controller/windowsmachine/metrics/metrics.go
This commit removes the constant used as name for  metrics resources.
The name for metrics resources is set by 'metrics' package of operator-sdk
and is equivalent to the name of the metrics service. The changes include
retrieving the name set by the 'metrics' package and using it for accessing
the resources.
(cherry picked from commit 831e42db1a24264fd28bb6f38e780e576ea3d6ce)
=> [community-4.7][wmco] Remove constant for metrics resources name

hack/common.sh, hack/machineset.sh
error-exit is being called in run-ci-e2e-test.sh but it is defined in machineset.sh. Fix this by moving it to common.sh.
(cherry picked from commit 92065011e2329f697d714e668e178bae7af97f8f)
(backport of #306)
=> [community-4.7][hack] Move error-exit to common.sh

controllers/windowsmachine/windowsmachine_controller.go
This commit fixes an issue where a the `signer` of the Windows Machine
reconciler could be used when nil. This was not being caught in our e2e
tests because if the signer's value was set in a previous reconcile that
stale value would be used.
This is being fixed by moving where the signer is set to before its
usage, where it should have been in the first place.
=> Bug 1929579: [wmco] Fix issue with dereferencing nil signer

pkg/controller/windowsmachine/windowsmachine_controller.go
This commit fixes an issue where a the `signer` of the Windows Machine
reconciler could be used when nil. This was not being caught in our e2e
tests because if the signer's value was set in a previous reconcile that
stale value would be used.
This is being fixed by moving where the signer is set to before its
usage, where it should have been in the first place.
(cherry picked from commit 19a7e68a64e46ad31b9aea729da8d422e29bdd4e)
=> Bug 1929794: [wmco] Fix issue with dereferencing nil signer

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/metrics/metrics.go
This change checks for an existing service monitor object on a WMCO restart.
If a service monitor object does exist, it is deleted and a new one is created.
We are deleting to ensure that the SM always exists with the correct spec. Otherwise,
metrics may exhibit unexpected behavior if created by a previous version of WMCO.
=> Bug 1905280: [wmco] Delete existing service monitor object on WMCO restart

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/windowsmachine/metrics/metrics.go
This commit checks for an existing service monitor object on a WMCO restart.
If a service monitor object does exist, it is deleted and a new one is created.
We are deleting to ensure that the SM always exists with the correct spec. Otherwise,
metrics may exhibit unexpected behavior if created by a previous version of WMCO.
(cherry picked from commit 2209daf0d0c6d5ebe7a0a986c509854539355780)
=> [community-4.6][wmco] Delete existing service monitor object on WMCO restart

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR corrects the CSV description to mention pre-requisite of 4.7 clusters and
formats the VM template requirements.
=> Bug 1930184: Fix formatting and description for WMCO 2.0.0

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
This PR  corrects the CSV description to mention pre-requisite of 4.7 clusters and formats the VM template requirements.
(cherry picked from commit 27e90d91a61ad69d0648f49b6d17bb50962abf27)
=> Bug 1930257: Fix formatting and description for WMCO 2.0.0

test/e2e/network_test.go, test/e2e/providers/azure/azure.go
- Use the corresponding container image for the deployments
- Use the appropriate PowerShell executable based on container image
=> WINC-555: [test] Use Windows Server 20H2 for Azure e2e tests

test/e2e/create_test.go
https://github.com/openshift/windows-machine-config-operator/pull/239 changed the behavior of `Windows Machines without the Windows label are not configured` test causing it wait longer for the test to finish. This commit reverts the test back to the original behavior.
Added a few print statements to help with CI debugging on failures.
=> [test] Reduce wait time for without label test

controllers/secret/secret_controller.go, test/e2e/validation_test.go
This commit fixes an issue where the public key hash annotation was being
added to not all nodes, not just Windows nodes. This commit also adds
logic to remove the annotation from Linux nodes when the operator is
installed.
As part of this fix, Windows node selection in the secret controller
now uses the label "kubernetes.io/os=windows". There is a mix of this
label and "node.openshift.io/os_id=Windows" in the node selection logic
throughout WMCO, and we should move towards just using one. Future work
should be done to only use the "kubernetes.io/os" label for node
selection throughout WMCO.
=> Bug 1930791: [wmco] Stop adding pub-key-hash label to all nodes

test/e2e/create_test.go, test/e2e/reconfigure_test.go, test/e2e/upgrade_test.go
- Run upgrade test only on AWS
- Run reconfiguration test only on Azure
- Run "Windows Machines without the Windows label are not configured" only on Azure
(cherry picked from commit 446b72eda149689863031b69f840675bde948603)
=> [release-4.7][test] Don't run all tests on all platforms

hack/common.sh, hack/machineset.sh
error-exit is being called in run-ci-e2e-test.sh but it is defined in machineset.sh. Fix this by moving it to common.sh.
(cherry picked from commit 92065011e2329f697d714e668e178bae7af97f8f)
(backport of #306)
=> [release-4.7][hack] Move error-exit to common.sh

deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/windowsmachine/metrics/metrics.go
This commit checks for an existing service monitor object on a WMCO restart.
If a service monitor object does exist, it is deleted and a new one is created.
We are deleting to ensure that the SM always exists with the correct spec. Otherwise,
metrics may exhibit unexpected behavior if created by a previous version of WMCO.
(cherry picked from commit 2209daf0d0c6d5ebe7a0a986c509854539355780)
=> [release-4.7][wmco] Delete existing service monitor object on WMCO restart

pkg/metrics/metrics.go
This commit removes the constant used as name for  metrics resources.
The name for metrics resources is set by 'metrics' package of operator-sdk
and is equivalent to the name of the metrics service. The changes include
retrieving the name set by the 'metrics' package and using it for accessing
the resources.
(cherry picked from commit 831e42db1a24264fd28bb6f38e780e576ea3d6ce)
=> [release-4.7][wmco] Remove constant for metrics resources name

README.md, docs/machineset-aws.md, docs/machineset-azure.md, docs/setup-hybrid-OVNKubernetes-cluster.md, docs/vsphere-prerequisites.md
Clearly call out when and why the custom VXLAN port cluster configuration should be used and how it affects the image picked in the MachineSet.
=> [docs] Clarify cluster and image requirements

hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/wmco_test.go
Move the network tests out from the creation tests. This is in preparation for separating out the upgrade and reconfiguration tests into a separate CI job.
=> [test] Separate out the network tests

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.ci, go.mod, hack/lint-gofmt.sh
As of https://github.com/openshift/ocp-build-data/pull/858 OCP will be built with Go 1.16, so move the WMCO builds to match that change.
=> [build] Move to Go 1.16

hack/common.sh
This PR updates the operator version to 1.0.4 for next 4.6 release.
=> Prep for 1.0.4 release

Makefile, docs/HACKING.md, hack/run-ci-e2e-test.sh
- Given we don't want to run the upgrade tests on all providers, introduce a `-t` option to run-ci-e2e-test.sh that can be used to  specify the test. The allowed options are:
- `all` all the tests are run
- `basic` creation, network and deletion tests are run
- `upgrade` creation, upgrade, reconfiguration and deletion tests are run
- Remove stale `-k` option from the script
- Add new `run-ci-e2e-upgrade-test` Makefile endpoint which will be used  in the new upgrade CI job. Next step would be to add the new CI job that uses this new endpoint. At which point we will change the `run-ci-e2e-test` endpoint to only run the `basic` tests.
=> [hack] Allow specifying tests

test/e2e/metrics_test.go, test/e2e/wmco_test.go
When the upgrade test is launched as a separate job, https://github.com/openshift/release/pull/17227, the monitoring label does not get applied to the operator namespace. Handle that difference by explicitly applying the label.
=> [test] Explicitly apply monitoring label

controllers/windowsmachine_controller.go
This PR changes the isValidMachine() function to:
* Stop checking the kind of the object passed to it
* Properly log errors
=> Properly handle Machine validity checks

test/e2e/metrics_test.go, test/e2e/wmco_test.go
While #372 ensured that the `openshift.io/cluster-monitoring` is applied, that was not sufficient as WMCO is already running at that point and assumes monitoring is not enabled. Work around this by restarting WMCO after the label is applied.
This is needed for https://github.com/openshift/release/pull/17227/.
=> [test] Restart WMCO after monitoring label is applied

Makefile, test/e2e/reconfigure_test.go, test/e2e/upgrade_test.go
Remove the platform type checks for the upgrade and reconfiguration tests as the upgrade test is configured to only run on AWS. This allows us to run the upgrade tests locally against other platforms.
=> [test] Only run "basic" tests for *-e2e-operator

docs/TROUBLESHOOTING.md
The purpose of this commit is to adjust
the Kubernetes node log file path to the
correct one since the previous file path
is no longer in use.
=> [docs] Fix K8s node log file path

test/e2e/network_test.go
Given we are seeing issues pulling `mcr.microsoft.com/windows/servercore:20H2`, switch to using `mcr.microsoft.com/windows/servercore:2009` which is already present on Azure VMs.
=> [test] Use servercore:2009 image

test/e2e/create_test.go
[Bug 1936556 - vSphere CI tcp no route to host in machine-controller](https://bugzilla.redhat.com/show_bug.cgi?id=1936556) is increasing the time required for Machines to reach the required phase. Increase the wait time in waitForWindowsMachines() to work around this.
=> [test] Increase Machine wait time for vSphere

test/e2e/create_test.go, test/e2e/delete_test.go
This PR introduces a wait time for the machines to be deleted after deleteMachineSet() has been called in deletionTestSuite()
to make sure we are proceeding to test prometheus endpoints after all the machines have been deleted.
=> [test] Wait for machines to be deleted

controllers/windowsmachine_controller.go, controllers/windowsmachine_controller_test.go
Introduce `getInternalIPAddress()` that returns the internal IPv4 address of a Machine and use it in all the call sites. This has the good side effect of improving `isValidMachine()` as it was not doing all the necessary checks for IP addresses in Machine objects.
=> WINC-500: [wmco] Improve isValidMachine()

bundle/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, config/windows-exporter/prometheusRule.yaml, pkg/windows/windows.go
After the windows_exporter update to v0.16.0, it is possible to collect metric windows_cpu_info that is equivalent to node_cpu_info on the linux side. This PR enables cpu_info collector since it is not enabled by default.
Additionally renaming the metric windows_cpu_info to node_cpu_info  through the PrometheusRule object, this will help in retrieving the telemetry info for Windows nodes collected using the recording rule node_role_os_version_machine:cpu_capacity_cores:sum based on node_cpu_info.
=> Bug 1948037: Enable and rename metric windows_cpu_info

hack/common.sh
This PR explicitly applies the monitoring label to be used when deploying the operator through OLM using the hack/olm.sh script to enable metrics configuration. This change needs to be made to align with the changes made as part of OSDK migration.
Prior to the migration this label was applied through the deploy/namespace.yaml which has now been replaced by a section of config/manager/manager.yaml.
=> [hack] Explicitly apply monitoring label

.gitignore, Makefile
Removes the `generate` target as a prerequisite of the `build` target.
Generate runs `go get`, which cannot be done when building with CpaaS.
=> [build] Remove generate requirement from building

hack/common.sh
This commit updates the WMCO version to 2.0.1 for the next 4.7 release.
=> [release-4.7] Prep for 2.0.1 release

deploy/olm-catalog/windows-machine-config-operator/manifests/prometheusRule.yaml, pkg/windows/windows.go
After the windows_exporter update to v0.16.0, it is possible to collect metric windows_cpu_info that is equivalent to node_cpu_info on the linux side. This PR enables cpu_info collector since it is not enabled by default.
Additionally renaming the metric windows_cpu_info to node_cpu_info through the PrometheusRule object, this will help in retrieving the telemetry info for Windows nodes collected using the recording rule node_role_os_version_machine:cpu_capacity_cores:sum based on node_cpu_info.
=> [community-4.7] Enable and rename metric windows_cpu_info

Makefile, build/Dockerfile.base, build/Dockerfile.wmco, docs/HACKING.md, hack/olm.sh
Introduce Dockerfile.base that builds only the submodules. This base image is used in Dockerfile.wmco which results in only the WMCO being built.
Now that we have simplified the image build process normalize on using `$OPERATOR_IMAGE` as the source of truth for the WMCO image.
=> [build] Improve development build process

deploy/olm-catalog/windows-machine-config-operator/manifests/prometheusRule.yaml, pkg/windows/windows.go
After the windows_exporter update to v0.16.0, it is possible to collect metric windows_cpu_info that is equivalent to node_cpu_info on the linux side. This PR enables cpu_info collector since it is not enabled by default.
Additionally renaming the metric windows_cpu_info to node_cpu_info through the PrometheusRule object, this will help in retrieving the telemetry info for Windows nodes collected using the recording rule node_role_os_version_machine:cpu_capacity_cores:sum based on node_cpu_info.
=> Bug 1955319: Enable and rename metric windows_cpu_info

hack/common.sh
This PR align the usage of the WMCO_DEPLOY_NAMESPACE parameter
within the `hack/common.sh` script.
See: https://github.com/openshift/windows-machine-config-operator/pull/419#discussion_r621435105
=> [hack] refactor consistent use of parameter

hack/machineset.sh
Instead pick the latest 1809 image.
=> [hack] Stop hardcoding the AMI date in MachineSet generation

hack/machineset.sh
Correct typo in error message for `get_azure_ms()`
=> [hack] fixed typo in error message

README.md
This PR adds a README section documenting how to enable
autoscaling of Windows MachineSets managed by WMCO.
=> WINC-551: Cluster autoscaling with Windows machines

docs/TROUBLESHOOTING.md, docs/setup-hybrid-OVNKubernetes-cluster.md
Clarify that you cannot use Windows Server 2019 LTSC (1809) in a cluster configured with a custom VXLAN port.
=> [docs] Improve troubleshooting for 1809

CONTRIBUTION.md
This is so that CPaaS automation can pick this up and add the BZs to the release errata.
=> [docs] Indicate how to reference bug fix commits

.gitmodules
Update to https://github.com/openshift/kubernetes/commit/f9da31467588898db8a6389b97cd78457950129c
Fixes BZ#1939968 by pulling in https://github.com/openshift/kubernetes/pull/762
=> Bug 1939968: [submodule][kube-proxy] Update to f9da3146758

test/e2e/network_test.go
createWindowsServerDeployment() is used to create the deployment for east-west and north-south networking tests. east-west tests require pods to be placed on particular nodes while this does not matter for
north-south networking tests. Moreover not spreading pods across nodes prevents us from testing scenarios like [BZ 1905950](https://bugzilla.redhat.com/show_bug.cgi?id=1905950).
=> [test] Set replica count based on affinity

hack/common.sh
This PR updates the operator version
to v1.0.5 for the next 4.6 release.
=> Prep for 1.0.5 release

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the WMCO version to v3.0.0 and updates the olm.SkipRange to '>=2.0.0 <3.0.0'  for the 4.8 operator release.
=> Prep for 3.0.0 release

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml
This PR adds a "system-cluster-critical" priority tag to the operator so
that WMCO pods are not preempted by user workloads. This priority still allows
operator pods to be OOMKilled as WMCO should come up fine if it gets
rescheduled on another node.
Bundle change was generated using `make bundle`.
=> WINC-600: Add system-cluster-critical priority class

config/manager/manager.yaml
This PR removes the duplicate 'serviceAccountName' field
from the WMCO Deployment resource config.
=> [deploy] Remove duplicate field in deployment spec

hack/run-ci-e2e-test.sh
This PR extends the usage of the WMCO_DEPLOY_NAMESPACE constant introduced
in the `hack/common.sh` source script.
See commit https://github.com/openshift/windows-machine-config-operator/pull/438/commits/50be4edf3b4c7b49602e779d3e83b5d15cc43413
=> [hack] Extend consistent use of namespace constant

.gitmodules
Update to https://github.com/openshift/kubernetes/commit/eb86af7b4ac9f067593f94bfe525e8b7f6d5d01f
Fixes BZ#1971745
=> Bug 1971745: [submodule][kubelet] Update to eb86af7b4ac

test/e2e/network_test.go
This PR enables pods logs to be printed out
to the ARTIFACT_DIR so that specific pod 
network communication errors can be identified.
=> WINC-569: Add logs to network tests

test/e2e/create_test.go, test/e2e/upgrade_test.go
This PR aims to reduce the amount of time our end-to-end tests take to complete by dropping a redundant case from the upgrade tests and spreading platform-agnostic tests across cloud providers in CI.
=> WINC-614: Remove test overlap in upgrade suite

README.md, docs/HACKING.md, docs/wmco-prerequisites.md
This was done to provide a clear pre-requisite list in ourGitHub docs 
so that common WMCO setup errors can be prevented.
=> WINC-628: [docs] Add pre-reqs to README

controllers/configmap_controller_test.go
Random ordering of elements caused this unit test to fail occasionally.
ElementsMatch should be used instead so that the order does not matter.
Co-authored-by: Aravindh Puthiyaparambil <aravindh@redhat.com>
=> [test] Fix flakey configmap unit test

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the required OCP platform to 4.8 in the pre-requisites section of the CSV for the 4.8 release.
=> [release-4.8] [bundle] Update pre-requisite to OCP 4.8

controllers/configmap_controller.go, controllers/controllers.go, controllers/controllers_test.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/metrics_test.go, test/e2e/network_test.go, test/e2e/validation_test.go
This commit enables the removal of BYOH nodes from a cluster. A new
username annotation has been added to BYOH nodes in order to help
accomplish this.
Instances that are removed from the windows-instances ConfigMap will be
cordoned, drained, and deconfigured, returning them to the state they
were in before WMCO configured them.
=> WINC-582: [wmco] BYOH node removal

hack/common.sh
This PR updates the WMCO version to
v2.0.2 for the next 4.7 release.
=> [release-4.7] Prep for 2.0.2 release

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
This commit renames the IP() method of the Windows interface to
Address(). This should be done as either an ip or dns address can be
used, and calling it IP is a misnomer.
=> [wmco] Rename IP() to Address()

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, pkg/nodeconfig/nodeconfig.go, test/e2e/reconfigure_test.go
This PR consists of three commits:
* BYOH Nodes are being watched by the ConfigMap controller
* Nodes are annotated earlier in the configuration process so that they can be identified as BYOH or Machine nodes.
* Partially configured BYOH nodes will be configured. This enables the reconfiguration tests, which also tests that BYOH node watching is working.
=> [wmco] WINC-631: BYOH controller is able to react to changes in Node objects

bundle.Dockerfile
This PR updates the label version of the index image in the bundle.Dockerfile to 4.8 for release-4.8.
=> [release-4.8] [Dockerfile] Set index image label version to 4.8

test/e2e/providers/vsphere/vsphere.go
This commit updates the name of the golden image template used
in the e2e tests for vSphere. In order to prevent the templates 
to be pruned by the automatic cleanup process that takes place
in the vSphere platform the following conventions are adopted:
- all golden image template names starts with the `vm` prefix
- the windows-golden-images folder holds all the templates
- the windows-golden-images folder is excluded from the
automatic cleanup process. 
See https://issues.redhat.com/browse/DPP-7909
=> [e2e] Update golden image template for vSphere

bundle.Dockerfile
This PR updates the label version of the index image in the
bundle.Dockerfile to v4.9 in prep for release-4.9.
=> [Dockerfile] Set index image label version to 4.9

controllers/configmap_controller.go, controllers/configmap_controller_test.go
isValidConfigMap() checks if the given configMap is the `windows-instances` ConfigMap. This is used when filtering objects in the ConfigMap predicate.
=> WINC-612: [wmco] Introduce isValidConfigMap()

test/e2e/providers/vsphere/vsphere.go
This commit updates the name of the golden image template used
in the e2e tests for vSphere. In order to prevent the templates
to be pruned by the automatic cleanup process that takes place
in the vSphere platform the following conventions are adopted:
- all golden image template names starts with the `vm` prefix
- the windows-golden-images folder holds all the templates
- the windows-golden-images folder is excluded from the
automatic cleanup process.
See https://issues.redhat.com/browse/DPP-7909
=> [community-4.7] [e2e] Update golden image template for vSphere

bundle/manifests/windows-machine-config-operator_v1_serviceaccount.yaml, config/rbac/kustomization.yaml, config/rbac/service_account.yaml
This PR removes the serviceaccount.yaml file from bundle manifests since it contains the same information as
held by the CSV spec for SA generation.
This causes an issue with the operator during upgrade with the CSV requirements not being met and the message: "Service account is owned by another ClusterServiceVersion"
=> Bug 1982991: Remove Service account file from bundle manifests

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml
Changes the label 'control-plane: controller-manager', to
'name: windows-machine-config-operator'. This change happened as part of
the switch to the kubebuilder style repo, and has broken the WMCO pod
log collection in the e2e tests.
The monitor.yaml and auth_proxy_service.yaml are not included in the
bundle that we ship, but changing them in order to be consistent.
=> [deploy] Fix e2e log collection by switching back to more descriptive WMCO label

controllers/configmap_controller.go, controllers/configmap_controller_test.go, controllers/controllers.go, controllers/windowsmachine_controller.go, hack/unit.sh, pkg/instances/instances.go, pkg/instances/instances_test.go, pkg/metadata/metadata.go, pkg/nodeconfig/nodeconfig.go, test/e2e/create_test.go, test/e2e/reconfigure_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
Deconfigures and then configures any instances associated with a node
that has an mismatched WMCO version annotation.
=> WINC-580: Upgrade BYOH Nodes configured by previous WMCO versions

README.md, controllers/configmap_controller.go
If the admin deletes the `windows-instances` ConfigMap, the operation is viewed as a call to deconfigure all BYOH Windows instances. This PR handles that scenario.
=> WINC-612: [wmco] Handle deletion of windows-instances

controllers/secret_controller.go, pkg/annotations/annotations.go, pkg/annotations/annotations_test.go, pkg/metrics/metrics.go, pkg/nodeconfig/nodeconfig.go, pkg/patch/patch.go, test/e2e/reconfigure_test.go
This PR opts to use a JSON Patch instead of Update when adding/removing 
annotations to node objects. Update calls can result in failures as the node 
object  can be a stale reference (if some other entity changes the Node 
while WMCO is configuring for example). A patch is best used when 
modifying parts of a resource, which fits the node annotation use case;
this is why a patch was favored over a Get -> Update loop.
This PR also introduces new packages to construct and format Patch data for arbitrary k8s resources.
=> [wmco] Patch node when adding annotations

deploy/service_account.yaml
This PR removes the serviceaccount.yaml file from bundle manifests since it contains the same information as
held by the CSV spec for SA generation.
This causes an issue with the operator during upgrade with the CSV requirements not being met and the message
"Service account is owned by another ClusterServiceVersion"
=> [release-4.7] Bug 1985349: Remove SA file from bundle manifests

hack/common.sh
This PR updates the WMCO version to v2.0.3 for the next 4.7 release.
=> [release-4.7] Prep for 2.0.3 release

controllers/configmap_controller.go, controllers/controllers.go, controllers/secret_controller.go, test/e2e/create_test.go
Changes the BYOH annotation to a label to allow for easier selection of
BYOH nodes.
=> WINC-649: [wmco] Change BYOH annotation to a label

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
- Change ConfigMap controller log name to "configmap" to be consistent  with other controllers
- Change the Windows Machine controller log name to reduce stuttering
- Add logs when deconfiguring a BYOH instance
- Add events for BYOH instances
=> WINC-643: Normalize BYOH and Machine logs and events

README.md
Add network name requirements in the machineSet example
for vSphere, since must match the network name where other
Linux workers are in the cluster.
=> [docs] Update vSphere machineSet requirement

test/e2e/providers/vsphere/vsphere.go
The vSphere Template is introduced as the standard golden image distribution
format, as recommended by SMEs.
Follow-up to df8b7de
=> WINC-610: Introduce vSphere Template as golden image

pkg/windows/windows.go, test/e2e/delete_test.go, test/e2e/reconfigure_test.go, test/e2e/validation_test.go
The hybrid-overlay process creates HNS networks when it runs on a node. This PR removes the HNS networks created by
previous configuration on the node and adds a test case in the deletion test suite to test the removal.
=> WINC-648: [wmco] Remove HNS networks in BYOH deconfiguration

controllers/controllers.go
This PR edits the windowsNodePredicate used in the configmap controller to capture delete events for nodes which have OS label Windows and BYOH label set.
Fixes BZ#1992428
=> Bug 1992428: [wmco] Capture delete event for BYOH Windows nodes

controllers/windowsmachine_controller.go
Previously, Prometheus configuration was only triggered upon
a machine in `Deleting` phase, the problem is that the event
could be missed leaving the metrics endpoints with an invalid
configuration.
Watching for machine not found errors, and updating the metrics
endpoints helps to maintain the metrics endpoint with valid
configuration.
Fixes BZ#1991739
=> Bug 1991739: [wmco] Fix metrics endpoint on machine not found

pkg/windows/windows.go
This PR fixes the HNSCommand suffix in the Run() method to avoid printing out the error logging message for PS timeouts when deleting HNS networks.
This PR also fixes the flake on Azure platform with the failure to remove all HNS networks.
=> [wmco] Fix issues with removing HNS networks

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the WMCO version to v3.1.0 and for the next 4.8 operator release.
=> Prep for 3.1.0 release

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the WMCO version to v3.1.0 and for the next 4.8 operator release.
=> [release-4.8] Prep for 3.1.0 release

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go
- Simplify the check for a Windows node
- Update all controllers to handle generic events
=> WINC-645: [controllers] Handle generic events

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, pkg/instance/instance.go, pkg/windows/windows.go, pkg/wiparser/wiparser.go, test/e2e/create_test.go, test/e2e/validation_test.go
Sets the WMCB node-ip arg when platform == 'none'. This results in the
node object for the configured node using the given IP. If the actual IP
of the node changes, the ConfigMap must be kept up to date in order for
the node status to not become stale.
Fixes BZ#1991282
=> Bug 1991282: [wmco] Set WMCB node-ip arg appropriately for BYOH

pkg/nodeconfig/nodeconfig.go, pkg/nodeutil/nodeutil.go, pkg/nodeutil/nodeutil_test.go, pkg/windows/windows.go, pkg/wiparser/wiparser.go
This PR performs checks on a Windows instance's network address.
Instead of using the raw address, it is checked to ensure it is an IPv4
address or if it resolves via DNS lookup. This is needed in case an instance's
DNS address does not match its hostname.
Fixes BZ#1995684
=> Bug 1995684: Validate and perform DNS lookup on Windows instance network address

.gitmodules
* [submodule][windows-machine-config-bootstrapper] Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/817a4013a0d84800669c360533436fb2c0fe7d49
* [submodule][kubelet] Update to https://github.com/openshift/kubernetes/commit/98073871f173baaa04dc2bafab50effd62c308a6
* [submodule][ovn-kubernetes] Update to https://github.com/openshift/ovn-kubernetes/commit/5ee76f3d1635658339433f9937714b3e44546591
This PR points the WMCB submodule at the correct branch, community-4.8
=> [community-4.8][submodule] Update

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/configmap_controller.go, pkg/nodeconfig/nodeconfig.go, test/e2e/network_test.go, test/e2e/upgrade_test.go
Add create permission to specific pods/eviction resource in the ConfigMap
Controller and config role.yaml.
Bundle manifests generated with:
`make bundle`
=> Bug 1996615: Add pods eviction permission and logging for drainer helper

pkg/windows/windows.go
This PR removes "--feature-gates=IPv6DualStack=false" from the kube-proxy service args as kubernetes/kubernetes#100966
has been fixed by openshift/kubernetes/commit@d5d9327351de99e6068f62efb388a6ede38d944e
=> WINC-644: [wmco] Remove "--feature-gates=IPv6DualStack=false"

docs/byoh-instance-pre-requisites.md
If the default shell is not powershell, the following bug will be hit:
https://bugzilla.redhat.com/show_bug.cgi?id=2000772
This can be reverted when the above bug is fixed.
=> [docs] SSH shell pre-requisite

hack/run-ci-e2e-test.sh
IMAGE_FORMAT is deprecated from the release repo
in favor of using dependencies.
This commit removes the usage of the deprecated
IMAGE_FORMAT env variable.
=> [hack] Stop using IMAGE_FORMAT in run-ci-e2e-test

controllers/certificatesigningrequests_controller.go
When adding a CSR to the queue, we filter based on whether the CSR is already approved. We don't however check this again during the reconciliation loop.
In certain scenarios, we can end up in a situation where the CSR is approved externally before we get to it. In this case, the approval call for to the API server fails as we are duplicating the approved condition. When this API call fails, this causes the CSR to requeue and we end up with the CSR in a constant loop of attempting to be approved, but unable for it to actually be approved.
To prevent this, before we reconcile any CSR, we should check that it hasn't already been approved out of band.
This should mirror the same being added in https://github.com/openshift/cluster-machine-approver/pull/129
=> Bug 2002961: Prevent error loop when a CSR is queued and then approved externally

test/e2e/providers/vsphere/vsphere.go
The intent of this PR is to derive the Workspace for machinesets created during testing based on the compute machineset provisioned by the cluster at installation.  The reason for this change is that a vCenter in IBM Cloud is being also used to run CI jobs from a shared lease pool to increase test coverage in some key configurations.   Additionally, the vmTemplate can now be optionally defined as an environment variable in the [e2e test script](https://github.com/openshift/release/blob/master/ci-operator/step-registry/windows/e2e/operator/test/windows-e2e-operator-test-commands.sh).
=> [vsphere] create machineset spec based on machineset spec created at install time

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR updates the WMCO version to v4.0.0 and updates the olm.SkipRange to '>=3.0.0 <4.0.0' for the 4.9 operator release.
=> Prep for 4.0.0 release

docs/byoh-instance-pre-requisites.md
This PR adds a bullet point stating address used in the configMap must have a PTR record resolving to the instance host name.
=> [doc] Document pre-requsite for PTR records

.gitmodules, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/lint-gofmt.sh
- [submodules] Add containerd
- [submodules] Add hcsshim
- [build] Add containerd components
=> WINC-672: [build] Add containerd components

docs/HACKING.md
This fix addresses two missing points in the document.
1. Add container registry verification as part of Pre-requisites
2. Add Updating Git submodules as part of Pre-requisites
=> [docs] update HACKING.md with missing pre-requisites

docs/vsphere_ci/build.json
Update the VMware Tools ISO image with newer version in the build.json script, used by Packer to create the golden image template.
[See VMware documentation for release notes](https://docs.vmware.com/en/VMware-Tools/11.3/rn/VMware-Tools-1130-Release-Notes.html)
=> [docs][vsphere-ci] Update VMware Tools to v11.3.0

pkg/windows/service.go, pkg/windows/windows.go
This commit adds the new dependencies field to the service struct. This
is preferrable to having to add the `depend` field in each service's
arguments, as depend is not part of the binPath.
=> [windows] Add dependencies to Windows service struct

test/e2e/network_test.go, test/e2e/upgrade_test.go
This commit revert the node affinity logic introduced, in order to keep
the e2e-upgrade test low in complexity.
To ensure the presence of a running workload in a BYOH node, if any, we trust
the kube-scheduler placement algorithm, that balance the number of workloads
across the available nodes that match taints and selectors.
The number of workloads is set to 3, representing the total number of
nodes (one BYOH and one WM) + 1, assuring the eviction of at least 1 pod from
the BYOH node during the de-configuration process.
=> [e2e] Rollback node affinity for BYOH label

pkg/nodeconfig/nodeconfig.go
Bump logging level to INFO in the OutWriter wrapper to enable
the drainerHelper to print information regarding the eviction/deletion
of pods.
Follow-up to https://github.com/openshift/windows-machine-config-operator/commit/c11fad50f01344bec63a61f7a4e56602c60f71d7
=> [wmco] Enable pods eviction logging

controllers/windowsmachine_controller.go
Adjust machine predicate to react upon Delete events for machines
that include the Windows label.
The previously proposed fix, is too restrictive since it includes the
validation of the machine object (r.isValidMachine(e.Object)), meaning
a) machine have a valid phase, and
b) machine have a valid IP address
There is an edge case, especially in vSphere, where the machine' IP addresses
are removed while the machine is still in Deleting phase. So, the event is
filtered out and WMCO is not able to update the metrics endpoint.
Removing the validation of the machine object from the filtering, entertains
the edge case.
Fixes BZ#2008601
Follow-up to https://github.com/openshift/windows-machine-config-operator/pull/571/commits/2a4484b755d334e06c4616ec9f4ad8bb61eadec9
=> Bug 2008601: Fix delete event subscription

controllers/windowsmachine_controller.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/vsphere/vsphere.go
This PR combines a few backports that have inter-dependencies.
While backporting the updates for the golden image template in vSphere, [Bug 1995340](https://bugzilla.redhat.com/show_bug.cgi?id=1995340) was identified and resolved. 
[Bug 2008601 ](https://bugzilla.redhat.com/show_bug.cgi?id=2008601) is a follow-up fix targeting 4.10, that is manually cherry-picked.
The support for IBMCloud is a dependency, and also got manually cherry-picked.
=> [release-4.7] Bug 1995340: Fix metrics endpoint + Update golden image + IBM cluster support

controllers/windowsmachine_controller.go
This PR does not react/re-queue when a Node associated with a Windows machine
cannot be found (i.e. is deleted), leaving the previously configured Machine
in the `Running` state. 
This approach was chosen rather than deleting &
re-creating the unassociated Machine as optimizing machine management is not in
scope of WMCO responsibilities. In addition, not reacting is in line with the 
current functionality of Linux Machines, standardizing OpenShift functionality.
Also, the Machine cannot be reconfigured to create a new Node object since
the machine-api's nodelink_controller will not update any Machine's Node
reference, neither after deleting a Node nor after reconfiguring a Machine.
Fixes BZ#1992841
=> Bug 1992841: Do not react to Windows Node deletion

.gitmodules
Github deprecated unauthenticated git:// access.
See https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Replace git with http URL in .gitmodules

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Ran `make bundle` after changing the Makefile and `config/` files.
=> Prep for 5.0.0 release

pkg/instance/instance.go, pkg/netutil/netutil.go, pkg/netutil/netutil_test.go, pkg/wiparser/wiparser.go, pkg/wiparser/wiparser_test.go
This commit fixes an issue where the DNS address used to configure a
BYOH node is not present in the addresses of the Node object.
A unit test case had to be removed, as the case was not possible, with
two nodes having the same resolved address.
Fixes BZ#2005360
=> Bug 2005360:  Lookup nodes via IPv4 address

README.md, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR standardizes the name of the user data secret in the sample
MachineSets in the README and in the CSV. The name is now consistent with
the user data name constant we use in the source code and in the sample
MachineSets for other cloud providers: `windows-user-data`
=> [docs] Standardize name of user data secret

README.md
Avoid using "dns.com" which is owned by an actual company;  "example.com" is more appropriate for use here.
=> Use more appropriate sample domain name for docs

bundle.Dockerfile
This PR updates the index image label version in the bundle.Dockerfile to v4.10, complaint with the version operator will be available in.
=> [Dockerfile] Update index image version label to 4.10

docs/projected-volume.md
...from https://github.com/kubernetes/website/pull/30366/
=> [docs] Update SAM verbiage in project volume doc

go.mod, go.sum, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/network_test.go, vendor/github.com/apparentlymart/go-cidr/LICENSE, vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go, vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go, vendor/modules.txt
In this PR a pre-work commit is introduced to avoid future code duplication by
generalizing the `createWindowsServerJob` function, accepting just a PowerShell 
command string instead of the generic command array.
The Cluster DNS is generated from the serviceNetwork subnet and passed
to the wmcb.exe initialize-kubelet command, to configure the kubelet
with a specific DNS server IP which will be used by all Windows containers.
Added e2e test case to ensure DNS resolution works properly inside the
Windows container.
Closes #575
=> Bug 1994859: Get and pass Cluster DNS to wmcb.exe

hack/run-ci-e2e-test.sh
Removes stale code that was previously used to run the e2e tests.
Current implementation uses `go test` to run the tests, so the old
method is no longer needed.
=> [hack] Remove stale OSDK test code

.gitmodules
Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/d656e5e5d9ac5cab824c74b8578d9740846803cc
=> [community-4.9][submodule][windows-machine-config-bootstrapper] Update to d656e5e

pkg/windows/windows.go
This commit replaces the inline OVNKubernetesHybridOverlayNetwork text value
with the existing constant OVNKubeOverlayNetwork.
=> [windows] Use OVNKubeOverlayNetwork constant

controllers/controllers.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
This commit passes platform typy to WCMB using the new `--platform-type` parameter.
Depending on the platform, WCMB may perform additional actions to configure the nodes. For instance, on AWS it overrides default hostname for kubelet using values from metadata server.
=> [OCPCLOUD-1247] Pass platform type to WMCB 

.gitmodules, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/lint-gofmt.sh
This is a manual revert of #701 as we have decided not to ship containerd with WMCO 4.y.z
=> [release-4.9] Revert containerd addition

controllers/certificatesigningrequests_controller.go, pkg/csr/csr.go, test/e2e/create_test.go, test/e2e/validation_test.go
This PR fixes the group value when adding a CVO override for 
the cluster-machine-approver. Overrides were not taking effect 
due to an invalid value ([CVO docs](https://github.com/openshift/enhancements/blob/f97876821d3bb506d28fee565271d3bebbbc682c/dev-guide/cluster-version-operator/dev/clusterversion.md#setting-objects-unmanaged) are incorrect).This is required for testing 
BYOH CSR approval feature so that CSRs associated with 
BYOH instances are not approved by Cluster Machine Approver.
The PR also takes the recommended k8s approach to Updating CSRs.
If an update fails due to a conflict, we want to retrieve an updated
reference to the object before trying again to apply our own changes to it.
Otherwise, Update calls can result in failures as the CSR object can
become a stale reference …
=> Bug 2032048: Fix CVO override and retry Update of CSRs approval status

test/e2e/create_test.go
This PR refines one of the steps needed to test BYOH node CSR approval.
1. uses k8s objects + WMCO's `patch` package to generate the
`cluster-machine-approver` CVO override request data, instead of
inputting a pre-formatted string directly
2. checks for error when patching the ClusterVersion resource
=> [e2e] Improve CVO override creation and patching

hack/common.sh
This commit updates the operator version
to v1.0.6 for the next 4.6 release.
=> Prep for 1.0.6 release

hack/common.sh
This commit updates the WMCO version to
v2.0.4 for the next 4.7 release.
=> Prep for 2.0.4 release

test/e2e/create_test.go, test/e2e/validation_test.go
This PR scales down the CVO when testing WMCO's CSR approval functionality.
This is needed to prevent CVO from scaling the cluster-machine-operator
deployment back up, something we scale down ourselves so it does not try to
auto-approve CSRs for Windows BYOH nodes (in CI, our BYOH nodes are
Machine-backed but without the Windows version annotation for ease of testing).
We are seeing an issue where the previous solution, adding a CVO override to
make the cluster-machine-operator deployment unmanaged, is no longer sufficient.
This PR also refactors a method used to scale deployments in the e2e tests.
=> [e2e] Scale down CVO when testing BYOH CSRs

config/rbac/kustomization.yaml, config/rbac/service_account.yaml
When I deploy the operator with `make deploy`, I get next error from WMCO deployment:
```txt
error looking up service account openshift-windows-machine-config-operator/windows-machine-config-operator:
serviceaccount "windows-machine-config-operator" not found'
```
This commit adds a manifest for the missing service account. After that everything installs well.
=> [config] Add ServiceAccount manifest

test/e2e/create_test.go, test/e2e/validation_test.go
This reverts commit 1521abca32c05a7f46f099980e7ef2c864982c62 from #869.
Not needed anymore as the CVO bug (https://bugzilla.redhat.com/show_bug.cgi?id=2042039)
that it worked around has been fixed with https://github.com/openshift/cluster-version-operator/pull/728.
=> Revert "[e2e] Scale down CVO when testing BYOH CSRs"

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, main.go, pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/nodeconfig/payload/payload.go, pkg/windows/windows.go, test/e2e/delete_test.go
This PR adds a flag through CSV args to specify the Windows host container runtime as docker or containerd. If the flag value is "containerd", the Containerd related files are transferred to the Windows VM.
This PR addresses both [WINC-617](https://issues.redhat.com/browse/WINC-617) and [WINC-694](https://issues.redhat.com/browse/WINC-694).
Ran
`make bundle`
=> WINC-617: Specify container runtime flag and transfer containerd files

test/e2e/network_test.go
This commit removes the DNS invalid URL test because it succeeds even if the request does not hit the DNS server.
Follow-up to https://github.com/openshift/windows-machine-config-operator/commit/c6092e2be3279651c8d4c57a9d48817f7cf07b78
=> [e2e] Remove DNS test for invalid URL

test/e2e/create_test.go
This commit modularizes the testBYOHConfiguration test, so that
it is easy to maintain and can be extended. This is a pre-work
to introduce support for platform=none.
=> WINC-607: [e2e] Modularize BYOH configuration test

docs/wmco-prerequisites.md
Windows server 2004 is no longer supported. Hence removing it
prerequisites document.
=> [docs] Remove Windows server 2004 from supported version

Makefile, docs/HACKING.md, docs/vsphere_ci/platform-none/README.md, docs/vsphere_ci/platform-none/create-ptr-records.sh, hack/common.sh, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/none/none.go
This PR adds support for the e2e tests to run in a platform-agnostic infrastructure (platform=none).
=> WINC-607: Add support for platform=none in e2e test suite

test/e2e/network_test.go
This test has 25% failure rate in CIs. [WINC-743](https://issues.redhat.com/browse/WINC-743) has been created to address
this issue. Until we address [WINC-743](https://issues.redhat.com/browse/WINC-743), this test has been temporarily
disabled.
=> [e2e] Disable Pod DNS Resolution Test

docs/vsphere-golden-image.md, docs/vsphere_ci/build.json
This is in order for golden images built using our docs as a guide have
the proper VM hardware version in vSphere environments.
=> WINC-726: Add VM hardware version in Packer config

test/e2e/create_test.go, test/e2e/validation_test.go
Manual backport of ae32e4cebdf93c9292ae9720cdbde1047a7b6e24
=> [community-4.9][e2e] Refactor scaleDeployment method

test/e2e/create_test.go, test/e2e/validation_test.go
Manual backport of ae32e4cebdf93c9292ae9720cdbde1047a7b6e24
=> [community-4.8][e2e] Refactor scaleDeployment method

test/e2e/create_test.go, test/e2e/validation_test.go
Manual backport of ae32e4cebdf93c9292ae9720cdbde1047a7b6e24
=> [release-4.8][e2e] Refactor scaleDeployment method

build/Dockerfile.ci
This PR Install `jq` in CI Dockerfile. `jq`requirement was introduced in [c1fb113](https://github.com/openshift/windows-machine-config-operator/pull/858/commits/c1fb113a4043cc0cb98ef1cfdf568d21010f095f#diff-f6f13ef4e3c83b5e22c436df5b1a4b24fd2c22a80d25855668b41828bcc05e12R194).
=> WINC-607: [build] Install jq in CI Dockerfile

controllers/certificatesigningrequests_controller.go, pkg/csr/csr.go
This PR consolidates the retry logic introduced in 223c8b95202a17b7072743bea44010ce3f5700c9 using [RetryOnConflict](https://github.com/kubernetes/client-go/blob/v0.23.3/util/retry/util.go#L103).
=> [csr_controller] RetryOnConflict in CSR approvals

build/Dockerfile.ci, test/e2e/delete_test.go, test/e2e/network_test.go
Follow-up to https://github.com/openshift/windows-machine-config-operator/pull/858
=> WINC-607: Add support for platform=none in e2e test suite (Cont.)

test/e2e/logs_test.go
This PR drops the requirement of there being .ERROR and .WARNING
logs for kube-proxy. These are only present if there was logging at
those log levels
=> Stop requiring kube-proxy ERROR and WARNING logs

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, pkg/cluster/config.go, pkg/cluster/config_test.go
This commit updates the csv and WMCO code to require kubernetes 1.23 in
order to be installed and ran.
=> WINC-723: Set v1.23 as the required k8s version

test/e2e/create_test.go, test/e2e/validation_test.go
Manual backport of ae32e4cebdf93c9292ae9720cdbde1047a7b6e24
=> [release-4.9][e2e] Refactor scaleDeployment method

controllers/certificatesigningrequests_controller.go, pkg/csr/csr.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/894 to fix vendoring.
=> [community-4.8]  [csr_controller] RetryOnConflict in CSR approvals

hack/machineset.sh, pkg/windows/windows.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR removes SAC Windows Server 2004 (EOL as of 2021-12-14) from our CI and docs,
and replaces it with LTSC Windows Server 2022 
(support announced here kubernetes/kubernetes#104438, EOL is 2026-10-13).
It also improves documentation around building the vSphere golden image using Packer.
Windows Server 2022 is tested in the vSphere environments. 
The golden image is built with a private networking OS fix supplied my Microsoft, 
so official support is on hold until they release the patch publicly.
Support on AWS and Azure is not included in this work.
=> WINC-602: [wmco] Support Windows Server 2022

Makefile, docs/HACKING.md, docs/vsphere_ci/platform-none/README.md, docs/vsphere_ci/platform-none/create-ptr-records.sh, hack/common.sh, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/none/none.go
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/858 to fix the location of openshift/mapi api used in all branches before release-4.10.
=> [release-4.8] WINC-607: Add support for platform=none in e2e test suite

build/Dockerfile.ci
This PR removes the kubectl client from the Dockerfile.ci.
This is in-prep for [WINC-520](https://issues.redhat.com/browse/WINC-520)
=> [build][ci] Remove unused kubectl client

.gitmodules
Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/53f5a1b252b6fa37d178712d3fada99cbfc010b1
=> [submodule][windows-machine-config-bootstrapper] Update to 53f5a1b

test/e2e/main_test.go
This PR fixes an old bug that occurs only when running WMCO e2e tests locally.
Since the test files are not within the top level WMCO directory and instead
nested in the `test/e2e` directories, this must be reflected when referencing
the WMCO binary. Otherwise, things like [getting the operator version](https://github.com/openshift/windows-machine-config-operator/blob/master/test/e2e/validation_test.go#L195-L196) will fail.
=> [e2e] Fix WMCO binary path

build/build.sh, cmd/operator/main.go, controllers/configmap_controller.go, controllers/configmap_controller_test.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go, test/e2e/create_test.go, test/e2e/validation_test.go
This PR creates the data representation of a service ConfigMap which provides WICD with the specifications for each Windows service that must be created on a Windows instance.
WMCO will then create and maintain a service ConfigMap which provides WICD with the specifications for each Windows service that must be created on a Windows instance. To begin with maintain a no-op ConfigMap, and in follow-up PRs we will move services one by one to be included in the ConfigMap.
- Services ConfigMap is a singleton within the namespace
- The ConfigMap is immutable
- If the ConfigMap is deleted it is recreated
- If a ConfigMap with incorrect values is found, WMCO will delete and recreate it with the proper values
- this applies both on operator start and during reconciling
- The Services ConfigMap …
=> WINC-715: WMCO creates and maintains Windows services ConfigMap

hack/common.sh
This commit updates the WMCO version to
v2.0.5 for the next 4.7 release.
=> Prep for 2.0.5 release

Makefile, hack/wicd-unit.sh
This commit adds a Make target for unit testing WICD. The purpose of
this is to validate that the WICD unit release job is fufilling all of
its requirements. Once both this stub and the release job are created,
this stub can be expanded to actually perform the tests required of it.
=> WINC-730: Add WICD unit test stub

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This PR adds a subscription annotation to our CSV to prepare for the new
gating validation being added by CVP. We will be unable to release without
it starting in April.
=> WINC-797: Add subscription annotation to CSV

controllers/windowsmachine_controller.go, test/e2e/create_test.go
This PR ensures the Username annotation is present in nodes configured
by the machine controller. Similar to BYOH nodes, the Username annotation
contains the encrypted value of the username used to SSH into the Windows
instance.
=> WINC-687: Add Username annotation for all Windows nodes

go.mod, hack/wicd-unit.sh, pkg/winsvc/winsvc.go, pkg/winsvc/winsvc_test.go, vendor/golang.org/x/sys/windows/svc/mgr/config.go, vendor/golang.org/x/sys/windows/svc/mgr/mgr.go, vendor/golang.org/x/sys/windows/svc/mgr/recovery.go, vendor/golang.org/x/sys/windows/svc/mgr/service.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/modules.txt
This commits adds interfaces to interact with the Windows service API.
A unit tested implementation has been added, along with unit tests to
ensure the proper behavior is being maintained. These interfaces should
be used when developing WICD, to enable large portions of the program to
be unit testable.
=> WINC-730: Windows service unit testable interfaces

controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
This PR adds the responsibility of removing outdated services ConfigMaps.
This will be particularly useful during upgrades -- the operator will clean up old 
services configs to ensure the source of truth is tied to the current operator version.
=> WINC-716: WMCO removes unneeded service ConfigMaps

README.md, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, cmd/operator/main.go, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, controllers/configmap_controller.go, controllers/controllers.go, controllers/windowsmachine_controller.go, docs/byoh-instance-pre-requisites.md, docs/vsphere-golden-image.md, pkg/csr/csr.go, pkg/internal/cni-conf-template.json, pkg/internal/containerd_conf.toml, pkg/nodeconfig/network.go, pkg/nodeconfig/network_test.go, pkg/nodeconfig/nodeconfig.go, pkg/nodeconfig/payload/payload.go, pkg/windows/windows.go, test/e2e/delete_test.go, test/e2e/logs_test.go
This PR makes the required CNI directory changes to the default containerd config file and stores it in the payload directory. It also creates the Windows containerd service using the config file along with the logging options and starts the service on the Windows node.
=> WINC-695: Configure containerd service and start it.

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/configmap_controller.go, controllers/secret_controller.go, controllers/windowsmachine_controller.go
This commit adjusts the RBAC permission for the nodes resource by
explicitly listing the required verbs.
Ran:
```
make bundle
```
=> WINC-799: [controllers] Tighten node permissions

README.md, docs/byoh-instance-pre-requisites.md
Update containerd pre requisites information. As WMCO installs and
manages containerd runtime, it is recommanded not to install by user.
=>  [docs] Update on containerd pre requisites

controllers/configmap_controller.go, controllers/configmap_controller_test.go
This PR updates the de-configuration workflow to ignore all
node addresses that fail to resolve a valid reverse lookup record
while looking for the associated Windows instance.
=> Bug 2070892: Skip node addresses without PTR record during instance de-configuration

test/e2e/clusterinfo/openshift.go
This PR adds the Cache initialization to the creation of the client
for the current OpenShift cluster, so that it is available during the
e2e test suite execution.
Follow-up to https://github.com/openshift/windows-machine-config-operator/commit/f57effd61af8859236067ea3c012f64dc21fff74
=> [e2e] Initialize OpenShift client's cache

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml
This commit aims to address [WINC-803](https://issues.redhat.com//browse/WINC-803) issue. We need to update
OpenShift Container Platform for Windows Containers subscription
as subscription info to be in sync with rlease and support docs.
=>  WINC-803: Update correct WMCO subscription info

controllers/configmap_controller.go, controllers/configmap_controller_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1045
=> [community-4.10] OCPBUGSM-42819: Skip node addresses without PTR record during instance de-configuration

controllers/configmap_controller.go, controllers/configmap_controller_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1045
=> [release-4.10] Bug 2081825: Skip node addresses without PTR record during instance de-configuration

README.md, docs/vsphere-golden-image.md, docs/vsphere-prerequisites.md, docs/vsphere_ci/README.md, docs/vsphere_ci/build.json, docs/vsphere_ci/scripts/autounattend.xml, docs/vsphere_ci/scripts/install-kb5012637.ps1, docs/wmco-prerequisites.md, hack/machineset.sh, test/e2e/providers/vsphere/vsphere.go
Manual backport of relevant commits from #1052:
- Use patched Windows Server 2022 image (with Docker) in vSphere CI
- Update golden image creation docs + scripts with steps to install OS patch
- Announce Windows Server 2022 Support for vSphere
=> WINC-755: Use patched Windows Server 2022 golden image in vSphere CI

docs/TROUBLESHOOTING.md, docs/machineset-aws.md
As containerd becomes the default runtime, Docker specific debug information should be removed from troubleshoot doc.This commit cleans up Docker runtime specific debug information.
=>  [docs] clean up Docker specific debug information

docs/vsphere-golden-image.md, docs/vsphere_ci/scripts/autounattend.xml, pkg/windows/windows.go
Windows Server 2022 onwards required Windows containers feature is not enabled by default. This PR adds
the ability to enable the Containers feature.
The additional step to do this from the golden image template has been reverted.
This work has been combined with the host name change method to minimize the number of times for VM reboot.
=> WINC-819: Enable required Windows feature for Containers

pkg/daemon/controller/controller.go, pkg/daemon/winsvc/winsvc.go, pkg/daemon/winsvc/winsvc_test.go
This commit corrects an issue where trying to start/stop an already started/stopped
Windows service would error out. The ServiceController now checks that
the service is not already in the correct state before telling Windows
to start/stop the service. Additionally, the mock service API used in
the unit tests has been altered to enact the behavior that the actual
service API has.
=> Correct Windows service start/stop behavior

controllers/configmap_controller.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go, test/e2e/validation_test.go
This commit adds the function GenerateWithData which allows for the
creation of service ConfigMaps with custom file and Windows service
specifications. This will be helpful for testing.
=> Enable generation of custom service CMs

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco, go.mod, go.sum, hack/lint-gofmt.sh
This commit is to build WMCO with golang 1.18, in line with the OCP bump
Also ran below command
`go mod edit -go=1.18 && go mod tidy && go mod vendor`.
This addresses https://issues.redhat.com/browse/WINC-821
=> WINC-821 : [build] Bump to go 1.18

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/897c494734c08abaaab7e7cf88ad594edf30fa34
Adapt to the WMCB submodule updates.
=> WINC-745: Clean up dockershim related flags

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/1ad93f2f015b1152885a0bc60edb9004e3147312
Adapt to the WMCB submodule updates.
=> [community-4.10] WINC-745: Clean up dockershim related flags

pkg/internal/containerd_conf.toml
This PR updates to https://github.com/openshift/containerd/commit/8100cdb4fa50c8c9888f2c3ad08f413e407fe567
and adds the image pull progress timeout feature argument to the Containerd config file.
=> WINC-828: Re-add image-pull-progress deadline feature

pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go
The controller-runtime manager is now being used to watch for Node
events relevant to the instance. When a relevant Node event occurs,
WICD will reconcile the Windows services specified within the cmData
Node annotation. In the future, instead of using this annotation, WICD
will use the actual contents of the appropriate services ConfigMap.
=> WINC-825: WICD reacts to Node events

pkg/internal/containerd_conf.toml
This PR updates to https://github.com/openshift/containerd/commit/8100cdb4fa50c8c9888f2c3ad08f413e407fe567
and adds the image pull progress timeout feature argument to the Containerd config file.
=> [community-4.10] WINC-828: Re-add image-pull-progress deadline feature

hack/machineset.sh, test/e2e/providers/aws/aws.go
This commit addresses CI failures on AWS platform.
the AMI which is created on May 25th is causing the issue, so
as a temp workaround we will be pointing to the older AMI image until
we figure out what is the real issue with the new AMI.
=> WINC-833: [e2e] unblock aws CI failure

hack/community/csv/description.md, hack/community/generate.sh, hack/community/readme.md
This PR automates the community release process through a bash
script that generates the community manifests and commits them to the
community-operator-prod repo.
[readme.md preview](https://github.com/alinaryan/windows-machine-config-operator/blob/WINC-700/hack/community/readme.md)
[description.md preview](https://github.com/alinaryan/windows-machine-config-operator/blob/WINC-700/hack/community/csv/description.md)
=> WINC-700: [hack] Introduce community manifests generation script

Makefile, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, docs/TROUBLESHOOTING.md, docs/setup-hybrid-OVNKubernetes-cluster.md, docs/vsphere-prerequisites.md
In order to properly control operator version availability in the OperatorHub 
catalog on different OCP versions, this ticket annotates our bundle image 
with a specific OCP version as per [OpenShift docs](https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-working-bundle-images.html#osdk-control-compat_osdk-working-bundle-images). This, in conjunction with
[setting the label in the bundle.Dockerfile](https://github.com/openshift/windows-machine-config-operator/blob/master/bundle.Dockerfile#L18), maintains WMCO major version 
availability is properly tied in 1:1 mapping with OCP versions.
This PR also bumps the WMCO and OCP version number in prep for the 6.0.0 release.
=> WINC-807: Add OpenShift versions annotation to bundle metadata and prep for 6.0.0 

cmd/daemon/controller.go, cmd/daemon/service.go, pkg/daemon/controller/controller.go
Adds the --windows-service flag to enable running as a Windows service.
Also adds the --log-dir flag so that logs can be accessible when running as a Windows service.
=> WINC-746: Enable running WICD as a Windows service

test/e2e/network_test.go
Security context checks by pod security admission have been made more
strict. RunAsNonRoot must be explicity made false within containers
using the ContainerAdministrator user.
=> Explicity run Windows webserver as root

docs/machineset-azure.md, docs/wmco-prerequisites.md, hack/machineset.sh, pkg/secrets/secrets.go, test/e2e/network_test.go, test/e2e/providers/azure/azure.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR adds support for WS 2022 for Azure platform by updating the dev hack script, e2e test and the documentation.
=> WINC-806: Add support for Windows Server 2022 in Azure

build/Dockerfile, build/Dockerfile.ci, build/Dockerfile.wmco, cmd/daemon/controller.go, cmd/operator/main.go, pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/nodeconfig/init.go, pkg/nodeconfig/nodeconfig.go, pkg/nodeconfig/payload/payload.go, pkg/windows/windows.go, test/e2e/logs_test.go
This PR includes changes required to run WICD on Windows nodes as part of the WMCO node configuration process.
* Allow WICD to use the windows services configmap by authenticating to the cluster with a ServiceAccount. This commit is being included within this PR as without the other commits in this PR there is no way to test this change in CI. 
* Build WICD and include it in the WMCO container image.
* Run WICD on Windows nodes.
=> WINC-731: Run WICD on Windows nodes

pkg/windows/windows.go
This PR fixes an issue where containerd configuration fails on instances
that do not have Windows Defender installed. WCMO now checks for Windows
Defender to be present before it creates an antivirus exclusion for containerd.
=> [windows] Check if Windows Defender is installed

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, pkg/cluster/config.go, pkg/cluster/config_test.go
This PR updates the csv and WMCO code to set the minimum required kubernetes to 1.24.
Commands ran:
`make bundle`
=> [manifests] Set v1.24 as the minimum required k8s version

bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/windows-instance-config-daemon_v1_serviceaccount.yaml, config/default/kustomization.yaml, config/wicd/kustomization.yaml, config/wicd/windows-instance-config-daemon-cluster-role-binding.yaml, config/wicd/windows-instance-config-daemon-cluster-role.yaml, config/wicd/windows-instance-config-daemon-role-binding.yaml, config/wicd/windows-instance-config-daemon-role.yaml, config/wicd/windows-instance-config-daemon-service-account.yaml, pkg/nodeconfig/nodeconfig.go
This PR adds a new WICD ServiceAccount with only the required permissions for WICD.
WICD will now use this SA instead of the WMCO SA.
=> WINC-731: Introduce WICD ServiceAccount

pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go
This PR adds cycle detection to the validation that occurs
on the services defined in `windows-services` ConfigMaps.
A dependency chain with cycles is considered invalid.
=> [servicescm] Service dependency cycle detection

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, cmd/operator/main.go, config/rbac/role.yaml, pkg/metrics/metrics.go
This code was added to transition from the old metrics resources to the
new resources. This is no longer relevant now that it is not possible
to upgrade from a version with the old resource type.
This was added in commit f7d52ed9f2567ad8abd81d798ece5f3acfbfcbd3
=> [metrics] Remove old cleanup code

README.md, docs/vsphere-golden-image.md, docs/vsphere-prerequisites.md, docs/vsphere_ci/README.md, docs/vsphere_ci/build.json, docs/vsphere_ci/scripts/autounattend.xml, docs/wmco-prerequisites.md, hack/machineset.sh, pkg/windows/windows.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR covers backporting Windows Server 2022 support on vSphere to the WMCO 4.x. This is relevant as version 20H2 support comes to an end in August 2022.
- WMCB submodule bump to pick up [release-4.9 pause image change](https://github.com/openshift/windows-machine-config-bootstrapper/pull/332)
- backporting support for newer Powershell version
- changing the golden image used in vSphere CI to Windows Server 2022 golden image with Docker
- Announce support through docs/support matrix changes
=> WINC-829: [release-4.9] Windows Server 2022 support on vSphere

README.md, docs/vsphere-golden-image.md, docs/vsphere-prerequisites.md, docs/vsphere_ci/README.md, docs/vsphere_ci/build.json, docs/vsphere_ci/scripts/autounattend.xml, docs/wmco-prerequisites.md, hack/machineset.sh, pkg/windows/windows.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR covers backporting Windows Server 2022 support on vSphere to the WMCO 3.x. This is relevant as version 20H2 support comes to an end in August 2022.
- WMCB submodule bump to pick up [release-4.8 pause image change](https://github.com/openshift/windows-machine-config-bootstrapper/pull/336)
- backporting support for newer Powershell version
- changing the golden image used in vSphere CI to Windows Server 2022 golden image with Docker
- Announce support through docs/support matrix changes
=> WINC-829: [release-4.8] Windows Server 2022 support on vSphere

pkg/metrics/metrics.go
WMCO deletes and recreates the windows-exporter endpoint upon each
operator start. This is resulting in an issue where the correct
endpoint subsets would be missing upon operator restart, stopping
metrics collection for Windows nodes.
This is being fixed by including the existing endpoint subsets in the
new endpoint created on restart.
A better approach would be to create a controller which maintains the
windows exporter endpoint. That is a larger change and should be done in
the future. This approach was taken as it is the smallest change which
can resolve this bug.
Fixes BZ#2107261
=> Bug 2107261: Maintain endpoint subsets on restart

pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go
This PR prevents a panic during service validation if a service that is not defined in
the services ConfigMap is listed as a dependency. Cycle detection now skips over
the unmanaged service and continues as normal for any other dependencies.
=> [servicescm] Handle unmanaged dependency services

docs/vsphere-golden-image.md, docs/wmco-prerequisites.md
Microsoft will drop support for OS version Windows Server 20H2 on 2022-08-09.
In line with this, WMCO will no longer support this version for vSphere worker nodes.
=> WINC-820: [docs] Remove Windows Server 20H2 support

docs/vsphere-golden-image.md, docs/wmco-prerequisites.md
Microsoft will drop support for Windows Server 20H2 on 2022-08-09.
In line with this, WMCO no longer supports this version, leaving
Windows Server 2022 LTSC as the recommended version for vSphere worker nodes.
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1145.
=> [release-4.10] WINC-820: [docs] Remove Windows Server 20H2 support

docs/vsphere-golden-image.md, docs/wmco-prerequisites.md
Microsoft will drop support for Windows Server 20H2 on 2022-08-09.
In line with this, WMCO no longer supports this version, leaving
Windows Server 2022 LTSC as the recommended version for vSphere worker nodes.
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1145.
=> [release-4.9] WINC-820: [docs] Remove Windows Server 20H2 support

docs/vsphere-golden-image.md, docs/wmco-prerequisites.md
Microsoft will drop support for Windows Server 20H2 on 2022-08-09.
In line with this, WMCO no longer supports this version, leaving
Windows Server 2022 LTSC as the recommended version for vSphere worker nodes.
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1145.
=> [release-4.8] WINC-820: [docs] Remove Windows Server 20H2 support

controllers/configmap_controller.go, pkg/daemon/controller/controller_test.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go, test/e2e/validation_test.go
The servicescm should not be the package which declares the expected
contents of the Windows service ConfigMap, that is a more fitting
responsibility of the ConfigMap controller. The reasoning for this is
that the CM controller is the entity which is responsible for
maintaining the CM's expected state. The state is also highly dependent
on cluster configuration, such as the platform type, information which
is more fitting on the controller level, rather than where it currently
exists.
As part of this change, the servicescm.GenerateWithData() function is
being removed, and its functionality is being moved into
servicescm.Generate().
=> Move service CM definition out of servicecm package

controllers/configmap_controller.go, pkg/nodeconfig/nodeconfig.go, pkg/services/services.go, pkg/windows/windows.go
This commit adds the hybrid-overlay service spec to the Windows service
ConfigMap, causing WICD to start and maintain the service. WMCO will
still wait to ensure that hybrid-overlay has done its job, as kube-proxy
cannot be started until that point.
=> WINC-737: Start hybrid-overlay with WICD

cmd/operator/main.go, go.mod
Makes timestamps human readable for easier use
=> Log WMCO timestamps in RFC3339 format

Makefile, hack/community/csv/description.md, hack/community/generate.sh, hack/community/readme.md
Adds the 'community' target to our Makefile that calls the generate.sh
script in order to generate a community bundle in the artifact dir to be used in
our CI e2e test for community branch PRs.
Adjusts generate.sh to ensure it aligns with the
aws-e2e-operator platform test in CI.
=> WINC-823: Test generated community manifests in WMCO e2e

docs/machineset-aws.md
* Removes outdated note on usable Windows server versions.
* fixes formatting for variables
* renames variable to more fitting name
=> Update AWS machineset docs

README.md
Adds a supported storage section to our docs that specifies that
only in-tree storage methods are supported in each cloud platform.
=> [docs] Clarify storage support

CONTRIBUTION.md
This change updates the contribution guidelines to support
the [OCP Bugzilla to Jira adoption](https://docs.google.com/document/d/1qbKUl4K9PPW4tCbdDgWSXd5klosX77ifkxQLqzjztGE/preview).
=> [docs] OCP Bugzilla to Jira adoption

test/e2e/clusterinfo/constants.go, test/e2e/clusterinfo/openshift.go, test/e2e/main_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/machineset/machineset.go, test/e2e/providers/vsphere/vsphere.go
This PR contains commits relating to refactoring the providers packages, used by the WMCO e2e tests to generate MachineSet specs. This will make adding additional platform easier.
=> Refactor providers package

pkg/daemon/winsvc/winsvc.go, pkg/retry/retry.go
This PR adds a wait to EnsureServiceState, ensuring that the Windows
service actually has the desired state when the function returns. This makes
any operations that occur after calling this function safe (for example, 
deleting after changing state to stopped).
=> [winsvc] Wait for service state changes

cmd/daemon/bootstrap.go, cmd/daemon/cleanup.go, controllers/configmap_controller.go, pkg/daemon/cleanup/cleanup.go, pkg/daemon/cleanup/cleanup_test.go, pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/daemon/fake/manager.go, pkg/daemon/fake/manager_test.go, pkg/daemon/manager/manager.go, pkg/servicescm/servicescm.go
WMCO will invoke WICD `cleanup` to remove an instance from the cluster. 
This PR covers the initial implementation of said command to remove services.
When the WICD cleanup command is executed, all services managed by us 
(as defined in the expected services ConfigMap) will be stopped and deleted. 
It will then delete the instance's Node object by default. 
When ran with the optional `--preserveNode` arg, the Node object won't be deleted.
=> WINC-718: WICD cleanup command

test/e2e/providers/aws/aws.go
This reverts commit 67305ad023f0011a1d006be5e5f2b913bfe12ef7.
openshift-ci bot cannot do this as the cherry-picked commit 7f73878dcc3c33d5a6a3d2e557655e7bae2d84e7 was made directly to the master branch, and does not have a PR associated with it.
=> [release-4.11] Revert "[e2e] unblock aws CI failure"

hack/common.sh, hack/community/generate.sh, hack/run-ci-e2e-test.sh
Adds a check for the COMMUNITY env var. If present(true), the manifest
location is set to the artifact dir. Otherwise, it is set to the local bundle/ location.
Moves ARTIFACT_DIR check up so that nounset is not triggered. 
Adjusts generate.sh to copy over wmco-package.yaml
to the community bundle as it's needed for e2e testing.
Depends on: https://github.com/openshift/windows-machine-config-operator/pull/1151 and https://github.com/openshift/release/pull/30711
=> WINC-823: Test generated community manifests in WMCO e2e Followup

hack/run-ci-e2e-test.sh, test/e2e/logs_test.go
Adds a retry for node log retrieval, and logs the command output upon
failure.
=> Make log test more resilient

README.md, controllers/windowsmachine_controller.go, docs/HACKING.md, docs/machineset-gcp.md, docs/wmco-prerequisites.md, pkg/secrets/secrets.go, test/e2e/create_test.go, test/e2e/delete_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/machineset/machineset.go, test/e2e/providers/none/none.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go
This PR adds multiple commits around providing WMCO support for GCP clusters
* Commits to have GCP to work with our test suite:
* [controllers] Add ignore label to filter Machines 
* [e2e] Add GCP provider
*  Commits to add GCP functionality and docs to WMCO:
* [secrets] Enable Administrator account if needed
* [docs] Document GCP support
=> WINC-815: Add support for Windows Server 2022 on GCP clusters

.gitmodules
This PR set the corresponding 4.11 branches and updates the following submodules:
[submodule][ovn-kubernetes] Update to https://github.com/openshift/ovn-kubernetes/commit/e2e2b4dde08bd5439e55437b12448b83d06214e4
[submodule][kubelet] Update to https://github.com/openshift/kubernetes/commit/b62823b40c2cb182f975fec0cb8378b2016ee9c5
[submodule][cloud-provider-azure] Update to https://github.com/openshift/cloud-provider-azure/commit/ac2724f3e7c0bc438cf76c15c10ff1b6d2c145bf
Ran: 
```
./hack/update_submodules.sh
```
=> [community-4.11][submodule] Update 08/29

README.md
This commit adds a supported storage section to our docs that specifies that
only in-tree storage methods are supported in each cloud platform.
Signed-off-by: Alina Ryan <aliryan@redhat.com>
(cherry picked from commit faa4ae134c6465962e11a0a2030e504f998f1845)
=> [release-4.8] [docs] Clarify storage support

README.md
This commit adds a supported storage section to our docs that specifies that
only in-tree storage methods are supported in each cloud platform.
Signed-off-by: Alina Ryan <aliryan@redhat.com>
(cherry picked from commit faa4ae134c6465962e11a0a2030e504f998f1845)
=> [release-4.9] [docs] Clarify storage support

config/manager/manager.yaml, hack/common.sh, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/wmco_test.go
This change adds the Pod Security admission enforcement labels to
the test namespace created in the e2e tests and to the WMCO namespace
created at deployment, allowing the automatic synchronization of privileged
pods directly without any intermediate pod controller, so that the serviceaccount
has enough privileges to run it. The WMCO namespace is a system namespace ("openshift-" prefixed)
and the `security.openshift.io/scc.podSecurityLabelSync` label is set as
`true` to ensure the automatic Pod Security label synchronization.
=> WINC-879: Introduce Pod Security admission labels

build/Dockerfile.ci
This was missed in openshift/windows-machine-config-operator#1075. `registry.ci.openshift.org/openshift/release:golang-1.18` comes with `jq` pre-installed and we no longer need to install it.
=> [build] Switch to golang 1.18 in Dockerfile.ci

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This change bumps the patch version in prep for next release.
=> [release-4.8] WINC-858: Prep for 3.1.2 release

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This change bumps the patch version in prep for the next release.
=> [release-4.10] WINC-858:  Prep for 5.1.1 release

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This change bumps the patch version in prep for the next release.
=> [release-4.9] WINC-858: Prep for 4.0.2 release 

Makefile, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This change bumps the operator and the OCP version
according to WMCO 7.0.0 release.
Ran:
```
make bundle
```
=> WINC-858: Prep for 7.0.0 release

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This change bumps the patch version in prep for the next release.
=> [release-4.11] WINC-858: Prep for 6.0.1 release

test/e2e/providers/azure/azure.go
SSH server installs on Azure Windows Server 2022 images after 20348.1129.221007 are failing with:
```console
PS C:\ProgramData\ssh> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
At line:1 char:1
+ Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
+ FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
```
Pin the image to 20348.1129.221007 to avoid this until Microsoft fixes the issue.
=> [test] Pin Azure 2022 image to 20348.1129.221007

test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/machineset/machineset.go, test/e2e/providers/vsphere/vsphere.go
The  infra name prefix is required for proper clean up when deprovisioning the cluster especially on GCP. Adding AWS to sync with what we are doing in the machineset hack script. Note that this cannot be done for all providers as Azure has naming restrictions when it comes to Windows VMs.
=> [test] Fix naming of MachineSet

test/e2e/network_test.go
Use the lts-nanoserver-ltsc2022 image for all providers except AWS now that we have moved to using Windows Server 2022.
Ref: https://github.com/openshift/release/pull/32500
=> WINC-830: [test] Use lts-nanoserver-ltsc2022 image

test/e2e/validation_test.go
This PR aims to fix the issue with failing CSR validation of CSR's that have a missing status condition.
These CSR's cannot be approved, hence they need to be skipped.
Latest failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1258/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1577062440414220288
csr.json: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1258/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1577062440414220288/artifacts/vsphere-e2e-operator/gather-extra/artifacts/csr.json
"status": {}
=> Fix CSR validation failure for missing status conditions

test/e2e/network_test.go, test/e2e/providers/vsphere/vsphere.go
- Use the `windows-golden-images/windows-server-2022-template-with-docker` VM template
- Use the `ts-nanoserver-ltsc2022` image for vSphere and platform:none
Ref: https://github.com/openshift/release/pull/32500
=> [release-4.10] WINC-830: [test] Update Windows Server 2022 image + template

test/e2e/validation_test.go
This change removes the e2e test that checks the kubelet version, so that
WMCO e2e test suite does not fail on k8s version bumps. This test was being
used as a signal and we no longer need it as we are proactive about that.
=> Remove kubelet version test

controllers/configmap_controller.go, pkg/nodeconfig/nodeconfig.go, pkg/services/services.go, pkg/windows/windows.go, test/e2e/create_test.go
Adds the azure cloud node manager into the windows-services ConfigMap
when an azure cluster is set to use CCM. This causes WICD to start and
manage the service. WMCO will no longer start the service.
=> WINC-739: Azure node manager added to services ConfigMap

cmd/operator/main.go, controllers/secret_controller.go, controllers/windowsmachine_controller.go, pkg/secrets/secrets.go, pkg/secrets/secrets_test.go
This change introduces a logic to process platform-specific
tags in the windows-user-data secret.
=> WINC-888: Use platform-specific tags in userData

build/Dockerfile, build/Dockerfile.ci, build/Dockerfile.wmco, cmd/operator/main.go, pkg/internal/gcp-get-hostname.ps1, pkg/nodeconfig/payload/payload.go, pkg/services/services.go, pkg/services/services_test.go, pkg/windows/windows.go
This change fetches the hostname from the GCE instance metadata service
and overrides the kubelet hostname so that the name of the Windows node
matches the hostname. The hostname is truncated if the length is longer
than 63 characters.
Should go after:
- https://github.com/openshift/windows-machine-config-operator/pull/1279
=> OCPBUGS-2028: Set kubelet hostname for GCP platform

pkg/windows/windows.go, test/e2e/create_test.go
Before, the check to see if Windows Defender antivirus was running was wrongly
checking for any services whose name starts with Windows Defender regardless of
state, leading to an error creating an exclusion for containerd on instances
without Defender installed. 
This PR fixes this by checking for the presence of the specific running process 
associated with the Defender antivirus service.
It also adds an e2e test to validate instances are able to be configured into
Nodes regardless of the Windows Defender antivirus status.
Fixes OCPBUGS-1513
Fixes #1240
=> OCPBUGS-1513: Fix check for Windows Defender

.github/ISSUE_TEMPLATE/merge-blocker.yml
This template will be used to created an issue that will result in blocking of PRs merges to a release branch. This is useful when code freeze is in effect. Meant to be used only by @openshift/openshift-team-windows-containers
=> Add merge blocker issue template

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
This change includes checks to validate the addresses in the metric endpoint subsets before looking for a matching node name, so that prevents a NPE if the field is not present.
Fixes OCPBUGS-3203
=> OCPBUGS-3203: [metrics] Add check for endpoints subsets address

controllers/secret_controller.go, controllers/windowsmachine_controller.go, test/e2e/create_test.go, test/e2e/secrets_test.go
This PR makes it so that Machine back Windows Nodes will be upgraded in place, in the same way that BYOH Windows nodes are. This fixes an issue relating to having to re-download container images after node upgrade. Machines will now be deleted whenever WMCO has to update the Windows userdata secret.
=> OCPBUGS-3506: Upgrade Machine Nodes in place

Makefile
This change is needed because the 'make bundle' command was failing since
'go get' can no longer install executables. Effective in Go 1.17, installing
executables must be done with 'go install'.
Doc Ref: https://go.dev/doc/go-get-install-deprecation
Also upgraded kustomize version to be able to install it with 'go install'
=> [build] Replace 'go-get' with 'go-install'

build/Dockerfile, build/Dockerfile.ci, build/Dockerfile.wmco, pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/internal/windows-defender-exclusion.ps1, pkg/nodeconfig/payload/payload.go, pkg/services/services.go, pkg/windows/windows.go
This PR moves the containerd service definition to `windows-services` 
ConfigMap. The priorities of other services were adjusted since containerd
is a bootstrap service that also must be first to start.
Starting containerd (including the pre-config work of creating a Windows
Defender exclusion if needed) is now done by WICD bootstrap instead of WMCO.
=> WINC-898: Containerd is added to windows-services configmap

test/e2e/providers/azure/azure.go
This reverts commit bf31913c now that microsoft/Windows-Containers/issues/285 has been fixed.
=> Revert "[test] Pin Azure 2022 image to 20348.1129.221007"

pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/services/services.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go
Renames powershellVariablesInCommand to powershellPreScripts to remove the implicit requirement of a variable to replace, which is not always necessary. Also renames powershellVaraiblesInCommand.Name, to VariableName, to be more clear about the purpose of the field with the new naming.
=> WINC-949: Rename powershellVariablesInCommand

test/e2e/metrics_test.go, test/e2e/network_test.go, test/e2e/upgrade_test.go
This PR consolidates the creation of the linux curl commands in the e2e tests so that there is a standard way of calling the curler jobs.
=> WINC-677: [e2e] Modularize linux curler job creation

controllers/windowsmachine_controller.go, pkg/nodeutil/nodeutil.go
This PR fixes an issue where Machine nodes were not being identified as
out-of-date. This made them skip the deconfigure process, preventing draining
nodes, which would have resulted in a user workload disruptions during upgrade.
Fixes [OCPBUGS-5732](https://issues.redhat.com/browse/OCPBUGS-5732)
=> OCPBUGS-5732: [wm_controller] Fix Machine node upgrades

.gitmodules
Update to containerd [v1.6.15](https://github.com/openshift/containerd/releases/tag/v1.6.15) and hcsshim [v0.9.6](https://github.com/openshift/hcsshim/releases/tag/v0.9.6)
Ran:
```bash
hack/update_submodules.sh -m containerd -r release-4.12 release-4.12
git checkout release-4.12-submodule-update-01-12
hack/update_submodules.sh -m hcsshim -r release-4.12 release-4.12-submodule-update-01-12
```
Renamed the resulting branch and opened the PR.
=> [release-4.12] WINC-957: [submodule] Update to containerd v1.6.15 and hcsshim v0.9.6

.gitmodules
Update to containerd [v1.6.15](https://github.com/openshift/containerd/releases/tag/v1.6.15) and hcsshim [v0.9.6](https://github.com/openshift/hcsshim/releases/tag/v0.9.6)
Ran:
```bash
hack/update_submodules.sh -m containerd -r release-4.11 release-4.11
git checkout release-4.11-submodule-update-01-12
hack/update_submodules.sh -m hcsshim -r release-4.11 release-4.11-submodule-update-01-12
```
Renamed the resulting branch and opened the PR.
=> [release-4.11] WINC-957: [submodule] Update to containerd v1.6.15 and hcsshim v0.9.6

pkg/nodeconfig/nodeconfig.go, pkg/services/services.go, pkg/windows/windows.go, test/e2e/certificates_test.go
Directory deletion is not being caught because err is nil, while
the actual reported error is present in out. This is being fixed by
using the PowerShell alternative, which will properly report an error.
In order to make use of Remove-Dir, trailing backslashes were removed
from constants, as they were causing unintentional escaping of quotes.
Fixes OCPBUGS-5887
=> OCPBUGS-5887: Check for error when deleting directories

cmd/daemon/cleanup.go, pkg/daemon/cleanup/cleanup.go, pkg/daemon/controller/controller.go, pkg/daemon/fake/manager.go, pkg/daemon/manager/manager.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
With this PR, WMCO starts invoking WICD cleanup command to stop and delete services and delete the node object.
Responsibility of removing directories and HNS networks is mainatined by WMCO while excluding deletion of log directories for future reference.
=> WINC-733: Instance cleanup is done by WICD cleanup command

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml, hack/run-ci-e2e-test.sh, pkg/daemon/cleanup/cleanup.go, pkg/nodeconfig/nodeconfig.go, test/e2e/delete_test.go
Draining a workload created with a DaemonSet was causing an error due
to lacking DaemonSet `get` permissions. This change adds the RBAC
permissions to resolve said error.
Additionally, the drain flags had to be adjusted by adding the `force`
and `IgnoreAllDaemonSets` flags.
Because draining ignores Daemonset pods, the pod's containers would be
leaked, continuing to run in the background even with kubelet and
containerd stopped. Stopping containerd does not stop containerd
containers running on the instance.
This behavior is preventing WMCO from removing the containerd shim.
To address this, WICD cleanup was made to kill all processes using
the shim, which will stop the leaked containers.
An issue with how the deletion tests were being invoked needed to be
corrected in order to properly …
=> OCPBUGS-5354: Enable draining DaemonSet workloads

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
* Updates version in Makefile to 7.0.1.
* Adds 7.0.0 to skipRange as it breaks upgrades for clusters with WMCO installed in a non-default namespace
* `make bundle` ran to update the `bundle/` directory
=> WINC-930: Prep for 7.0.1 release

hack/machineset.sh
Using the image family will use the latest released image from the
family (Windows server 2022) without having to exec gcloud.
The projectID is available within the cluster infrastructure object
and should be retrieved that way.
=> Remove gcloud dependency in hack/machineset.sh

pkg/daemon/manager/manager.go
This commit removes an unecessary Windows API call, as the error returned by OpenService will inform the caller if the service doesn't exist.
=> Use error code to determine svc existence

bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/wicd/windows-instance-config-daemon-cluster-role.yaml, controllers/controllers.go, controllers/secret_controller.go, controllers/windowsmachine_controller.go, pkg/cluster/config.go, pkg/daemon/cleanup/cleanup.go, pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/metadata/metadata.go, pkg/nodeconfig/nodeconfig.go, pkg/secrets/secrets.go, pkg/servicescm/servicescm.go, pkg/windows/windows.go, test/e2e/delete_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/secrets_test.go, test/e2e/validation_test.go
This PR moves the version annotation application and removal to WICD,
instead of WMCO. This allows us to reduce WMCO's responsibility when reconciling
nodes -- it no longer watches or stops any WICD managed Windows services. It also
shifts the responsibility of stopping services before bootstrapping from WMCO to WICD.
To do this, the WICD cleanup command was with partial best effort cleanup, using 
most recently created services ConfigMap  if no associated node object exists.
The PR also includes miscellaneous changes:
Adds containerd to the services ConfigMap validation e2e test.
Removes hardcoded values and consolidates Machine API namespace & user data constants.
Rehomes the desired version annotation constant to the metadata pkg.
=> WINC-741: WICD takes more responsibility of Node configuration

Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/update_submodules.sh
The openshift/kubernetes repo does not propagate all tags from upstream. Only the X.Y.0 tag is propagated. This causes the Windows kubelet and kube-proxy Z version to lag behind its Linux counterparts. The Linux [build](https://github.com/openshift/doozer/blob/a34e303682ca180e4f071f85cc4c34e6d333787e/doozerlib/metadata.py#L788) of kubelet and kube-proxy figures out the Z version at build time. To do something similar for Windows, we can leverage the hack/update_submodules.sh script which is always used to update the kubelet and kube-proxy submodules. To achieve this, the following changes are made:
- Add kubelet and kube-proxy version variables to the Makefile along with make endpoints
- Call these make endpoints in the Dockerfile
- Update hack/update_submodules.sh to pull upstream tags …
=> OCPBUGS-6635: [build] Fix k8s version reporting

pkg/services/services.go
This PR fixes an issue where the kubelet logs were not being written to the kubelet.log file.
The kubelet.exe invocation was not ordered correctly with the arguments being passed before it. 
Moreover, we do not want to set the `-redirect-stderr` flag to false and want to default to true which means we want our error logs to be logged to the same kubelet log file instead of stderr.
Fixes: OCPBUGS-7287
=> OCPBUGS-7287: Fix Kublet logs are not written to kubelet.log

.gitmodules, Makefile, pkg/services/services.go, pkg/windows/windows.go, test/e2e/logs_test.go
- Replace the usage of deprecated klog flags like --log-dir and --logstostderr with the kube-log-runner invocation to direct logs to a single log file.
- [submodule][kube-proxy] Update to 9500d080756 
- [build] Update kube-proxy version to v1.26.0+9500d08
=> WINC-977: Update kube-proxy submodule to sdn-4.13

test/e2e/network_test.go, test/e2e/providers/azure/azure.go
this PR enables using Windows Server 2019 instead of Windows Server 20H2 for e2e tests
=> WINC-920: Use Windows Server 2019 for Azure e2e tests

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
* Updates version in Makefile to 7.1.0.
* Removes `skipRange` from CSV as it has no effect on 7.1.0 upgrade path.
* `make bundle` ran to update the `bundle/` directory
=> WINC-981: [release-4.12] Prep for 7.1.0 release

Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/update_submodules.sh
The openshift/kubernetes repo does not propagate all tags from upstream. Only the X.Y.0 tag is propagated. This causes the Windows kubelet and kube-proxy Z version to lag behind its Linux counterparts. The Linux [build](https://github.com/openshift/doozer/blob/a34e303682ca180e4f071f85cc4c34e6d333787e/doozerlib/metadata.py#L788) of kubelet and kube-proxy figures out the Z version at build time. To do something similar for Windows, we can leverage the hack/update_submodules.sh script which is always used to update the kubelet and kube-proxy submodules. To achieve this, the following changes are made:
- Add kubelet and kube-proxy version variables to the Makefile along with make endpoints
- Call these make endpoints in the Dockerfile
- Update hack/update_submodules.sh to pull upstream tags …
=> [release-4.12] OCPBUGS-7336: [build] Fix k8s version reporting

README.md, test/e2e/delete_test.go, test/e2e/network_test.go, test/e2e/validation_test.go
This PR adds the OS field in the pod specification for the
Windows Server deployment used in the network test. This ensures that
Windows pods can be identified authoritatively at admission time. As of
now, the SCC Admission Plugin does not perform any validation for Windows
pods, it ignores them. See to https://github.com/openshift/apiserver-library-go/pull/82
Fixes a CI issue introduced by https://github.com/openshift/kubernetes/pull/1290
where SCC Admission Plugin defaults the `runAsNonRoot` with value `true`.
=> WINC-838: Add OS field to pod spec in Windows Server deployment

Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/update_submodules.sh
Containerd Makefile uses VERSION env var to set the containerd version if it is not already set. When we run the make command in WMCO Dockerfile, the VERSION var is already set to the golang image version of the base image eg: registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.12.
This is the root cause of containerd Makefile not setting the version and we see containerd 1.19  as the misreported version in 4.12 and 1.18 in 4.11 cluster.
One way to solve this issue is unsetting the env var in Dockerfile however it may have other unknown implications with versions. Adding a containerd Makefile target instead that will set the value of the ENV var within context.
Fixes:  OCPBUGS-5378
=> OCPBUGS-5378: [build] Fix containerd version reporting

test/e2e/delete_test.go
Adds the daemonset status to the error message when it fails to scale completely.
=> [test] Improve error logging for DaemonSet

pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/services/services.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go
Reverts openshift/windows-machine-config-operator#1356
Reverting as part of the effort to get WICD work into 4.12: https://issues.redhat.com/browse/WINC-978
=> Revert "[release-4.12] WINC-949: Rename powershellVariablesInCommand"

Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/update_submodules.sh
Containerd Makefile uses VERSION env var to set the containerd version if it is not already set. When we run the make command in WMCO Dockerfile, the VERSION var is already set to the golang image version of the base image eg: registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.12.
This is the root cause of containerd Makefile not setting the version and we see containerd 1.19 as the misreported version in 4.12 and 1.18 in 4.11 cluster.
One way to solve this issue is unsetting the env var in Dockerfile however it may have other unknown implications with versions. Adding a containerd Makefile target instead that will set the value of the ENV var within context.
(manually cherry-pick from #1423)
=> [release-4.12] OCPBUGS-7843:  [build] Fix containerd version reporting

test/e2e/logs_test.go
This commit  adds a check to the logs tests to check that log files have non-zero size, ensuring they are actually being written to by the services.
=> WINC-983: [e2e] Ensure required log files are non-empty

Makefile, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This change bumps the operator and OCP version according to the WMCO 9.0.0 release.
Commands ran: 'make bundle'
=> WINC-952: [master] Prep for 9.0.0 release

Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, hack/update_submodules.sh
Containerd Makefile uses VERSION env var to set the containerd version if it is not already set. When we run the make command in WMCO Dockerfile, the VERSION var is already set to the golang image version of the base image eg: registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.12.
This is the root cause of containerd Makefile not setting the version and we see containerd 1.19 as the misreported version in 4.12 and 1.18 in 4.11 cluster.
One way to solve this issue is unsetting the env var in Dockerfile however it may have other unknown implications with versions. Adding a containerd Makefile target instead that will set the value of the ENV var within context.
(manually cherry-pick from https://github.com/openshift/windows-machine-config-operator/pull/1424)
=> OCPBUGS-8055: [release-4.11]  [build] Fix containerd version reporting

pkg/secrets/secrets.go
Disables password auth for Windows VMs by default to prevent unauthorized access to VMs and because it is required by CoreOS.
=> WINC-535: Disable password auth for Windows Machine VMs

hack/machineset.sh
The hack/machineset.sh script was relying on an incorrect way to determine the platform of the cluster. The expected result of the query has changed, and broken the script. This commit changes the script to use use the infrastructure/cluster object to correctly determine the platform.
=> [hack] MachineSet script platform discovery fix

pkg/metrics/metrics.go
This PR makes the cluster monitoring label for the WMCO namespace case insensitive to provide better user experience. Previously, not adhering to an all lowercase `true` value would result in WMCO ignoring the label and not configuring/exposing Prometheus metrics for Windows nodes.
Fixes OCPBUGS-10222
Fixes #1478
=> OCPBUGS-10222: [metrics] Ignore case of cluster monitoring label

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml
As WMCO is ran with host network privileges, its DNS policy is currently
using the DNS servers of the Node it is running on.
Instead, the policy should be set to `ClusterFirstWithHostNet`. Without
this it will not be able to resolve any addresses defined within the
cluster's DNS, such as internal services. With this policy, cluster
defined services can be resolved, while also using the cluster
configured upstream name server for any names that are not within the
cluster.
=> Use ClusterFirstWithHostNet DNS policy

bundle/metadata/annotations.yaml
This PR sets the proper OCP version in the bundle metadata so the
operator is only included in catalogs targeting the compatible OCP version.
Follow-up to https://github.com/openshift/windows-machine-config-operator/pull/1456
=> [bundle] Fix metadata version annotation

test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/upgrade_test.go
Adds required methods to ClusterProvider, and calls them to add a persistent storage volume to the Windows webserver pods created during the north south tests.
Creating a PVC is currently disabled on all providers, but as functionality is added, it can be enabled for each provider individually.
=> [test] Add framework for storage testing

bundle.Dockerfile, bundle/metadata/annotations.yaml
This commit updates the OCP version label used in the bundle.Dockerfile and the annotations.yaml file to use v4.13 until v4.14 index images are supported by CVP.
=> [bundle] Fall back to using v4.13 OCP version label

pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go, test/e2e/network_test.go
https://github.com/openshift/windows-machine-config-operator/commit/62dc2c3e8db93de37a3b557c52de7bb18d3bfd85 introduced creating a CNI config with PascalCase moving away from the camelCase that was used previously generated. Generated is the key word here as the old template used PascalCase but the generated config was camelCase. This commit fixes the issue by adhering to the CNI config [definition](https://www.cni.dev/plugins/current/main/win-overlay/) for the win-overlay plugin.
=> OCPBUGS-10437: Fix CNI conf

test/e2e/network_test.go
Removes defunct DNS test and replaces it with a test which ensures that pods can resolve cluster services through DNS.
(cherry picked from commit 38e374f6274b7a8c400eb3c816e3764b6c48e0e4)
=> [release-4.11] Assert that Windows pods use cluster DNS

test/e2e/network_test.go
Removes defunct DNS test and replaces it with a test which ensures that pods can resolve cluster services through DNS.
(cherry picked from commit 38e374f6274b7a8c400eb3c816e3764b6c48e0e4)
=> [release-4.10] Assert that Windows pods use cluster DNS

test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/vsphere/vsphere.go
Adjusts the CreatePVC method to allow the namespace to be specified. Additionally cleans up PVCs when done with them.
=> [test] Add namespace for PVC creation

test/e2e/logs_test.go
The purpose of this commit is to fix the panic introduced by https://github.com/openshift/windows-machine-config-operator/commit/0a5bad55ae625df7e3995e893c9e63348ff87c63.
(changed link to reference the openshift repo)
=> [test] fix panic introduced by 0a5bad5

bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/wicd/windows-instance-config-daemon-cluster-role.yaml
This PR adds the WICD RBAC permissions to delete nodes. This is required to ensure a successful upgrade since WMCO version 7.0.1 has the WICD binary with the capability to delete nodes, this feature was removed in WMCO 8.0.0. This commit will ensure backward comaptibility during an upgrade from 7.0.1 to 8.0.0.
Ran:
`make bundle`
Fixes: OCPBUGS-11259
=> OCPBUGS-11259: BYOH node upgrade failed with WICD RBAC permissions

hack/run-ci-e2e-test.sh, test/e2e/network_test.go, test/e2e/storage_test.go, test/e2e/wmco_test.go
Instead of using the network tests to indirectly test storage, move it to a separate test. This ensures that neither test is compromised by the requirements of the other. As storage testing uses the same container image, this should not add much to the testing time, since no images need to be pulled.
=> [test] Move storage testing to its own test

docs/vsphere_ci/README.md, docs/vsphere_ci/scripts/disable-ipv6.ps1, docs/vsphere_ci/windows-server-2022.pkr.hcl
To work around the issue with "oc adm node-logs" hitting an IPv6 address on IBM vCenter clusters, disable IPv6 on the Windows Server 2022 template.
Also fixed minor issues in the README.md.
Fixes OCPBUGS-11306
=> OCPBUGS-11306: [vpshere_ci] Disable IPv6 on Windows 2022

hack/machineset.sh, test/e2e/providers/vsphere/vsphere.go
Switch to using the IPv6 disabled template for Windows Server 2022 to mitigate issues seen in CI when the job lands in IBM vCenter where the DHCP server hands out IPv6 addresses causing `oc adm node-logs` test to fail. To be consistent update the machineset.sh script to also use the same template.
Fixes OCPBUGS-11306
=> OCPBUGS-11306: [test] Use IPv6 disabled template for Windows 2022

pkg/daemon/cleanup/cleanup.go
This PR uses the version annotation instead of the desired version
as the source of truth when deconfiguring Windows services. This is 
important to ensure there are no services left behind when upgrading, 
if there is a change to the services CM spec between WMCO versions.
Using the desired version anno is kept as a backup operation if the node 
does not have a version annotation (i.e. was not fully configured). This is 
useful to recover when configuration fails and the instance needs to be reconciled.
=> WINC-1040: Use Version annotation for service removal in WICD cleanup

pkg/services/services.go, test/e2e/create_test.go, test/e2e/validation_test.go
Uses the kubelet priority flag introduced in https://github.com/kubernetes/kubernetes/pull/96051 to set the kubelet priority class to ABOVE_NORMAL_PRIORITY_CLASS to ensure that running Pods do not starve the kubelet of CPU cycles.
=> WINC-561: Set kubelet priority flag

controllers/configmap_controller.go, controllers/windowsmachine_controller.go, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/nutanix/nutanix.go, test/e2e/validation_test.go
[controllers] Support Nutanix platform
Nutanix is similar to the vSphere platform, so add the Nutanix platform in
places where vSphere platform is special cased.
Do the same in the e2e tests except for testPrivateKeyChange() because of
cloudbase-init support in Nutanix.
=> WINC-1035: Support Nutanix platform

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
This PR enhances the node deconfiguration process to allow for better backward compatibility and failure recovery during upgrades.
- use the new version's WICD binary to cleanup during upgrade
- stop the WICD controller service from running before running WICD cleanup when recovering from node config failure
=> WINC-1033: Use latest WICD binary during upgrades

hack/common.sh
Introduces a common function that deduces the OCP version from the
WMCO version that can be used when updating the OCP versions for all WMCO
releases.
=> [hack] infer OCP version from WMCO version 

test/e2e/delete_test.go
vSphere BYOH MachineSets were not being cleaned up at the end of the e2e tests. As the blocking bug linked in the code is fixed, the special casing can be removed.
=> WINC-635: Remove vSphere Machine deletion exception

docs/wmco-prerequisites.md
Add an explanation of why we are dropping Azure support in WMCO 5.x and lower.
=> WINC-1036: Drop Azure support in WMCO 5.x and lower

.gitmodules, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, docs/HACKING.md, goio.yaml, hack/update_submodules.sh, pkg/nodeconfig/payload/payload.go, pkg/services/services.go, pkg/windows/windows.go, test/e2e/providers/vsphere/vsphere.go
This PR allows the use of persistent storage on Windows nodes with CSI drivers.
It includes:
* Shipping csi-proxy in the payload
* Running csi-proxy as a Windows service
* Tests storage functionality using vSphere csi drivers
=> WINC-1025: Enable CSI plugins on Windows nodes

docs/HACKING.md, hack/machineset.sh, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/nutanix/nutanix.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go, test/e2e/windows/version.go, test/e2e/wmco_test.go
- Make Windows version configurable in the e2e tests by using an environment variable, `WINDOWS_SERVER_VERSION`.
- Make Windows version configurable in machineset.sh using a command line option
=> WINC-1037: Allows selecting Windows Server version for testing

Makefile
* https://github.com/openshift/ovn-kubernetes/commit/401c3ae3508d24dccb5fce60cf903d1718f90832
* Updates reported kubelet version, no actual version change included.
=> [release-4.12] submodule update 05/16

hack/common.sh, hack/pre-release.sh, hack/update_submodules.sh
There are many places in a number of files where the versions of the WMCO and OCP need to be updated for release. These should be automated so it no longer has to be done manually.
=> WINC-860: [hack] Automate pre-release version updates

cmd/operator/main.go, controllers/configmap_controller.go, hack/run-ci-e2e-test.sh, pkg/cluster/config.go, test/e2e/proxy_test.go, test/e2e/wmco_test.go
This PR introduces a new resource to be managed by WMCO in proxied
clusters. This resource will contain a trusted CA injection request label so it
will be updated by the cluster-network-operator (CNO) when the global
Proxy resource changes. This is the first step to supporting custom user
certificates for HTTPS proxies.
It also creates the scaffolding for the proxy test suite, which can be
expanded as more proxy support functionality is added and needs to be tested.
=> WINC-999: WMCO manages new trusted CA ConfigMap

hack/run-ci-e2e-test.sh, test/e2e/main_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This is a set of changes which are meant to enable better upgrade testing in CI
=> Test suite enhancements around WMCO deployments

docs/HACKING.md
The refactor removed information about operator-sdk from the hacking.md This returns it.
=> [docs] Adds operator-sdk prequisite and version

build/Dockerfile, build/Dockerfile.base
This PR updates the Dockerfiles to use ubi9 images which is in sync with the rest of the base images used.
=> [build] Update Dockerfile to use ubi9 images

docs/HACKING.md, hack/machineset.sh, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go, test/e2e/windows/version.go, test/e2e/wmco_test.go
- Make Windows version configurable in the e2e tests by using an environment variable, WINDOWS_SERVER_VERSION.
- Make Windows version configurable in machineset.sh using a command line option
This is a manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1586
=> [release-4.13] WINC-1037: Allows selecting Windows Server version for testing

build/Dockerfile, build/Dockerfile.base
This PR updates the Dockerfiles to use ubi9 images which is in sync with the rest of the base images used.
(cherry picked from commit 06ae6644de01d21981626e2226ac41293ea4c7eb)
=> [release-4.13] [build] Update Dockerfile to use ubi9 images

docs/HACKING.md, hack/machineset.sh, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/validation_test.go, test/e2e/windows/version.go, test/e2e/wmco_test.go
- Make Windows version configurable in the e2e tests by using an environment variable, WINDOWS_SERVER_VERSION.
- Make Windows version configurable in machineset.sh using a command line option
This is a manual backport of #1615
=> [release-4.12] WINC-1037: Allows selecting Windows Server version for testing

test/e2e/providers/vsphere/vsphere.go
Adds the use-csinode-id flag which is being set to true for Linux nodes. Without this change Windows node CSI configuration fails.
=> [test] Use updated vSphere FSS ConfigMap values

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml, pkg/cluster/config.go, pkg/cluster/config_test.go
OCPBUGS-4862 fixed an issue where deletion of a BYOH node object resulted in it hanging in the `Ready,SchedulingDisabled` state. This was fixed in OCP 4.12.3 and as a result any WMCO upgrades from 7.0.1 needs to be on versions greater than that. Otherwise BYOH node upgrades will fail and could potentially cause workload disruptions. To prevent that from happening stop WMCO 7.1.0 from running if the OCP version is below 4.12.3.
Fixes OCPBUGS-14260
=> [release-4.12] OCPBUGS-14260: Check for minimum OCP version

pkg/daemon/cleanup/cleanup.go, pkg/daemon/cleanup/cleanup_test.go, test/e2e/delete_test.go
Uses the union of the services present in the services CM for the version that configured it as well as the latest CM present in the cluster. This ensures that all services will be accounted for when cleaning up an instance.
=> OCPBUGS-13780,OCPBUGS-14700: Use latest and version CM for cleanup

hack/errata-check.sh
In some cases a PR may reference multiple bugs in the title.  This fix returns only the first bug referenced for looking up details.  The error message is also updated to include more detail for troubleshooting.
=> [hack] Fix error when a PR links to multiple bugs

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
Switches from using Poll() to PollImmediate() where appropriate. Each of these uses have the potential to not require the wait period before attempting to perform the task being polled. These unecessary wait periods of 5 and 15 seconds add up, and they should be avoided where possible.
=> Remove unnecessary poll wait times

controllers/configmap_controller.go
The check for the existing windows-instance-config-daemon ClusterRoleBinding and RoleBinding objects with the expected objects was not doing deep compares. This caused the the existing object not to be deleted in the case where the WMCO namespace was changing.
Fixes OCPBUGS-15461
=> OCPBUGS-15461: Fix WICD RBAC comparisons

pkg/daemon/controller/controller_test.go
This commit fixes the WICD controller unit tests by adding a missing assert
for no error in the Reconcile func happy path.
waitUntilNodeReady() was introduced, which waits for a ready/schedulable node.
Before this, the test was passing despite the mock node not having these labels.
=> [wicd][controller] Fix Reconcile unit test

test/e2e/secrets_test.go
The userdata tamper test has been made to retry if previously configured
nodes were found, instead of failing. This prevents timing issues that
are being seen when refactoring the creation suite, to allow for the
addition of "real" upgrade testing.
=> Harden userdata tamper test

test/e2e/reconfigure_test.go
Removes the OperatorCondition check in the reconfigure test. The check
is causing issues, as the reconfigure test is changing the
version annotation, which is managed by WICD. If WICD fixes the change
by reconciling the node, before WMCO is able to reconcile the Machine or
windows-instance ConfigMap, WMCO's controllers will return early, and
not change the condition state.
The test discovered a scenario where WICD is working but WMCO is not
and is marking the operator as upgradable which is a bug and we are
temporarily disabling it. This will be addressed in the bug linked
in the TODO.
The timeline for this issue is as follows:
* Version annotation change happens
* WMCO is busy
* WICD sees that version annotation is incorrect
* WICD corrects version annotation state
* WMCO becomes un-busy …
=> Remove condition check in reconfigure test

Makefile, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
Adds the upgrade-test-setup and upgrade-test make targets, which are
designed to be ran before a WMCO upgrade occurs and after,
respectively. These targets will do basic testing on WMCO to ensure that
WMCO is able to upgrade nodes.
=> WINC-950: Test WMCO version upgrades

bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/wicd/windows-instance-config-daemon-cluster-role.yaml
WICD in WMCO 8.0.1 was given the node delete permission so that WMCO could successfully upgrade from 7.0.1. The permissions can now be removed as it is not needed to upgrade from the next 8 release to 9.0.0.
- Removed the delete verb from `config/wicd/windows-instance-config-daemon-cluster-role.yaml` 
- Ran `make bundle`. 
- Reverted unnecessary changes to `bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml`.
=> WINC-1023: Remove WICD node deletion RBAC permission

hack/update_submodules.sh
Version was being generated for csi-proxy, which is not required.
Removes this requirement.
=> [hack] Remove version gen for csi-proxy 

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This change bumps the patch version in prep for the next release.
Ran 'make bundle' after bumping version in the Makefile.
=> [release-4.12] WINC-1028: Prep for 7.1.1 release

controllers/node_controller.go, pkg/nodeconfig/nodeconfig.go
Allow a NodeConfig object to populate its node field on construction. 
This removed the need to call setNode to populate the node object in each of the exported NodeConfig methods. 
It also removed the need to pass in node objects to functions upon the NodeConfig struct, which was a bad pattern.
=> [nodeconfig] Set node in NodeConfig constructor

pkg/daemon/controller/controller.go, pkg/nodeconfig/nodeconfig.go
This PR flips the waiting and removal of the reboot annotation, with WICD now waiting on WMCO to remove the annotation. The reason for this is to decouple WMCO's node controller from the WICD controller -- WMCO removes the reboot annotation as soon as the instance is reachable again after rebooting. Now the safeReboot() func returns after it has done just that, safely rebooted, without waiting on some extra WICD signal.
=> WMCO removes reboot annotation instead of WICD

test/e2e/logs_test.go
This PR adds the csi-proxy.log to the list of required logs to collect in the e2e test suite, so that the csi-proxy logs are kept in the artifact folder.
Follow-up to:
- https://github.com/openshift/windows-machine-config-operator/pull/1530
=> Add csi-proxy logs collection in e2e test suite

controllers/configmap_controller.go, pkg/certificates/certificates.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/proxy_test.go
This PR is part 1 of supporting user-provided certs. 
WMCO copies over the CA bundle with all trusted cluster certs to Windows instances. 
This is done, if needed, during node configuration as well as when there are any 
events on the ConfigMap holding the trusted CA.
=> WINC-633: Copy additional CA bundle to Windows instances

hack/manifests/csi/vsphere/01-example-driver-daemonset.yaml, hack/manifests/csi/vsphere/02-example-namespace.yaml, hack/manifests/csi/vsphere/03-example-sc.yaml, hack/manifests/csi/vsphere/04-example-pvc.yaml, hack/manifests/csi/vsphere/05-example-deployment.yaml
Separates the manifests in the ideal order that they should be
deployed. 
Adds an example deployment spec and custom namespace used
to confirm a Windows pod with a storage mount file can be written to a
desired mount path.
=> [hack] Improve vSphere CSI Manifests

hack/machineset.sh, test/e2e/providers/aws/aws.go
This PR moves away from using Windows Server 2019 that have Docker pre-installed in CI as these images have been pulled from AWS. We had been using them for test coverage as we required pre-installed Docker runtime in 4.10 and below, before moving to containerd (WMCO-managed).
Moved to `Core` instead of `Full` as we use that in for 2022 images and it is more lightweight/faster startup time.
=> [aws] Avoid Windows Server 2019 `Containers` image

hack/machineset.sh, test/e2e/providers/aws/aws.go
This is an manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1723
=> [release-4.11] [aws] Avoid Windows Server 2019 `Containers` image

Makefile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/windows-machine-config-operator.package.yaml
This change bumps the patch version in prep for the next 5.1.2 release.
=> [release-4.10] WINC-1055: Prep for 5.1.2 release

docs/wmco-prerequisites.md
Explain why we are dropping AWS support in WMCO 5.x and lower.
(manually cherry picked from commit e0020e5fc991f9905b37a9ea92336910d542b012)
=> WINC-1092: [release-4.10][docs] Drop AWS support in WMCO 5.x and lower

docs/wmco-prerequisites.md
Add to explanation of why we are dropping AWS support in WMCO 5.x and lower.
=> WINC-1092: [docs] Drop AWS support in WMCO 5.x and lower

docs/wmco-prerequisites.md
Explain why we are dropping AWS support in WMCO 5.x and lower.
(manually cherry picked from commit https://github.com/openshift/windows-machine-config-operator/commit/e0020e5fc991f9905b37a9ea92336910d542b012)
=> WINC-1092: [release-4.11][docs] Drop AWS support in WMCO 5.x and lower

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml, pkg/ignition/ignition.go, pkg/nodeconfig/nodeconfig.go
This change pulls the kubelet CA from the machine's controller configuration, given it is getting removed from the machine ignition files.
Refs:
- https://github.com/openshift/machine-config-operator/pull/3787
=> OCPBUGS-17528: Get kubeletCA from controller configuration

pkg/cluster/config.go
Adds an exception for nightly clusters when checking OCP version, just like we do for CI clusters.
=> [release-4.12] OCPBUGS-17639: Allow WMCO to run on nightly clusters

pkg/daemon/controller/controller.go
This is a cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1656
PollUntilContextTimeout doesn't exist in version 0.26.1 of apimachinery. Replace this function with PollImmdiateWithContext temporarily until we start using version 0.27 of apimachinery.
=> [release-4.13] Ensure node becomes ready when configuring

pkg/ignition/ignition.go
Uses this function instead of Parse(), so that this can be backported to release-4.13. This will stop wmco 8.y.z from crashing upon cluster upgrade to 4.14, due to it being unable to parse the 3.4 ignition spec present on 4.14.
=> Use ParseCompatibleVersion when parsing ignition

pkg/servicescm/servicescm.go
This PR refactors the isPresentAndCorrect function using generics to reduce code duplication and make the code more object-oriented.
=> [servicescm] Use generics for Services and Files

pkg/cluster/config.go, pkg/daemon/cleanup/cleanup.go, pkg/daemon/cleanup/cleanup_test.go, pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/daemon/envvar/envvar.go, pkg/nodeconfig/nodeconfig.go, pkg/services/services.go, pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go, test/e2e/delete_test.go, test/e2e/proxy_test.go
This PR implements the following scenarios:
1. On existing Windows nodes, when an cluster-wide proxy is removed WICD is able to remove the ENV variables on the instance.
2. When a node deconfiguration occurs, WICD cleanup command will remove the ENV vars set on the instance if cluster-wide proxy is enabled. This includes HTTP_PROXY, HTTPS_PROXY, NO_PROXY being removed from the instance along with the keys set in the Windows registry.
=> WINC-998: Clear proxy variables from Windows nodes

pkg/nodeconfig/nodeconfig.go
Reverts commit e8839a128ed9dce8c202468d088ba629e8c7b89b which was a temporary fix for [OCPBUGS-13790](https://issues.redhat.com//browse/OCPBUGS-13790) given [WINC-948: WICD uses a kubeconfig to authenticate](https://github.com/openshift/windows-machine-config-operator/pull/1516)  was unable to be backported to the release-4.12 branch in time for the 7.1.0 release.
[Slack discussion](https://redhat-internal.slack.com/archives/CM4ERHBJS/p1684417674870159)
=> [release-4.12] Revert "[nodeconfig] Ensure cached WICD creds are set"

cmd/daemon/controller.go, pkg/daemon/certs/certs.go, pkg/daemon/controller/controller.go, pkg/windows/windows.go, test/e2e/proxy_test.go
Cluster admins can provide custom certificates that are required to communicate through their man-in-the-middle egress proxy. This PR covers importing certs Windows nodes so they can become fully proxy aware. 
This is done by updating the local trust store of all Windows instances with the certs present in the trusted-ca ConfigMap.
=> WINC-1090: Support custom CA certificates for cluster-wide proxy

hack/run-ci-e2e-test.sh, test/e2e/delete_test.go, test/e2e/logs_test.go, test/e2e/main_test.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go
Adds various changes required to test upgrading a Windows node from a version of WMCO which supports in-tree storage drivers, to a version that does not.
The changes within `Enable upgrading from in-tree to CSI ` should be reverted when branching for OCP 4.15 occurs, as they will break the tests. Those changes have been labeled with a TODO, and have been purposely been made easily removable.
=> WINC-1043: Test upgrading to CSI storage, from in-tree drivers

pkg/servicescm/servicescm.go, pkg/servicescm/servicescm_test.go
This PR fixes a bug where WMCO is not reacting to changes in the env vars as expected by deleting and re-creating the
invalid services CM object. This was caused by a flawed comparison between the expected and existing CM object.
Fixes: #OCPBUGS-18294
=> OCPBUGS-18294: WMCO is not reacting to new environment variables

Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, hack/common.sh
Update Dockerfiles to use 4.15 base image and prep for 10.15.0 release
This change bumps the operator and OCP version according to the WMCO 10.15.0 release.
Dockerfile and the annotations.yaml file will use v4.14 until v4.15 index images are CVP supported.
Commands ran: 'make bundle'
=> WINC-1053: [build] Update to 4.15 image and prep for 10.15.0

bundle.Dockerfile, bundle/metadata/annotations.yaml
This PR updates the OCP version label used in the bundle.Dockerfile and the annotations.yaml file to use v4.14 index image as it is CVP supported now.
=> [release-4.14] [bundle] Bump to v4.14 OCP version label

test/e2e/providers/aws/aws.go, test/e2e/providers/azure/azure.go, test/e2e/providers/cloudprovider.go, test/e2e/providers/gcp/gcp.go, test/e2e/providers/none/none.go, test/e2e/providers/nutanix/nutanix.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/smb/smb.go, test/e2e/storage_test.go
Adds storage testing on platform none clusters. After deploying the SMB
storage drivers, the test suite creates an SMB fileshare on one of the
Windows nodes and a PersistentVolume which is able to access it.
As part of this commit the CreatePVC() method of the Provider interface
was given an extra optional parameter of a PV. This is necessary to make
use of the previously described changes.
=> [test] SMB storage testing on Platform none

test/e2e/providers/azure/azure.go
Azure Machines do not have to specify a zone. In this case the zone is nil, and could cause a panic when creating a new MachineSet. This is being addressed by not dereferencing the copied zone pointer, and instead using it as is when creating a AzureMachineProviderSpec.
=> Allow possibility of nil Azure zone in CI

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, test/e2e/delete_test.go
Run the EC2Launch v2 service as a hack to restore routes after the HNS networks have been deleted during deconfiguration. This allows the same VM to be configured as a node again.
Fixes OCPBUGS-15988
=> OCPBUGS-15988: Restore routes on AWS Windows 2022 nodes

hack/errata-check.sh
Cosmetic change to use the full WMCO_VERSION from the Makefile due to new 10.y.z vesioning scheme.
=> [hack] Use full WMCO version in errata-check.sh

test/e2e/delete_test.go
Fixes an issue in the deletion suite, which was causing tests to fail if the NOOP Daemonset was not immediately deployed. The wait loop was immediately returning on error, instead of continuing to check after the time interval passed.
=> [test] Fix bad wait logic for NOOP DaemonSet

hack/run-ci-e2e-test.sh, test/e2e/delete_test.go, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go
Includes two cherry-picks required to stop the aws-e2e-upgrade noop daemonset test from failing almost every run.
=> [release-4.12] Unblock aws-e2e-upgrade test

hack/run-ci-e2e-test.sh, test/e2e/delete_test.go, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go
Includes two cherry-picks required to stop the aws-e2e-upgrade noop daemonset test from failing almost every run.
=> [release-4.13] Unblock aws-e2e-upgrade test

hack/run-ci-e2e-test.sh, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go
Running the reconfiguration test causes Machine backed nodes to be deleted, without waiting for a Node to replace them. This is bleeding over to the deletion test suite, and causing failures, and potential false positives there.
=> Prevent reconfigure test from leaving Machine nodes in a bad state

pkg/daemon/cleanup/cleanup.go, pkg/daemon/controller/controller.go, pkg/daemon/envvar/envvar.go
This PR renames the function EnsureVarsAreUpToDate to Reconcile. This removes name stuttering when calling this function form pacakge envVar. It also renames the boolean variable name to a more appt envVarsUpdated.
=> [daemon] Rename envVar function and variables

test/e2e/create_test.go
This change introduces a wait after changing the private key secret on Azure to check all machines provisioned with the outdated windows-user-data were deleted.
In addition, moves the test that changes private key secret while machine configuration to a separate test.
=> [e2e] Wait for deleted machines in Azure

controllers/controllers.go, controllers/controllers_test.go, pkg/cluster/config.go, pkg/metadata/metadata.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go, version/version.go
Blocks the upgrade of Nodes if it will disrupt workloads which have an attached storage volume. Workloads will be disrupted if WMCO is upgrading a node to a kubelet version which is using CSI, from a version which uses in tree volumes.
Users can apply the label
windowsmachineconfig.openshift.io/allow-upgrade in order to unblock the upgrade, and have WMCO upgrade the Node. This allows for the user to confirm that upgraded Nodes have functional storage capabilities, before upgrading any other Nodes.
=> [release-4.14] WINC-1098: Block upgrades when migrating from in-tree to CSI

test/e2e/providers/vsphere/vsphere.go
This change leverage the logic to fetch the providerSpecs from an existing machineSet to get the network configuration and avoid the hard-coded values for CI and development.
In addition, removes the dependency on the env var LEASED_RESOURCE for CI used to read the target network segment.
=> Remove hard-coded default network for vSphere e2e test

pkg/services/services.go
First commit bumps ovn-kubernetes submodule.
Second commit adjusts hybrid-overlay parameters required to use a per-node certificate.
=> OCPBUGS-19943: Fix hybrid-overlay parameters required for certificate management

pkg/services/services.go
First commit bumps ovn-kubernetes submodule.
Second commit adjusts hybrid-overlay parameters required to use a per-node certificate.
=> [release-4.14] OCPBUGS-19949: Fix hybrid-overlay parameters required for certificate management

test/e2e/clusterinfo/openshift.go, test/e2e/create_test.go, test/e2e/proxy_test.go
Proxy tests were not actually running due to an issue with the proxy enabled check.
When enabled, a few of the tests were failing so one was patched and the other was
disabled with the fix coming in another PR (https://github.com/openshift/windows-machine-config-operator/pull/1800).
=> OCPBUGS-19716: Enable proxy cert test to run in CI

pkg/windows/windows.go
This PR adds a necessary wait to our instance reboot flow. 
After kicking off a reboot, we now first wait for the instance to become unreachable via SSH. 
Then it waits for the instance to be back online before returning the reboot as successful.
Previously WMCO checked if the instance is reachable directly after issuing the reboot request, 
which lead to false positives since the instance was viewed as successfully rebooted before the reboot even began.
=> OCPBUGS-17217: Fix "WMCO does not wait for instance to reboot properly"

hack/manifests/csi/azure/01-example-driver-daemonset.yaml, hack/manifests/csi/azure/02-example-namespace.yaml, hack/manifests/csi/azure/03-example-sc.yaml, hack/manifests/csi/azure/04-example-pvc.yaml, hack/manifests/csi/azure/05-example-deployment.yaml
This patch adds the required manifests, in its ideal order, to ensure that Windows workloads can be created with Azure File CSI storage.
=> [hack] Add Azure File CSI Driver Manifests

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/controllers.go, controllers/controllers_test.go, pkg/cluster/config.go, pkg/metadata/metadata.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go, vendor/k8s.io/kubelet/pkg/apis/stats/v1alpha1/types.go, vendor/modules.txt, version/version.go
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1794
=> [release-4.13] WINC-1098: Block upgrades when migrating from in-tree to CSI

pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go
This PR re-orders a deconfiguration step removing files and HNS networks
to be after the instance has finished rebooting. This way WMCO is guaranteed
to only interact with the instance when it is reachable via SSH.
Previously, we were hitting timing issues where, after WICD cleanup is ran,
WMCO's configmap and node controllers would race, resulting in WMCO issuing
SSH commands while the node is still rebooting. These would fail and cause 
deconfiguration to reconcile again, leading to timeouts in CI for our deletion suite.
=> OCPBUGS-18554: Fix "error removing HNS network when cleaning up BYOH proxy nodes"

Makefile, hack/run-ci-e2e-test.sh, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
Manual backport of #1649 needed because one commit [cd47d34b0](https://github.com/openshift/windows-machine-config-operator/commit/cd47d34b0ae6a114ee3a752c1bfdca380fc3d156) went in out of order.
=> [release-4.12] WINC-950: Test WMCO version upgrades

pkg/csr/csr.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/windows.go, pkg/windows/windows_test.go
AzureCloudNodeManagerPath was being copied to all platforms, causing
errors. This change ensures AzureCloudNodeManagerPath is only copied
on Azure.
=> OCPBUGS-5002: Copy Azure setup files only on Azure 

hack/common.sh
Change the `imagePullPolicy` for `olm.sh run` to `Always`. This is needed to ensure that the latest image is always pulled. Revert to `IfNotPresent` on `olm.sh cleanup`. 
Remove the extra quotes from the sed command which was mangling the strings.
=> [hack] Change imagePullPolicy for olm.sh

pkg/daemon/certs/certs.go, pkg/daemon/cleanup/cleanup.go, pkg/daemon/controller/controller.go, test/e2e/delete_test.go, test/e2e/proxy_test.go
WICD controller reacts to changes in the trusted CA bundle that involve
a certificate removal (cert rotation, user disabling cluster-wide proxy, etc). 
Certificates that are removed from the trusted CA bundle are in turn
removed from each Windows node's local trust store and processes. 
This is also the case when nodes are deconfigured. With this, no outgoing
traffic from the node will try to use removed certificates.
=> WINC-688: Support removing proxy certs from Windows nodes

hack/run-ci-e2e-test.sh, test/e2e/logs_test.go, test/e2e/main_test.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go
This reverts commit 378aa320ce74f0e3385c3e1bca54a22d65d2f352.
This needs to be done as in-tree storage is not usable on 4.14.
All upgrades will be from CSI -> CSI.
=> Revert "[test] Enable upgrading from in-tree to CSI"

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco
This removes the go compliance shim output like:
```
2023-10-18T03:16:31.947886521Z Go compliance shim [28] [][]: Forcing GOTOOLCHAIN=local
2023-10-18T03:16:31.950822867Z Go compliance shim [28] [][]: assessment: CGO_ENABLED=1
2023-10-18T03:16:31.958796677Z Go compliance shim [28] [][]: assessment: dynamic linking
2023-10-18T03:16:31.961102618Z Go compliance shim [28] [][]: skipping forced compliance due to GOOS=windows
2023-10-18T03:16:31.986646448Z Go compliance shim [28] [][]: EXEMPT: 1
2023-10-18T03:16:31.988808927Z 
2023-10-18T03:16:31.988808927Z 
2023-10-18T03:16:31.988916101Z Go compliance shim [28] [][]: final command line arguments: "build" "-v" "-mod" "vendor" "-gcflags" "" "-ldflags" "-B 0x80ad4265bd6983364e1614c7463ea2a0efe93137 		" "-o" …
```
=> [build] Silence go compliance shim output

hack/run-ci-e2e-test.sh, test/e2e/delete_test.go, test/e2e/proxy_test.go
This PR enables running proxy removal test which was disabled due to its unreliable behavior.
It has now been modified to wait for the reboot annotation to be applied and to be removed before running the tests.
=> OCPBUGS-19502: Enable proxy removal test

pkg/nodeconfig/nodeconfig.go, test/e2e/delete_test.go, test/e2e/network_test.go
Draining a workload with emptydir data was causing an error due to a lack of the DeleteEmptyDirData field in the drain Helper struct. This change adds the field and sets it to true to resolve the error.
Fixes OCPBUGS-19039
=> OCPBUGS-19039: [nodeconfig] Enable draining nodes with emptydir data

controllers/controllers.go, hack/common.sh, hack/e2e/resources/parallel-upgrade-checker-job.yaml, hack/run-ci-e2e-test.sh, pkg/metadata/metadata.go, pkg/nodeconfig/nodeconfig.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go, test/e2e/wmco_test.go
This PR introduces the `windowsmachineconfig.openshift.io/upgrading` label for Windows nodes to block concurrent upgrades between the WindowsMachine and ConfigMap controllers.
The maximum allowed number of parallel upgrades proposed is fixed to 1. Hence, no matter how many Windows nodes are available, WMCO will upgrade them one at a time. 
ATM, the locking mechanism in the condition package is insufficient as it has a controllers-wide scope that sets the operator condition on each work item across all the controllers. From the OLM perspective, it makes sense, as OLM can track the sub-components of WMCO as a parent entity, but there is a need for sequential control for upgrades.
With the concurrent reconciliation between WindowsMachine and ConfigMap controllers, the level of granularity is …
=> OCPBUGS-8996: Introduce `upgrading` label to block concurrent upgrades

pkg/windows/windows.go
- [[windows] Refactor instance reboot method](https://github.com/openshift/windows-machine-config-operator/commit/2ae380001073f93e9926613e6f96666c1dc32955) 
- [Add SSH off-line check to reboot logic](https://github.com/openshift/windows-machine-config-operator/commit/e70aa4b96902c902b21d25335e40c12ea9af6dd2)
manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1862
=> [release-4.13] OCPBUGS-20259: Fix "WMCO does not wait for instance to reboot properly"

Makefile, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, cmd/operator/main.go, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/rbac/role.yaml, docs/HACKING.md, hack/common.sh, hack/pre-release.sh
Updates the OSDK version to latest v1.32.0.
- Added updates required for Golang/v3 based operators following https://sdk.operatorframework.io/docs/upgrading-sdk-version/ starting from version 1.16.0 to latest 1.32.0.
- Updates the OSDK version in our pre-release.sh script and the hacking script.
- Skipped anything that did not apply to our operator (helm/ansible/non-Go-v3 based operators)
=> WINC-751: Upgrade sdk-operator to 1.32.0

.gitmodules, Makefile
Update kube-proxy submodule to sdn-4.15-kubernetes-1.28.3
=> WINC-1146: Update kube-proxy submodule to sdn-4.15-kubernetes-1.28.3

bundle/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, config/windows-exporter/prometheusRule.yaml, test/e2e/metrics_test.go, test/e2e/storage_test.go
Adds recording rules which translates the windows exporter's CPU and memory metrics into the time series required for display in the OpenShift console.
=> WINC-1181: Add pod CPU and Memory metrics

.ci-operator.yaml, .gitmodules, Makefile, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco, bundle.Dockerfile, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/windows-machine-config-operator.package.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, go.mod, go.sum, hack/lint-gofmt.sh
This change bumps the operator and the OCP version according to WMCO 10.16.0 release.
Ran:
```
make bundle
```
=> WINC-1158: Prep for 10.16.0 release

pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go
The network configuration script contained bad logic to determine if the cni config had the correct contents. The 'expected' config does not contain carriage returns, while the actual created config file does. Because the script did not account for this, the script would always determine that the cni configuration needed to be recreated with the correct contents. This can cause issues with containerd, which needs to reload the configuration everytime this happens.
=> OCPBUGS-21606,OCPBUGS-2887: Fix network config script

bundle.Dockerfile
removes scorecard from bundle.Dockerfile which was preventing bundles from being built.
=> [bundle] remove scorecard from bundle.Dockerfile

controllers/controllers.go
reconcileKubeletClientCA() handles reconciling the kube-apiserver certificate rotation by merging the initial and current CA configmaps for the kube API server signer, however, there is currently no error-check after the call to mergeCAsConfigMaps(). This commit adds an error-check after mergeCAsConfigMaps() is called to make certain no unknown failures are able to slip through.
=> [controllers] Introduce err check when merging CA configmaps

Makefile
[[submodule][kubelet] Update to 4ad3e1bc5d0](https://github.com/openshift/windows-machine-config-operator/commit/cd431608ef3060866dba5e756bada193780edeb8) 
[[build] Update kubelet version to v1.26.11+4ad3e1b](https://github.com/openshift/windows-machine-config-operator/commit/62ec625caab1e15a8b00cb85ef07f6312d786e45)
=> [release-4.13] submodule update 01/02

cmd/operator/main.go, pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go, pkg/windows/windows.go
This reverts commit ab9a1690d1de5bc34ed37106abcbff262473df3b.
We have been given new information that this is not required, the method that was used before was valid.
=> [release-4.15] Revert "Change sourceVIP used for kube-proxy"

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco
This PR sets the value of ENV var GOTOOLCHAIN to local. The default value is auto if not set.
Making this change prevents it from downloading the latest version of toolchain which is incompatible
with Cachito still running on go1.19.
This change is made to maintain parity between the github and midtstream Dockerfiles.
=> [build] Set go toolchain to local

pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go
This commit fixes an issue which would be seen when the cni config file was created with no content. When using the -replace operator with $null, an empty object array was returned. This caused comparison issues with the expected config as it was comparing an array with a string.
=> OCPBUGS-28575: Fix issue with PS type mismatch

docs/byoh-instance-pre-requisites.md, docs/vsphere-golden-image.md, docs/vsphere_ci/scripts/install-firewall-rules.ps1, pkg/secrets/secrets.go, pkg/services/services.go, test/e2e/create_test.go, test/e2e/network_test.go, test/e2e/storage_test.go, test/e2e/upgrade_test.go, test/e2e/validation_test.go
=> [release-4.13] OCPBUGS-28253: Use DSR load balancing in kube-proxy

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci
This is to workaround:
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
which occurs due to the RHSA-2024:0407 fix which intentionally disabled the safe.directory that is required to allow non-root users to interact with the git repo.
=> [release-4.13] build: Build Azure CCM with buildvcs=false

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
This change adds the olm.skipRange attribute to the ClusterServiceVersion manifest to specify a range of versions that should be skipped during upgrades so that the upgrade path skips intermediate versions that may contain issues fixed in the latest patch and minor releases.
Ran:
```
make bundle
```
=> OCPBUGS-27775: [release-4.12] Introduce olm.skipRange to 7.2.1

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
=> [release-4.12] WINC-1113: Introduce feature annotations to CSV

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Adds infrastructure-related annotations: 'features.operators.openshift.io/*' to the operator config CSV file, and sets each to string 'true' or 'false' for the WMCO bundle to pass the new CVP Operator Infrastructure Feature Test in the Operator Bundle Image Validation pipeline.
Ran:
'make bundle'
=> [release-4.14] WINC-1113: Followup

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Adds infrastructure-related annotations: 'features.operators.openshift.io/*' to the operator config CSV file, and sets each to string 'true' or 'false' for the WMCO bundle to pass the new CVP Operator Infrastructure Feature Test in the Operator Bundle Image Validation pipeline.
Ran:
'make bundle'
=> WINC-1113: Followup

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Adds infrastructure-related annotations: 'features.operators.openshift.io/*' to the operator config CSV file, and sets each to string 'true' or 'false' for the WMCO bundle to pass the new CVP Operator Infrastructure Feature Test in the Operator Bundle Image Validation pipeline.
Ran:
'make bundle'
=> [release-4.13] WINC-1113: Followup

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Adds infrastructure-related annotations: 'features.operators.openshift.io/*' to the operator config CSV file, and sets each to string 'true' or 'false' for the WMCO bundle to pass the new CVP Operator Infrastructure Feature Test in the Operator Bundle Image Validation pipeline.
Ran:
'make bundle'
=> [release-4.15] WINC-1113: Followup

test/e2e/storage_test.go
Changes how the upgrade blocked Node is labeled when doing an in-tree to csi storage upgrade. This is required to stop the use of affinities, which will cause issues across WMCO upgrade in the case that Machine Nodes have to be recreated. If the Machine Node is replaced, the pod will be unschedulable, as it will only run on the deleted Node.
=> [release-4.14] Change how upgrade-blocked Node is labeled

bundle.Dockerfile, bundle/metadata/annotations.yaml
=> [bundle] bump version to 4.16

hack/common.sh, hack/pre-release.sh
This change updates the get_operator_sdk function in the hack script to use a temp dir instead of a hard-coded path that may not exist and improve error handling.
In addition, it generalizes the OPERATOR_SDK_VERSION environment variable to be re-used.
=> [hack] Fix get_operator_sdk hardcode path issue

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Adds resource limits for containers, taken from MCO's resource limits.
Testing done on a 4.14 GCP cluster with 10 windows worker node, and a  4.14 platform none cluster, with one windows worker node. 
ran make bundle
=> WINC-703: [config] adds controller manager resource limits

controllers/configmap_controller.go, pkg/cluster/config.go, pkg/nodeconfig/nodeconfig.go, pkg/services/services.go, test/e2e/validation_test.go
This commit reacts to
https://github.com/openshift/cluster-cloud-controller-manager-operator/commit/65c07a6e44bfa1b0cdfadc264d3341c093ffd914
There is no longer a CloudControllerOwner condition on the CCM clusteroperator, as external cloud controllers are now fully default. WMCO will no longer check for this condition, and the logic depending on it should now always be done.
=> OCPBUGS-31626: Stop checking CloudControllerOwner

go.mod, go.sum, vendor/modules.txt
[[vendor] Use v1.28.7+f1b5f6c k8s and OpenShift libraries](https://github.com/openshift/windows-machine-config-operator/pull/2122/commits/5ab605f038e23139410d7680f428d12e0181fdd3)
=> [release-4.15] submodule update 04/03

controllers/configmap_controller.go, pkg/cluster/config.go, pkg/nodeconfig/nodeconfig.go, pkg/services/services.go, test/e2e/validation_test.go
Backport of https://github.com/openshift/windows-machine-config-operator/pull/2117
This commit reacts to
https://github.com/openshift/cluster-cloud-controller-manager-operator/commit/65c07a6e44bfa1b0cdfadc264d3341c093ffd914
There is no longer a CloudControllerOwner condition on the CCM clusteroperator, as external cloud controllers are now fully default. WMCO will no longer check for this condition, and the logic depending on it should now always be done.
=> [release-4.15] OCPBUGS-31704: Stop checking CloudControllerOwner

pkg/windows/windows.go
Stops logging within windows.Run(), and instead lets the caller decide to log. This stops the undesired logging of errors, in the case that Run() is expected to fail.
=> OCPBUGS-20255: Let caller of Run handle error logging

test/e2e/create_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
Collects service logs and the cni config on failures in the e2e tests
=> Collect node logs on e2e failure

hack/run-ci-e2e-test.sh
Increases the timeout for the upgrade test, as we have been seeing panics due to the timeout being hit. Panics make log collection much harder.
=> [test] Increase upgrade test timeout

pkg/internal/containerd_conf.toml, pkg/windows/windows.go
This PR adjusts the containerd base config to pick up CRI plugin config so we can customize runtime settings like image registry configuration. The new directory is added to the set created and deleted by WMCO.
=> WINC-1220: Set config_path for containerd registry settings

hack/setup-cluster-wide-proxy.sh
This commit introduces a helper script to create the required resources and configure a cluster-wide for a given Openshift cluster in AWS.
Sample script output:
```
./hack/setup-cluster-wide-proxy.sh 
Initializing cluster-wide proxy for cluster jvaldes-clus-20240415-xxxvv on AWS
Setting up cluster-wide proxy with name jvaldes-clus-20240415-xxxvv-proxy for AWS in region us-east-1
Found CoreOS image with id ami-04003e644492ae5e8 and release 39.20240322.3.1 for AWS in region us-east-1
Found subnet subnet-074fb20687d116136 for worker node with instance id i-0effc17e730a95d0e in region us-east-1
Found VPC with id vpc-0860d57c0d28182b9 for subnet subnet-074fb20687d116136 in region us-east-1
Finding all subnets associated with vpc-0860d57c0d28182b9
Finding route tables with public gateway …
```
=> [hack] add helper script for cluster-wide proxy

docs/TROUBLESHOOTING.md, docs/vsphere-golden-image.md, docs/vsphere-prerequisites.md, docs/wmco-prerequisites.md
Point to OpenShift docs instead of stale reference to an internal networking pre-req doc.
The internal doc was removed as part of
https://github.com/openshift/windows-machine-config-operator/pull/1513.
=> [doc] Remove stale references to networking doc

bundle/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, config/windows-exporter/prometheusRule.yaml, test/e2e/metrics_test.go
This commit creates a new Prometheus monitoring rule that uses the newly created record for container_metrics introduced for CMO and console.
Ref:
https://github.com/openshift/console/pull/13759
https://github.com/openshift/cluster-monitoring-operator/pull/2314
=> WINC-1180: Use record created for container_network metrics

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, cmd/operator/main.go, config/rbac/role.yaml, controllers/registry_controller.go, pkg/registries/registries.go, pkg/registries/registries_test.go
Goal:
WMCO to create config files compatible with containerd from cluster's mirror registry settings
Approach: 
- introducing a "registry controller" to WMCO which watches to ImageDigestMirrorSet and ImageTagMirrorSet resources
- The controller generates a set of `hosts.toml` containerd config files when cluster settings are updated
=> WINC-1221: WMCO generates hosts.toml file content

README.md
Removes statement on lack of support for pulling images from a registry namespace which requires authentication. It is possible to pull images by authenticating with a kubernetes.io/dockerconfigjson secret.
=> [doc] Adjust private registry support statement

Makefile
Set `buildvcs=false` when building kubelet to fix the 4.13 build pipeline failure in brew builds
This is not an issue with the base image used but an issue that happened after the recent K8s submodule bumps. 
Kicked off a build with the previous commit and it was green.
https://jenkins-cpaas-openshift-winc.apps.cpaas-poc.r6c9.p1.openshiftapps.com/job/release-7.2.2/job/build-pipeline/11/console
https://pkgs.devel.redhat.com/cgit/containers/windows-machine-config-operator/commit/?h=rhaos-4.12-rhel-8&id=8a33b7f11afe3b7be0c6dceabae88d08c66ca32b
=> WINC-1290: [release-4.13] Set buildvcs false

controllers/registry_controller.go, hack/run-ci-e2e-test.sh, pkg/nodeconfig/nodeconfig.go, pkg/registries/registries.go, pkg/registries/registries_test.go, pkg/windows/connectivity.go, pkg/windows/windows.go, test/e2e/delete_test.go, test/e2e/mirror_test.go, test/e2e/wmco_test.go
- [WINC-1222](https://issues.redhat.com//browse/WINC-1222): WMCO applies image mirroring settings to Windows instances
- [WINC-1294](https://issues.redhat.com//browse/WINC-1294): Support token-based auth for mirror registries
This PR transfers containerd registry config files generated by WMCO to
each Windows instance based on the cluster's global image mirroring settings,
allowing containerd to pull Windows images from user-defined mirror locations.
The containerd daemon picks up the registry config without requiring restart.
Containerd also becomes auth-aware in order to support pulling images from secure registries.
We add a header field to each host listed in hosts.tomls with the repo's auth token.
The token for each mirror is taken from cluster's global pull secret.
=> WINC-1222: WMCO applies image mirroring settings to Windows instances

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, .tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml
Adds filtering to prevent konflux builds from happening on doc changes
https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/configuring-builds/proc_preventing_redundant_rebuilds/
=> Don't trigger unecessary konflux builds

pkg/services/services.go
clean cherry-pick of: b3b68b4 
with changes coming from backporting a validating webhook in ovn-kubernetes (https://github.com/openshift/ovn-kubernetes/pull/2053) this backport is needed in order to fully implement the webhook and make the required CNO changes https://github.com/openshift/cluster-network-operator/pull/2261
did not do an automated cherry-pick of PR https://github.com/openshift/windows-machine-config-operator/pull/1850 because there is an additional update to the ovn-kube submodule that was not needed.
=> [release-4.13] OCPBUGS-34669: changes needed for validating webhook

bundle.Dockerfile, bundle/metadata/annotations.yaml
Required until 4.17 redhat-operators index is created
=> [build] Use 4.16 index

controllers/configmap_controller.go, controllers/controllerconfig_controller.go, pkg/nodeconfig/nodeconfig.go, pkg/registries/registries.go, pkg/registries/registries_test.go, pkg/windows/windows.go
This PR adds support for using TLS certs for mirror registries by watching MCO's controllerconfig which holds the ImageRegistryBundleUserData and ImageRegistryBundleData.
These certs are combined into a bundle file and transferred to the trusted bundle store location on Windows nodes. 
If proxy is enabled, these certs are combined with the proxy certs.
=> WINC-1291: Use all existing CAs for TLS auth when pulling images

Makefile, hack/run-ci-e2e-test.sh, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
Removes the old upgrade test, as it has been replaced by the newer upgrade test for a while now. The reconfigure test was moved to run on other cloud platforms as that was the only part of the test run that is not covered elsewhere.
=> WINC-1310: Remove certain tests in old upgrade suite

controllers/configmap_controller.go, pkg/services/services.go
I was mistaken as to how to tell if the nodeAdmission plugin is running, this PR should be able to correctly tell
=>  [release-4.13] OCPBUGS-34669: changes needed for validating webhook

hack/run-ci-e2e-test.sh, pkg/registries/registries.go, pkg/registries/registries_test.go, pkg/windows/windows.go, test/e2e/create_test.go, test/e2e/main_test.go, test/e2e/mirror_test.go, test/e2e/network_test.go, test/e2e/wmco_test.go
Update WICD args to include CA bundle path irrespective of cluster proxy settings.
=> OCPBUGS-35936: Update WICD args to include CA bundle path

hack/machineset.sh
This commit updates the machineset.sh script to follow the 4.17 naming convention for securityGroups and subnet in AWS.
=> Align machineset.sh with 4.17 updates for securityGroups and subnet in AWS

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Increase memory resource requests and limits as the current limits are proving to be insufficient in an upgrade scenario, tested in QE clusters.
=> OCPBUGS-36395: [config] Increase controller manager resource limits

Makefile, hack/run-ci-e2e-test.sh, test/e2e/reconfigure_test.go, test/e2e/secrets_test.go, test/e2e/upgrade_test.go, test/e2e/wmco_test.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2250
=> [release-4.13] WINC-1310: Remove certain tests in old upgrade suite

pkg/csr/csr.go
This fixes an issue where if reverse lookup fails due to an error, such as reverse lookup services being down, WMCO would not fall back to using the VM hostname to determine if a CSR should be approved.
=> OCPBUGS-36643: Handle reverse lookup error correctly

README.md
This commits updates the upgrade process described in the README.md so that it aligns with the current behavior of the Windows instances during an upgrade, specially:
- Machines instances are no longer deleted
- Parallel node upgrades are limited to 1
=> [docs] Update details for upgrade process

README.md
This commit removes the hard-coded OCP version from the reference link to the documentation and make them dynamic by pointing to the latest.
=> [docs] Remove hard-coded  links to older OCP version

docs/vsphere_ci/README.md, docs/vsphere_ci/vcenter_copy_template/README.md, docs/vsphere_ci/vcenter_copy_template/getem.sh, docs/vsphere_ci/vcenter_copy_template/options.json, docs/vsphere_ci/vcenter_copy_template/putem.sh, docs/vsphere_ci/vcenter_copy_template/sourcedevqe, docs/vsphere_ci/vcenter_copy_template/sourceibm-ci, docs/vsphere_ci/vcenter_copy_template/sourcevcs8e, docs/vsphere_ci/windows-server-2022.pkr.hcl
- Updates packer config to work on new DEV/QE environment
- Adds scripts and documentation to copy over VMs across vCenter environments, to be used only as a last resort to move existing VMs (created via packer or otherwise) to CI environments.
=> WINC-1199: Fix VM creation automation in new vCenter

pkg/daemon/powershell/powershell.go
Aligns how WICD runs powershell commands with WMCO. Prevents commands from failing to run when ExecutionPolicy is set to restricted, which may be default depending on the VM image used.
=> OCPBUGS-30995: Bypass ExecutionPolicy running commands

test/e2e/mirror_test.go
Increase retry interval when checking for image mirroring settings on nodes. 15s can be too short for the Job pod to complete since it SSHs into the node. Use 1 minute instead, like is done elsewhere in the e2e tests for such Job pods.
Done to address flaky behavior presenting as timeouts waiting for the Job pod to succeed.
=> [e2e] Increase retry interval for mirror test

.gitmodules, Makefile, hack/update_submodules.sh
Switches to maintain kube-proxy repo by tag off of o/k's master branch.
With SDN no longer carrying kube-proxy patches, we no longer need to
have our submodule track a specific branch -- we can directly checkout
the tag we need without waiting for branch creation.
If we need upstream fixes later, we just update the submodule version
in our build an hack scripts to get the desired tag (e.g. `v1.30.2`).
Ran `./hack/update_submodules.sh -m kube-proxy -r master master`
=> WINC-1305: Move kube-proxy submodule build from tags (v1.30.0)

bundle.Dockerfile, bundle/metadata/annotations.yaml
Labels the bundle to be included in the 4.17 Red Hat operator index
=> WINC-1314: Use 4.17 Red Hat operator index

test/e2e/network_test.go, test/e2e/upgrade_test.go
Collects job logs in one go, rather than using two API calls, one to gather the logs to print to a file, and one to return the logs to the caller.
=> [test] Job log collection as a single action

README.md, pkg/nodeconfig/nodeconfig.go, pkg/secrets/secrets.go, pkg/windows/windows.go, test/e2e/create_test.go
Add a special command to the AWS userdata to add persistent routes for
the metadata endpoint, installs the EC2Launch.exe if missing, checks
the minimum required version and upgrades if needed.
This will allow the same VM to be configured, deconfigured, and reconfigured
without losing access to the metadata endpoint.
follow-up to prev PR, credits to @aravindhp 
- https://github.com/openshift/windows-machine-config-operator/pull/1847
=> WINC-1149: Use userdata task to persistent instance metadata routes  in AWS

README.md, docs/TROUBLESHOOTING.md
This PR documents the process of gratefully rebooting a Windows node
by adding references to the official OCP guidelines along with the specific
PowerShell command.
In addition, it provides a workaround to an AWS limitation where the EC2 instance metadata endpoint becomes unavailable, preventing the node from reaching the ready state.
=> OCPBUGS-36305: Document graceful Node reboot and add workaround for issue in AWS

pkg/nodeconfig/nodeconfig.go
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2285
This is a behavior change which comes as a result of inconsistencies across OCP platforms and versions. Previously WMCO would check if the cluster created a SA token secret for the WICD SA, and if it exists would use the cluster created secret, else it would create its own secret.
We are finding that on upgrades from 4.15 to 4.16 the secret was missing on 4.15, but then created by an entity in the cluster on 4.16. This is throwing off WMCO's logic to get the secret as there will be multiple SA token secrets, one created by WMCO in 4.15, and an additional one when the 4.16 upgrade occurs.
This commit remedies this issue by having WMCO only use the secret it creates, ignoring any other service …
=> [release-4.15] OCPBUGS-38485: Always use created WICD SA token

bundle/manifests/windows-exporter_v1_service.yaml, config/windows-exporter/kustomization.yaml, pkg/metrics/metrics.go
This PR fixes the make bundle command that was broken with recent changes to serviceMonitor. It removes the servicemonitor.yaml requirement from kustomization.yaml since the responsiblity of its generation has been moved from OLM to WMCO.
It also fixes the kubebuilder delimiters in metrics.go file.
=> [bundle] Fix 'make bundle'

build/Dockerfile
This PR fixes the Dockerfile to change the WOKDIR Back to /payload/
after copying windows_exporter files.
=> [build] Fix Dockerfile WORKDIR

hack/manifests/csi/vsphere/01-example-driver-daemonset.yaml, test/e2e/providers/vsphere/vsphere.go
Use the new community owned registry for vSphere CSI driver image after the old one was deprecated and bump the driver version
=> WINC-1326: Use new repo for vSphere CSI driver image

pkg/daemon/controller/controller.go, pkg/daemon/controller/controller_test.go, pkg/nodeconfig/payload/payload.go, pkg/nodeconfig/payload/payload_test.go, pkg/services/services.go, pkg/servicescm/servicescm.go, pkg/windows/windows.go
launching kube-proxy with flags is now deprecated. Changes to using a config file instead.
This adds the creation of the kube-proxy config file to the script run before setting up kube-proxy. This script also contains the post-configuration setup steps for  CNI. Ideally this script will be broken up or retired, and we will be able to generate the kube-proxy configuration in a more idiomatic way.
=> WINC-710: replaces kube-proxy flags with config file

pkg/daemon/fake/manager.go, pkg/daemon/fake/winsvc.go, pkg/daemon/manager/manager.go, pkg/daemon/winsvc/winsvc.go
Changes the code to list Windows services dependencies to use the function which was upstreamed into the go windows svc libraries.
=> WINC-1337: Use upstreamed dependency code

bundle.Dockerfile
This PR updates the operator-supported version label to 4.18. We were waiting for CVP to support
4.18 before making this change, this can be done with the latest support announcement.
This will also help with a failing CVP test that checks if the OCP version label corresponds to the minkubeversion specified in the CSV.
=> WINC-1329: [bundle.Dockerfile] Update supported version to 4.18

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, pkg/cluster/config.go, pkg/cluster/config_test.go
Supports k8s versions 1.30 & 1.31.
=> OCPBUGS-42827: [release-4.17] Adjust k8s version for kube 1.30

hack/machineset.sh, test/e2e/providers/azure/azure.go
This PR hardcodes Azure VMs to a specific version as the latest build released by MSFT is unstable. Any Windows Server 2019 VMs created from the October 2024 release `"version": "17763.6414.241004"` has issues preventing SSH connections.
Required to unblock CI. Should be reverted when patched Windows Server images are released.
=> Hardcode Azure SKU version for 2019 nodes

docs/wmco-prerequisites.md
This PR moves the Supported Installation method section up in the
Pre-Requisites to highlight that UPI is supported for platform:none.
=> OCPBUGS-18898: Highlight UPI support for platform:none and update pre-req docs

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.konflux
CNI submodule is compiled by explicitly setting CGO_ENABLED=0 which is not FIPS compliant. This commit remidaiates this by using a Windows-compatible C compiler “CC=gcc-mingw-w64” in the go build command.
=> WINC-1352: Build CNI plugins with CGO_ENABLED

renovate.json
Adds a renovate.json from
https://github.com/konflux-ci/mintmaker/blob/main/config/renovate/renovate.json
This is the default config that konflux uses. I added an ignoreDeps field to prevent the kubelet, kube-proxy, and containerd submodules from being updated automatically. This is because they need to be updated using hack/update-submodules.sh, in order to present the correct versioning.
=> [release-4.17] Prevent some submodule auto-updates

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco, build/build.sh
This PR updates the base image used in Dockerfile to use the golang builder image recommended for FIPS compliant operators and flips the CGO_ENABLED variable to value 1 in the operator build command.
=> WINC-1351: Fix WMCO's go build command to FIPS compliant

.tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml, .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-17-push.yaml, build/Dockerfile.konflux, build/bundle-konflux.Dockerfile
Adds changes to adhere to the required build policies
Also prevents operator from being built when only the bundle should built.
=> [release-4.17] Adjust konflux pipelines to work with Enterprise Contract

.tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml, .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-17-push.yaml
Set konflux builds to run without network connection. Required for compliance reasons.
=> [release-4.17] Enable hermetic builds for konflux

README.md
This PR adds support statement for HPA on Windows Containers. This feature has become available after recent monitoring development to get the pod resource metrics.  Tested this locally and it works for deployment scaling.
Needs to be verified by QE.
=> WINC-1353: HPA support for Windows Containers

controllers/configmap_controller.go
This PR triggers a restart after deleting malformed ClusterRoleBinding, so that the new instance of the operator pod reconciles with the newly created resources.
=> OCPBUGS-23121: Restart operator pod on malformed RBAC

controllers/configmap_controller.go
This PR reacts to rendered-worker changes by regenerating the ServicesManifest when the rendered-worker changes. This ensures that the ServicesManifest always stays up to date with the full state of the rendered-worker.
=> WINC-897: Regenerate servicesmanifest on rendered-worker update 

go.mod, go.sum, vendor/golang.org/x/crypto/ssh/server.go, vendor/golang.org/x/net/html/doctype.go, vendor/golang.org/x/net/html/foreign.go, vendor/golang.org/x/net/html/parse.go, vendor/modules.txt
This PR bumps the x/net dependency to v0.33.0
to fix CVE-2024-45338.
Ran: go mod tidy && go mod vendor
=> [release-4.18] OCPBUGS-47444: Bump x/net to v0.33.0

build/Dockerfile.konflux, build/bundle-konflux.Dockerfile
This label is used by the konflux RPA to tag the image with the correct semver.
=> Add version label to operator image

.tekton/images-mirror-set.yaml, build/bundle-konflux.Dockerfile
Changes the registry to stage as master will never have a production release. As there will be no prod RPA for master, the renovate nudge functionality will not work properly without this change.
=> Change operator image ref to stage

Containerfile.bundle
Was incorrectly using tag + digest. When referencing an image only the digest should be used.
=> [release-4.18] Fix WMCO image reference

Containerfile
This commit sets the value of GOEXPERIMENT
variable in Containerfile to strictfipsruntime.
This change is required to build fips compliant
images and is in line with rest of the container
files.
=> Run with GOEXPERIMENT var strictfipsruntime

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.base, build/Dockerfile.ci, build/Dockerfile.wmco, bundle.Dockerfile
- Use golang builder image in line with OCP 4.19
- adjust dockerfile for OCP 4.19
Release repo counter part:
- https://github.com/openshift/release/pull/61109
=> Use golang builder image and bundle dockerfile  in line with OCP 4.19

.gitignore, test/e2e/create_test.go, test/e2e/validation_test.go
- introduces the `nodes.json` file in the nodes artifact dir
with a dump of the existing Windows node objects so that there is information
of the Windows node objects after the test suite ends.
- deletes the getInstanceIDsOfNodes and getInstanceID helpers,
no longer in use.
=> Add node object to e2e artifacts and remove unused test code

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml, docs/TROUBLESHOOTING.md, hack/run-ci-e2e-test.sh
Debug logging can now be enabled by configuring the OLM subscription.
=> OCPBUGS-50511: Make debugLogging non-default

go.mod, test/e2e/create_test.go, test/e2e/network_test.go
Adds a packet trace to the networking tests which is saved in the artifacts of test runs.
Adds various improvements to timing to prevent the test run from being killed by timeout.
This is required to allow the packet trace to be completed before ending the test.
=> WINC-720: Improve network tests and add packet trace

renovate.json
As submodule updates can't be selectively disabled, disable all submodule updates through renovate.
=> Disable submodule renovate

test/e2e/network_test.go
This PR fixes the issues in the East West Networking test by:
- Explicitly defining resource requests and limits of the Linux and Windows  web server pods to significantly reduce the likelihood of them being terminated due to resource constraints.
- Fetching the Linux and Windows webserver pod IP right after creating the corresponding curl job.
In addition:
**Debugging Enhancements:**
- Added logging of host and pod IP addresses to the Linux Webserver.
- Introduced logging of the Windows pod IP address in WinCurler and the server IP address in WinServer.
- Included response content logging in WinCurler for better troubleshooting.
- Enabled verbosity in the LinuxCurler command to provide detailed output.
- Added debug logging to the WinCurler curl script.
**Code Readability and …
=> OCPBUGS-48713: Improve debugging capabilities, code readability, and reliability in network tests

controllers/metric_controller.go
This commit fixes the controller to generate events when the cluster-monitoring label is not present or removed from the operator namespace.
=> OCPBUGS-45027: No Events Generated after changing cluster-monitoring Label

hack/common.sh
This commit replaces the dependency on jq for a core utility to parse the ConfigMap in the common.sh script so that the e2e test scripts does not depend on jq binary installed in the CI image.
=> Stop depending on `jq` binary in e2e run script

hack/machineset.sh, test/e2e/providers/azure/azure.go
reacts to
- https://github.com/openshift/machine-api-provider-azure/pull/133
relates to:
- https://github.com/openshift/installer/pull/9538
- https://github.com/openshift/cluster-capi-operator/pull/276
=> Allow Azure machineSet to conditionally set ManagedIdentity

.tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml, .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-18-push.yaml
increasing our resource request to 10gi to avoid OOMkill. Should probably be lowered.
based on the docs here
https://konflux.pages.redhat.com/docs/users/building/overriding-compute-resources.html
=> WINC-1380 [release-4.18] - increases resource limits to avoid OOMkilling

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, .tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml
increasing our resource request to 10gi to avoid OOMkill. Should probably be lowered. 
based on the docs here 
https://konflux.pages.redhat.com/docs/users/building/overriding-compute-resources.html
=> [WINC-1380] increases resource limits to avoid OOMkilling

.tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml, .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-15-push.yaml
=> WINC-1380: [release-4.15]  Add shell and unicode sast pipeline tasks 

pkg/secrets/secrets.go
This PR updates the  EC2LaunchV2 minimum version to address the conflict with hybrid-overlay network interfaces.
=> OCPBUGS-35285:  bump AWS EC2LaunchV2 min version to 2.0.2107

.tekton/windows-machine-config-operator-bundle-master-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-master-push.yaml, .tekton/windows-machine-config-operator-master-pull-request.yaml, .tekton/windows-machine-config-operator-master-push.yaml
This step is the one in particular that is going OOM. Only it should be given the memory increase.
=> WINC-1383: Bump use-trusted-artifact step memory

test/e2e/main_test.go, test/e2e/network_test.go, test/e2e/providers/aws/aws.go
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2658
=> [release-4.16] WINC-1365: Fix e2e warnings

test/e2e/providers/azure/azure.go
Updates the MachineSet spec to be in line with Linux MachineSets by
adding the BootDiagnostics field, using the cluster's public LB,
and basing the vmSize off the Linux MachineSet.
=> WINC-1189: Add publicLoadBalancer to azure test VMs

Containerfile.bundle
This commit updates the operator image digest to
the latest one. Replacement command for date
in CSV is also added here.
=> [release-4.15] Update operator image digest

test/e2e/certificates_test.go, test/e2e/validation_test.go
This PR fixes the formatting in error message for kubelet CA certificate assertion and  the error message in e2e windows pods:
```
Could not create directory '/.ssh' (Permission denied).
Failed to add the host to the list of known hosts (/.ssh/known_hosts).
```
for example:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_windows-machine-config-operator/2843/pull-ci-openshift-windows-machine-config-operator-master-vsphere-disconnected-e2e-operator/1916921306410913792/artifacts/vsphere-disconnected-e2e-operator/windows-e2e-operator-test/artifacts/pods/job-name=check-win-dirs-job-jz8n7/job-name=check-win-dirs-job-jz8n7.log
=> Fix unknown verb in message and ignore SSH known hosts in test suite

go.mod, vendor/modules.txt
This commit addresses CVE-2025-30204 in transitive deps that are still using vulnerable v4 and v5 versions
=> vendor: fix golang-jwt to v4.5.2 and v5.2.2

go.mod, go.sum, vendor/modules.txt
Fixes:
- CVE-2025-22868
- CVE-2025-30204 
- CVE-2025-22869
=> [release-4.18] OCPBUGS-51967,OCPBUGS-51980,OCPBUGS-54113: update vendor deps oauth2, crypto and jwt 

pkg/windows/windows.go
Windows machines using a different language set will not return the word FAILED. Remove the word failed to allow any language to be used.
=> OCPBUGS-54224: removed the FAILED keyword to not depend on internationalization

.tekton/images-mirror-set.yaml, .tekton/windows-machine-config-operator-bundle-release-4-20-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-20-push.yaml, .tekton/windows-machine-config-operator-release-4-20-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-20-push.yaml
As the master branch tracks 4.20 development for now, the master application and components have been removed. The 4.20 application and components will be used in master until the next branching day.
=> React to master application removal

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, cmd/operator/main.go, config/manager/manager.yaml
$(ARGS) is not being processed correctly when the operator is ran without another argument before it.
=> Change how extra arguments are processed

Containerfile.bundle, README.md, bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml, docs/HACKING.md, docs/TROUBLESHOOTING.md, docs/machineset-nutanix.md, docs/nutanix-prerequisites.md, docs/vsphere-golden-image.md, docs/vsphere-prerequisites.md, docs/wmco-prerequisites.md, hack/community/csv/description.md, pkg/services/services.go, test/e2e/network_test.go, test/e2e/providers/vsphere/vsphere.go, test/e2e/storage_test.go
updates all docs link to redhat.com to the latest version.
=> WINC-1376: Replace docs.openshift.com for docs.redhat.com  

.tekton/windows-machine-config-operator-bundle-release-4.19-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4.19-push.yaml, .tekton/windows-machine-config-operator-release-4.19-pull-request.yaml, .tekton/windows-machine-config-operator-release-4.19-push.yaml
Reacts to task-sast-unicode-check-oci-ta migration
from 0.2 to 0.3 and adds the now required image-digest to
the sast-unicode-check task.
https://github.com/konflux-ci/build-definitions/blob/main/task/sast-unicode-check-oci-ta/0.3/MIGRATION.md
=> [release-4.19] Update Konflux references and add image digest to task-sast-unicode-check-oci-ta 

.tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml, .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-18-push.yaml
Reacts to task-sast-unicode-check-oci-ta migration
from 0.2 to 0.3 and adds the now required image-digest to
the sast-unicode-check task.
https://github.com/konflux-ci/build-definitions/blob/main/task/sast-unicode-check-oci-ta/0.3/MIGRATION.md
=> [release-4.18] WINC-1417: Update Konflux references and add image digest to task-sast-unicode-check-oci-ta

.tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml, .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml, .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml, .tekton/windows-machine-config-operator-release-4-15-push.yaml
Reacts to task-sast-unicode-check-oci-ta migration
from 0.2 to 0.3 and adds the now required image-digest to
the sast-unicode-check task.
https://github.com/konflux-ci/build-definitions/blob/main/task/sast-unicode-check-oci-ta/0.3/MIGRATION.md
=> [release-4.15] WINC-1417: Update Konflux references and add image digest to task-sast-unicode-check-oci-ta

test/e2e/wmco_test.go
This reduces the retry interval from 60 -> 15 seconds. This change reduces the potential wasted time of a Node finishing configuration immediately after a retry.
=> Reduce node retry interval in e2e tests

controllers/configmap_controller.go, controllers/controllers.go, controllers/node_controller.go, controllers/registry_controller.go, controllers/secret_controller.go, pkg/csr/csr.go, pkg/nodeconfig/init.go, pkg/nodeconfig/nodeconfig.go, pkg/windows/connectivity.go, pkg/windows/windows.go
Adds Close() methods to NodeConfig and Windows interfaces to allow callers to ensure that SSH connections to the VM are closed.
=> OCPBUGS-60482: Fix SSH connection leak

bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml, config/manager/manager.yaml
removes the deprecation warning by updating the NodeSelector from master to control-plane
=> WINC-1366: changes NodeSelector from master to control-plane

pkg/windows/connectivity.go
A warning is being logged as not all conditions for determining if the SSH connection is already closed are being checked.
=> Fix sshConnectivity close error handling

test/e2e/network_test.go, test/e2e/upgrade_test.go
We are reporting jobs as failed if a pod within the job failed. This is incorrect logic, as a single pod failing is not a failure state for the entire job. The job will keep creating pods until a success is seen.
=> OCPBUGS-60771: Fix job success logic

test/e2e/create_test.go, test/e2e/logs_test.go, test/e2e/main_test.go, test/e2e/network_test.go
Adds configuration times to the e2e artifacts when creation tests are ran.
Example file contents:
{"nodeType":"machine","nodeCount":1,"machineProvisioned":"3m40s","sshAvailable":"10s","nodeConfigured":"4m30s"}
{"nodeType":"byoh","nodeCount":1,"nodeConfigured":"5m45s"}
=> WINC-1442: Save configuration time data to artifacts directory

.gitmodules
update to the `.gitmodules` file, specifying that the `windows_exporter` submodule should track the `release-4.20` branch.
=> [release-4.20] set windows_exporter submodule to 4.20 branch

Containerfile
=> chore(KONFLUX-6210): fix and set name and cpe label for windows-machine-config-operator-release-4-19

Containerfile
=> chore(KONFLUX-6210): fix and set name and cpe label for windows-machine-config-operator-release-4-17

Containerfile
=> chore(KONFLUX-6210): fix and set name and cpe label for windows-machine-config-operator-release-4-18

Containerfile
=> chore(KONFLUX-6210): fix and set name and cpe label for windows-machine-config-operator-release-4-16

Containerfile.bundle
=> chore(KONFLUX-6210): fix and set name and cpe label for windows-machine-config-operator-bundle-release-4-17

Containerfile.bundle
=> chore(KONFLUX-6210): fix and set name and cpe label for windows-machine-config-operator-bundle-release-4-18

renovate.json
Add gomod manager and vendor directory handling to automatically update Go dependencies and their vendored files via Renovate PRs.
=> Enable Go dependency updates in Renovate config
